// adjectives-db-a1.js - A1 Level Adjectives
const adjectivesA1 = [
  {word:"gut",comparative:"besser",superlative:"am besten",translations:["good"],examples:["Das Essen ist gut.","Ein guter Freund."]},
  {word:"schlecht",comparative:"schlechter",superlative:"am schlechtesten",translations:["bad"],examples:["Das Wetter ist schlecht.","Eine schlechte Idee."]},
  {word:"groß",comparative:"größer",superlative:"am größten",translations:["big","large","tall"],examples:["Ein großes Haus.","Er ist groß."]},
  {word:"klein",comparative:"kleiner",superlative:"am kleinsten",translations:["small","little"],examples:["Ein kleines Kind.","Die Wohnung ist klein."]},
  {word:"alt",comparative:"älter",superlative:"am ältesten",translations:["old"],examples:["Ein altes Auto.","Ich bin 25 Jahre alt."]},
  {word:"jung",comparative:"jünger",superlative:"am jüngsten",translations:["young"],examples:["Ein junger Mann.","Sie ist jung."]},
  {word:"neu",comparative:"neuer",superlative:"am neuesten",translations:["new"],examples:["Ein neues Buch.","Das ist neu."]},
  {word:"schön",comparative:"schöner",superlative:"am schönsten",translations:["beautiful","nice"],examples:["Ein schöner Tag.","Das Wetter ist schön."]},
  {word:"hässlich",comparative:"hässlicher",superlative:"am hässlichsten",translations:["ugly"],examples:["Ein hässliches Gebäude."]},
  {word:"schnell",comparative:"schneller",superlative:"am schnellsten",translations:["fast","quick"],examples:["Ein schnelles Auto.","Er läuft schnell."]},
  {word:"langsam",comparative:"langsamer",superlative:"am langsamsten",translations:["slow"],examples:["Eine langsame Schildkröte.","Geh langsam!"]},
  {word:"teuer",comparative:"teurer",superlative:"am teuersten",translations:["expensive"],examples:["Ein teures Restaurant.","Das ist zu teuer."]},
  {word:"billig",comparative:"billiger",superlative:"am billigsten",translations:["cheap"],examples:["Ein billiges Hotel.","Das war billig."]},
  {word:"leicht",comparative:"leichter",superlative:"am leichtesten",translations:["easy","light"],examples:["Eine leichte Aufgabe.","Der Koffer ist leicht."]},
  {word:"schwer",comparative:"schwerer",superlative:"am schwersten",translations:["difficult","heavy"],examples:["Eine schwere Prüfung.","Der Koffer ist schwer."]},
  {word:"lang",comparative:"länger",superlative:"am längsten",translations:["long"],examples:["Eine lange Straße.","Das Buch ist lang."]},
  {word:"kurz",comparative:"kürzer",superlative:"am kürzesten",translations:["short"],examples:["Eine kurze Pause.","Der Rock ist kurz."]},
  {word:"hoch",comparative:"höher",superlative:"am höchsten",translations:["high","tall"],examples:["Ein hoher Berg.","Die Preise sind hoch."]},
  {word:"niedrig",comparative:"niedriger",superlative:"am niedrigsten",translations:["low"],examples:["Ein niedriges Gebäude.","Niedrige Preise."]},
  {word:"warm",comparative:"wärmer",superlative:"am wärmsten",translations:["warm"],examples:["Ein warmer Tag.","Das Wasser ist warm."]},
  {word:"kalt",comparative:"kälter",superlative:"am kältesten",translations:["cold"],examples:["Ein kalter Winter.","Das Bier ist kalt."]},
  {word:"heiß",comparative:"heißer",superlative:"am heißesten",translations:["hot"],examples:["Ein heißer Sommer.","Der Kaffee ist heiß."]},
  {word:"hell",comparative:"heller",superlative:"am hellsten",translations:["bright","light"],examples:["Ein heller Raum.","Es ist hell."]},
  {word:"dunkel",comparative:"dunkler",superlative:"am dunkelsten",translations:["dark"],examples:["Ein dunkler Raum.","Es wird dunkel."]},
  {word:"laut",comparative:"lauter",superlative:"am lautesten",translations:["loud"],examples:["Laute Musik.","Sei nicht so laut!"]},
  {word:"leise",comparative:"leiser",superlative:"am leisesten",translations:["quiet"],examples:["Eine leise Stimme.","Sprich leise!"]},
  {word:"sauber",comparative:"sauberer",superlative:"am saubersten",translations:["clean"],examples:["Ein sauberes Zimmer.","Das Auto ist sauber."]},
  {word:"schmutzig",comparative:"schmutziger",superlative:"am schmutzigsten",translations:["dirty"],examples:["Schmutzige Hände.","Die Straße ist schmutzig."]},
  {word:"reich",comparative:"reicher",superlative:"am reichsten",translations:["rich"],examples:["Ein reicher Mann.","Sie sind reich."]},
  {word:"arm",comparative:"ärmer",superlative:"am ärmsten",translations:["poor"],examples:["Arme Leute.","Er ist arm."]},
  {word:"voll",comparative:"voller",superlative:"am vollsten",translations:["full"],examples:["Ein volles Glas.","Der Bus ist voll."]},
  {word:"leer",comparative:"leerer",superlative:"am leersten",translations:["empty"],examples:["Ein leeres Zimmer.","Die Flasche ist leer."]},
  {word:"stark",comparative:"stärker",superlative:"am stärksten",translations:["strong"],examples:["Ein starker Mann.","Starker Kaffee."]},
  {word:"schwach",comparative:"schwächer",superlative:"am schwächsten",translations:["weak"],examples:["Eine schwache Person.","Ich bin schwach."]},
  {word:"dick",comparative:"dicker",superlative:"am dicksten",translations:["thick","fat"],examples:["Ein dickes Buch.","Er ist dick."]},
  {word:"dünn",comparative:"dünner",superlative:"am dünnsten",translations:["thin"],examples:["Dünnes Papier.","Sie ist dünn."]},
  {word:"breit",comparative:"breiter",superlative:"am breitesten",translations:["wide"],examples:["Eine breite Straße.","Der Fluss ist breit."]},
  {word:"schmal",comparative:"schmaler",superlative:"am schmalsten",translations:["narrow"],examples:["Ein schmaler Weg.","Das Bett ist schmal."]},
  {word:"süß",comparative:"süßer",superlative:"am süßesten",translations:["sweet"],examples:["Süßer Kuchen.","Das ist süß!"]},
  {word:"sauer",comparative:"saurer",superlative:"am sauersten",translations:["sour"],examples:["Saure Zitrone.","Die Milch ist sauer."]},
  {word:"salzig",comparative:"salziger",superlative:"am salzigsten",translations:["salty"],examples:["Salziges Essen.","Das ist zu salzig."]},
  {word:"scharf",comparative:"schärfer",superlative:"am schärfsten",translations:["spicy","sharp"],examples:["Scharfes Essen.","Ein scharfes Messer."]},
  {word:"frisch",comparative:"frischer",superlative:"am frischesten",translations:["fresh"],examples:["Frisches Brot.","Die Luft ist frisch."]},
  {word:"alt (Brot)",comparative:"älter",superlative:"am ältesten",translations:["stale"],examples:["Altes Brot.","Das Brot ist alt."]},
  {word:"gesund",comparative:"gesünder",superlative:"am gesündesten",translations:["healthy"],examples:["Gesundes Essen.","Ich bin gesund."]},
  {word:"krank",comparative:"kränker",superlative:"am kränksten",translations:["sick","ill"],examples:["Ein kranker Mensch.","Ich bin krank."]},
  {word:"müde",comparative:"müder",superlative:"am müdesten",translations:["tired"],examples:["Ich bin müde.","Müde Augen."]},
  {word:"wach",comparative:"wacher",superlative:"am wachsten",translations:["awake"],examples:["Ich bin wach.","Wache Augen."]},
  {word:"hungrig",comparative:"hungriger",superlative:"am hungrigsten",translations:["hungry"],examples:["Ich bin hungrig.","Hungrige Kinder."]},
  {word:"satt",comparative:"satter",superlative:"am sattesten",translations:["full (after eating)"],examples:["Ich bin satt.","Danke, ich bin satt."]},
  {word:"glücklich",comparative:"glücklicher",superlative:"am glücklichsten",translations:["happy"],examples:["Ein glücklicher Mensch.","Ich bin glücklich."]},
  {word:"traurig",comparative:"trauriger",superlative:"am traurigsten",translations:["sad"],examples:["Ein trauriges Kind.","Ich bin traurig."]},
  {word:"fröhlich",comparative:"fröhlicher",superlative:"am fröhlichsten",translations:["cheerful","merry"],examples:["Fröhliche Menschen.","Sie ist fröhlich."]},
  {word:"lustig",comparative:"lustiger",superlative:"am lustigsten",translations:["funny","fun"],examples:["Ein lustiger Film.","Das ist lustig!"]},
  {word:"langweilig",comparative:"langweiliger",superlative:"am langweiligsten",translations:["boring"],examples:["Ein langweiliger Film.","Das ist langweilig."]},
  {word:"interessant",comparative:"interessanter",superlative:"am interessantesten",translations:["interesting"],examples:["Ein interessantes Buch.","Das ist interessant."]},
  {word:"wichtig",comparative:"wichtiger",superlative:"am wichtigsten",translations:["important"],examples:["Eine wichtige Nachricht.","Das ist wichtig."]},
  {word:"unwichtig",comparative:"unwichtiger",superlative:"am unwichtigsten",translations:["unimportant"],examples:["Ein unwichtiges Detail.","Das ist unwichtig."]},
  {word:"richtig",comparative:"richtiger",superlative:"am richtigsten",translations:["correct","right"],examples:["Die richtige Antwort.","Das ist richtig."]},
  {word:"falsch",comparative:"falscher",superlative:"am falschesten",translations:["wrong","false"],examples:["Eine falsche Antwort.","Das ist falsch."]},
  {word:"einfach",comparative:"einfacher",superlative:"am einfachsten",translations:["simple","easy"],examples:["Eine einfache Aufgabe.","Das ist einfach."]},
  {word:"kompliziert",comparative:"komplizierter",superlative:"am kompliziertesten",translations:["complicated"],examples:["Eine komplizierte Aufgabe.","Das ist kompliziert."]},
  {word:"nah",comparative:"näher",superlative:"am nächsten",translations:["near","close"],examples:["Ein nahes Ziel.","Das ist nah."]},
  {word:"fern",comparative:"ferner",superlative:"am fernsten",translations:["far","distant"],examples:["Ferne Länder.","Das ist fern."]},
  {word:"früh",comparative:"früher",superlative:"am frühesten",translations:["early"],examples:["Früher Morgen.","Es ist früh."]},
  {word:"spät",comparative:"später",superlative:"am spätesten",translations:["late"],examples:["Später Abend.","Es ist spät."]},
  {word:"pünktlich",comparative:"pünktlicher",superlative:"am pünktlichsten",translations:["punctual","on time"],examples:["Er ist pünktlich.","Pünktliche Ankunft."]},
  {word:"modern",comparative:"moderner",superlative:"am modernsten",translations:["modern"],examples:["Ein modernes Haus.","Das ist modern."]},
  {word:"altmodisch",comparative:"altmodischer",superlative:"am altmodischsten",translations:["old-fashioned"],examples:["Altmodische Kleidung.","Das ist altmodisch."]},
  {word:"freundlich",comparative:"freundlicher",superlative:"am freundlichsten",translations:["friendly","kind"],examples:["Ein freundlicher Mensch.","Sie ist freundlich."]},
  {word:"unfreundlich",comparative:"unfreundlicher",superlative:"am unfreundlichsten",translations:["unfriendly"],examples:["Ein unfreundlicher Kellner.","Er ist unfreundlich."]},
  {word:"nett",comparative:"netter",superlative:"am nettesten",translations:["nice","kind"],examples:["Ein netter Mensch.","Das ist nett von dir."]},
  {word:"gemein",comparative:"gemeiner",superlative:"am gemeinsten",translations:["mean"],examples:["Eine gemeine Person.","Das ist gemein."]},
  {word:"klug",comparative:"klüger",superlative:"am klügsten",translations:["clever","smart"],examples:["Ein kluger Mensch.","Das ist klug."]},
  {word:"dumm",comparative:"dümmer",superlative:"am dümmsten",translations:["stupid","dumb"],examples:["Eine dumme Idee.","Das ist dumm."]},
  {word:"fleißig",comparative:"fleißiger",superlative:"am fleißigsten",translations:["hard-working","diligent"],examples:["Ein fleißiger Schüler.","Sie ist fleißig."]},
  {word:"faul",comparative:"fauler",superlative:"am faulsten",translations:["lazy"],examples:["Ein fauler Mensch.","Er ist faul."]},
  {word:"bequem",comparative:"bequemer",superlative:"am bequemsten",translations:["comfortable"],examples:["Ein bequemer Stuhl.","Das ist bequem."]},
  {word:"unbequem",comparative:"unbequemer",superlative:"am unbequemsten",translations:["uncomfortable"],examples:["Ein unbequemer Stuhl.","Das ist unbequem."]},
  {word:"möglich",comparative:"möglicher",superlative:"am möglichsten",translations:["possible"],examples:["Das ist möglich.","Alles Mögliche."]},
  {word:"unmöglich",comparative:"unmöglicher",superlative:"am unmöglichsten",translations:["impossible"],examples:["Das ist unmöglich.","Eine unmögliche Aufgabe."]},
  {word:"sicher",comparative:"sicherer",superlative:"am sichersten",translations:["safe","sure"],examples:["Ein sicherer Ort.","Ich bin sicher."]},
  {word:"gefährlich",comparative:"gefährlicher",superlative:"am gefährlichsten",translations:["dangerous"],examples:["Eine gefährliche Situation.","Das ist gefährlich."]},
  {word:"normal",comparative:"normaler",superlative:"am normalsten",translations:["normal"],examples:["Eine normale Situation.","Das ist normal."]},
  {word:"seltsam",comparative:"seltsamer",superlative:"am seltsamsten",translations:["strange","odd"],examples:["Ein seltsamer Mensch.","Das ist seltsam."]},
  {word:"bekannt",comparative:"bekannter",superlative:"am bekanntesten",translations:["known","famous"],examples:["Ein bekannter Schauspieler.","Er ist bekannt."]},
  {word:"unbekannt",comparative:"unbekannter",superlative:"am unbekanntesten",translations:["unknown"],examples:["Ein unbekannter Ort.","Das ist unbekannt."]},
  {word:"fertig",comparative:"fertiger",superlative:"am fertigsten",translations:["ready","finished"],examples:["Das Essen ist fertig.","Ich bin fertig."]},
  {word:"offen",comparative:"offener",superlative:"am offensten",translations:["open"],examples:["Die Tür ist offen.","Offene Fragen."]},
  {word:"geschlossen",comparative:"geschlossener",superlative:"am geschlossensten",translations:["closed"],examples:["Die Tür ist geschlossen.","Das Geschäft ist geschlossen."]},
  {word:"weit",comparative:"weiter",superlative:"am weitesten",translations:["far","wide"],examples:["Eine weite Reise.","Das ist weit."]},
  {word:"eng",comparative:"enger",superlative:"am engsten",translations:["tight","narrow"],examples:["Enge Schuhe.","Der Raum ist eng."]},
  {word:"ruhig",comparative:"ruhiger",superlative:"am ruhigsten",translations:["quiet","calm"],examples:["Ein ruhiger Ort.","Bleib ruhig!"]},
  {word:"still",comparative:"stiller",superlative:"am stillsten",translations:["silent","quiet"],examples:["Es ist still.","Stille Nacht."]},
  {word:"aktiv",comparative:"aktiver",superlative:"am aktivsten",translations:["active"],examples:["Ein aktiver Mensch.","Sie ist aktiv."]},
  {word:"passiv",comparative:"passiver",superlative:"am passivsten",translations:["passive"],examples:["Ein passives Verhalten.","Er ist passiv."]},
  {word:"perfekt",comparative:"perfekter",superlative:"am perfektesten",translations:["perfect"],examples:["Ein perfekter Tag.","Das ist perfekt."]},
  {word:"schlimm",comparative:"schlimmer",superlative:"am schlimmsten",translations:["bad","terrible"],examples:["Eine schlimme Situation.","Das ist schlimm."]},
  {word:"best",comparative:"better",superlative:"best",translations:["best"],examples:["Das beste Restaurant.","Du bist der Beste!"]}
];

export default adjectivesA1;
