// adverbs-db-b2.js - B2 Level Adverbs
const adverbsB2 = [
  {word:"dementsprechend",translations:["accordingly"],examples:["Die Nachfrage ist hoch, dementsprechend steigen die Preise.","Er war müde, dementsprechend ging er früh.","Dementsprechend planen wir vorsichtig."]},
  {word:"infolgedessen",translations:["as a result"],examples:["Der Zug fiel aus, infolgedessen kam ich zu spät.","Die Kosten stiegen, infolgedessen sparen wir.","Er hat geübt, infolgedessen wurde er besser."]},
  {word:"gegebenenfalls",translations:["if necessary"],examples:["Gegebenenfalls ändern wir den Termin.","Ruf mich gegebenenfalls an.","Gegebenenfalls müssen wir neu starten."]},
  {word:"unter Umständen",translations:["under certain circumstances"],examples:["Unter Umständen ist das möglich.","Unter Umständen dauert es länger.","Unter Umständen klappt es nicht."]},
  {word:"prinzipiell",translations:["in principle"],examples:["Prinzipiell stimme ich zu.","Das ist prinzipiell möglich.","Prinzipiell gibt es zwei Wege."]},
  {word:"allmählich",translations:["gradually"],examples:["Allmählich wird es besser.","Er versteht es allmählich.","Allmählich steigt die Temperatur."]},
  {word:"zunächst",translations:["at first","initially"],examples:["Zunächst hören wir zu.","Zunächst war ich skeptisch.","Zunächst klären wir die Fakten."]},
  {word:"anschließend",translations:["afterwards"],examples:["Anschließend gehen wir essen.","Anschließend schicke ich die Unterlagen.","Anschließend war alles klar."]},
  {word:"letztendlich",translations:["ultimately"],examples:["Letztendlich zählt die Qualität.","Letztendlich entscheidet das Team.","Letztendlich war es richtig."]},
  {word:"weitgehend",translations:["largely"],examples:["Das ist weitgehend korrekt.","Wir sind weitgehend fertig.","Die Regeln gelten weitgehend."]},
  {word:"zunehmend",translations:["increasingly"],examples:["Die Kosten steigen zunehmend.","Er wird zunehmend nervös.","Zunehmend fehlt uns Zeit."]},
  {word:"keineswegs",translations:["by no means"],examples:["Das ist keineswegs sicher.","Ich bin keineswegs überzeugt.","Das ist keineswegs genug."]},
  {word:"durchaus",translations:["quite","certainly"],examples:["Das ist durchaus möglich.","Ich bin durchaus zufrieden.","Das kann durchaus stimmen."]},
  {word:"eindeutig",translations:["clearly","unambiguously"],examples:["Das ist eindeutig falsch.","Die Ergebnisse sind eindeutig.","Er hat sich eindeutig geäußert."]},
  {word:"teilweise",translations:["partly"],examples:["Das stimmt teilweise.","Teilweise habe ich recht.","Die Lieferung ist teilweise verspätet."]},
  {word:"vollständig",translations:["completely"],examples:["Die Unterlagen sind vollständig.","Ich stimme vollständig zu.","Das Problem ist vollständig gelöst."]},
  {word:"hauptsächlich",translations:["mainly"],examples:["Ich arbeite hauptsächlich von zu Hause.","Hauptsächlich geht es um Zeit.","Wir sprechen hauptsächlich Deutsch."]},
  {word:"insbesondere",translations:["especially","in particular"],examples:["Insbesondere im Winter ist es teuer.","Das betrifft insbesondere junge Leute.","Wir achten insbesondere auf Sicherheit."]},
  {word:"im Gegenteil",translations:["on the contrary"],examples:["Ich bin nicht müde, im Gegenteil, ich bin fit.","Das ist nicht schlechter, im Gegenteil, besser.","Er ist nicht unfreundlich, im Gegenteil, sehr nett."]},
  {word:"hingegen",translations:["on the other hand"],examples:["Ich mag Kaffee, er hingegen Tee.","Das ist günstig, jenes hingegen teuer.","Sie arbeitet schnell, ich hingegen langsam."]},
  {word:"allerdings",translations:["however"],examples:["Das ist gut, allerdings teuer.","Ich komme, allerdings später.","Er wollte helfen, allerdings hatte er keine Zeit."]},
  {word:"dennoch",translations:["nevertheless"],examples:["Es ist schwer, dennoch versuchen wir es.","Er ist müde, dennoch arbeitet er.","Die Kritik ist hart, dennoch fair."]},
  {word:"sogar",translations:["even"],examples:["Er hilft sogar am Wochenende.","Das ist sogar kostenlos.","Sie hat sogar angerufen."]},
  {word:"mindestens",translations:["at least"],examples:["Ich brauche mindestens zwei Tage.","Mindestens zehn Leute kommen.","Das dauert mindestens eine Stunde."]},
  {word:"höchstens",translations:["at most"],examples:["Das kostet höchstens 20 Euro.","Höchstens drei Personen passen rein.","Ich bleibe höchstens eine Stunde."]},
  {word:"ausnahmsweise",translations:["exceptionally","for once"],examples:["Ausnahmsweise komme ich früher.","Ich esse ausnahmsweise Fleisch.","Ausnahmsweise hat er recht."]},
  {word:"regelmäßig",translations:["regularly"],examples:["Ich trainiere regelmäßig.","Regelmäßig kontrollieren wir die Qualität.","Er kommt regelmäßig zu spät."]},
  {word:"selbstverständlich",translations:["of course"],examples:["Selbstverständlich helfe ich dir.","Das ist selbstverständlich.","Selbstverständlich halte ich die Frist ein."]},
  {word:"vermutlich",translations:["presumably"],examples:["Er ist vermutlich schon da.","Vermutlich regnet es später.","Das ist vermutlich die Ursache."]},
  {word:"offenbar",translations:["apparently"],examples:["Offenbar hat er es vergessen.","Offenbar gibt es ein Problem.","Sie ist offenbar nicht zu Hause."]},
  {word:"tendenziell",translations:["tendentially","generally tends to"],examples:["Tendenziell sind die Preise gestiegen.","Er ist tendenziell skeptisch.","Tendenziell hilft Routine."]},
  {word:"grundsätzlich",translations:["fundamentally","generally"],examples:["Grundsätzlich stimme ich zu.","Grundsätzlich ist das erlaubt.","Grundsätzlich gilt diese Regel."]},
  {word:"wörtlich",translations:["literally"],examples:["Nimm das nicht wörtlich.","Er meinte es wörtlich.","Wörtlich verstanden klingt das komisch."]},
  {word:"sinngemäß",translations:["roughly","in essence"],examples:["Sinngemäß stimmt das.","Er hat es sinngemäß erklärt.","Sinngemäß bedeutet das: Wir warten."]},
  {word:"erneut",translations:["again","anew"],examples:["Ich versuche es erneut.","Er ruft erneut an.","Die Lieferung ist erneut verspätet."]},
  {word:"im Voraus",translations:["in advance"],examples:["Danke im Voraus.","Bitte bezahlen Sie im Voraus.","Wir planen alles im Voraus."]},
  {word:"im Nachhinein",translations:["in retrospect"],examples:["Im Nachhinein war es klar.","Im Nachhinein bereue ich es.","Im Nachhinein wirkt die Entscheidung richtig."]},
  {word:"schrittweise",translations:["step by step"],examples:["Wir gehen schrittweise vor.","Schrittweise verbessern wir den Prozess.","Schrittweise wird es einfacher."]},
  {word:"unmittelbar",translations:["immediately","directly"],examples:["Unmittelbar danach rufe ich an.","Die Entscheidung wirkt unmittelbar.","Unmittelbar vor dem Start war ich nervös."]}
];

export default adverbsB2;
