// adverbs-db-a1.js - A1 Level Adverbs
const adverbsA1 = [
  {word:"heute",type:"time",translations:["today"],examples:["Heute ist Montag.","Was machst du heute?"]},
  {word:"gestern",type:"time",translations:["yesterday"],examples:["Gestern war Sonntag.","Ich war gestern krank."]},
  {word:"morgen",type:"time",translations:["tomorrow"],examples:["Morgen ist Dienstag.","Bis morgen!"]},
  {word:"jetzt",type:"time",translations:["now"],examples:["Ich gehe jetzt.","Komm jetzt!"]},
  {word:"gleich",type:"time",translations:["soon","right away"],examples:["Ich komme gleich.","Gleich sind wir da."]},
  {word:"bald",type:"time",translations:["soon"],examples:["Wir kommen bald.","Bis bald!"]},
  {word:"später",type:"time",translations:["later"],examples:["Ich rufe später an.","Bis später!"]},
  {word:"früher",type:"time",translations:["earlier","formerly"],examples:["Ich komme früher.","Früher war alles anders."]},
  {word:"immer",type:"time",translations:["always"],examples:["Ich komme immer pünktlich.","Das ist immer so."]},
  {word:"nie",type:"time",translations:["never"],examples:["Ich komme nie zu spät.","Das mache ich nie."]},
  {word:"oft",type:"time",translations:["often"],examples:["Ich gehe oft spazieren.","Wie oft?"]},
  {word:"manchmal",type:"time",translations:["sometimes"],examples:["Manchmal regnet es.","Ich gehe manchmal ins Kino."]},
  {word:"selten",type:"time",translations:["seldom","rarely"],examples:["Ich komme selten zu spät.","Das passiert selten."]},
  {word:"hier",type:"place",translations:["here"],examples:["Ich bin hier.","Komm hier!"]},
  {word:"dort",type:"place",translations:["there"],examples:["Dort ist ein Auto.","Geh dort hin!"]},
  {word:"da",type:"place",translations:["there"],examples:["Da ist sie!","Warte da!"]},
  {word:"oben",type:"place",translations:["above","upstairs"],examples:["Ich bin oben.","Das Zimmer ist oben."]},
  {word:"unten",type:"place",translations:["below","downstairs"],examples:["Ich bin unten.","Die Küche ist unten."]},
  {word:"links",type:"place",translations:["left","on the left"],examples:["Links ist die Tür.","Geh nach links!"]},
  {word:"rechts",type:"place",translations:["right","on the right"],examples:["Rechts ist das Fenster.","Geh nach rechts!"]},
  {word:"vorne",type:"place",translations:["in front"],examples:["Ich sitze vorne.","Vorne ist der Eingang."]},
  {word:"hinten",type:"place",translations:["in back"],examples:["Hinten ist ein Garten.","Ich sitze hinten."]},
  {word:"überall",type:"place",translations:["everywhere"],examples:["Es ist überall.","Ich suche überall."]},
  {word:"nirgends",type:"place",translations:["nowhere"],examples:["Ich finde es nirgends.","Er ist nirgends."]},
  {word:"draußen",type:"place",translations:["outside"],examples:["Es ist kalt draußen.","Wir sind draußen."]},
  {word:"drinnen",type:"place",translations:["inside"],examples:["Es ist warm drinnen.","Komm rein!"]},
  {word:"gut",type:"manner",translations:["well"],examples:["Ich schlafe gut.","Das schmeckt gut."]},
  {word:"schlecht",type:"manner",translations:["badly"],examples:["Ich schlafe schlecht.","Das schmeckt schlecht."]},
  {word:"schnell",type:"manner",translations:["quickly","fast"],examples:["Komm schnell!","Er läuft schnell."]},
  {word:"langsam",type:"manner",translations:["slowly"],examples:["Geh langsam!","Sprich langsam!"]},
  {word:"laut",type:"manner",translations:["loudly"],examples:["Sprich lauter!","Die Musik ist zu laut."]},
  {word:"leise",type:"manner",translations:["quietly"],examples:["Sprich leise!","Sei leise!"]},
  {word:"gern",type:"manner",translations:["gladly","with pleasure"],examples:["Ich schwimme gern.","Gern geschehen!"]},
  {word:"ungern",type:"manner",translations:["reluctantly"],examples:["Ich gehe ungern zum Zahnarzt."]},
  {word:"sehr",type:"degree",translations:["very"],examples:["Sehr gut!","Das ist sehr schön."]},
  {word:"zu",type:"degree",translations:["too"],examples:["Das ist zu viel.","Zu teuer!"]},
  {word:"ziemlich",type:"degree",translations:["quite","rather"],examples:["Ziemlich gut.","Es ist ziemlich kalt."]},
  {word:"ganz",type:"degree",translations:["quite","completely"],examples:["Ganz gut.","Ich bin ganz sicher."]},
  {word:"besonders",type:"degree",translations:["especially"],examples:["Besonders schön.","Nicht besonders."]},
  {word:"genug",type:"degree",translations:["enough"],examples:["Das ist genug.","Groß genug."]},
  {word:"ein bisschen",type:"degree",translations:["a little"],examples:["Ein bisschen Zucker.","Ich bin ein bisschen müde."]},
  {word:"viel",type:"degree",translations:["much","a lot"],examples:["Sehr viel.","Zu viel!"]},
  {word:"wenig",type:"degree",translations:["little"],examples:["Zu wenig.","Sehr wenig."]},
  {word:"mehr",type:"degree",translations:["more"],examples:["Ich will mehr.","Noch mehr?"]},
  {word:"weniger",type:"degree",translations:["less"],examples:["Ich will weniger.","Weniger ist mehr."]},
  {word:"fast",type:"degree",translations:["almost"],examples:["Fast fertig.","Fast nie."]},
  {word:"etwa",type:"degree",translations:["approximately"],examples:["Etwa 10 Leute.","Etwa so groß."]},
  {word:"nur",type:"degree",translations:["only"],examples:["Nur ich.","Nur heute."]},
  {word:"auch",type:"degree",translations:["also","too"],examples:["Ich auch.","Das auch?"]},
  {word:"zusammen",type:"manner",translations:["together"],examples:["Wir gehen zusammen.","Zusammen sind wir stark."]},
  {word:"allein",type:"manner",translations:["alone"],examples:["Ich bin allein.","Ich gehe allein."]},
  {word:"so",type:"manner",translations:["so","like this"],examples:["So ist es.","Mach es so!"]},
  {word:"anders",type:"manner",translations:["differently"],examples:["Es ist anders.","Mach es anders!"]},
  {word:"genau",type:"manner",translations:["exactly"],examples:["Genau!","Genau so."]},
  {word:"richtig",type:"manner",translations:["correctly","really"],examples:["Richtig gut!","Mach es richtig!"]},
  {word:"falsch",type:"manner",translations:["incorrectly","wrong"],examples:["Das ist falsch.","Du machst es falsch."]},
  {word:"gerne",type:"manner",translations:["gladly"],examples:["Ich helfe gerne.","Gerne!"]},
  {word:"lieber",type:"manner",translations:["rather","preferably"],examples:["Ich gehe lieber ins Kino.","Lieber nicht."]},
  {word:"am liebsten",type:"manner",translations:["most preferably"],examples:["Am liebsten bleibe ich zu Hause."]}
];

export default adverbsA1;
