// nouns-db-c1.js - C1 Level Nouns (advanced nouns)
const nounsC1 = [
  {word:"die Herausforderung",gender:"f",plural:"die Herausforderungen",genitive:"der Herausforderung",translations:["challenge"],examples:["Das Projekt ist eine große Herausforderung.","Ich suche neue Herausforderungen im Job.","Wir meistern die Herausforderung gemeinsam."]},
  {word:"die Voraussetzung",gender:"f",plural:"die Voraussetzungen",genitive:"der Voraussetzung",translations:["prerequisite","requirement"],examples:["Erfahrung ist eine wichtige Voraussetzung.","Gute Deutschkenntnisse sind Voraussetzung für die Stelle.","Welche Voraussetzungen gelten für die Teilnahme?"]},
  {word:"die Maßnahme",gender:"f",plural:"die Maßnahmen",genitive:"der Maßnahme",translations:["measure","action"],examples:["Die Maßnahmen sollen Kosten senken.","Wir ergreifen sofortige Maßnahmen.","Welche Maßnahme ist am effektivsten?"]},
  {word:"die Erkenntnis",gender:"f",plural:"die Erkenntnisse",genitive:"der Erkenntnis",translations:["insight","realization"],examples:["Diese Erkenntnis hat mich überrascht.","Neue Erkenntnisse verändern die Debatte.","Aus der Diskussion entstand eine wichtige Erkenntnis."]},
  {word:"der Fortschritt",gender:"m",plural:"die Fortschritte",genitive:"des Fortschritts",translations:["progress"],examples:["Der Fortschritt ist deutlich sichtbar.","Wir machen schnelle Fortschritte.","Technologischer Fortschritt hat Folgen."]},
  {word:"die Debatte",gender:"f",plural:"die Debatten",genitive:"der Debatte",translations:["debate"],examples:["Die Debatte ist kontrovers.","Wir führen eine Debatte über Bildung.","In der Debatte fehlen oft Fakten."]},
  {word:"die Vielfalt",gender:"f",plural:"die Vielfalten",genitive:"der Vielfalt",translations:["diversity","variety"],examples:["Die kulturelle Vielfalt bereichert die Stadt.","Vielfalt ist in Teams ein Vorteil.","Wir schätzen die Vielfalt der Meinungen."]},
  {word:"der Zusammenhang",gender:"m",plural:"die Zusammenhänge",genitive:"des Zusammenhangs",translations:["connection","context"],examples:["Ich verstehe den Zusammenhang nicht.","Das steht im Zusammenhang mit der Reform.","Es gibt mehrere Zusammenhänge."]},
  {word:"die Entwicklung",gender:"f",plural:"die Entwicklungen",genitive:"der Entwicklung",translations:["development","evolution"],examples:["Die Entwicklung verläuft positiv.","Diese Entwicklung überrascht mich.","Technische Entwicklungen verändern den Alltag."]},
  {word:"die Konsequenz",gender:"f",plural:"die Konsequenzen",genitive:"der Konsequenz",translations:["consequence"],examples:["Das hat unangenehme Konsequenzen.","Wir müssen die Konsequenzen bedenken.","Ohne Konsequenzen lernt man wenig."]},
  {word:"die Vorgehensweise",gender:"f",plural:"die Vorgehensweisen",genitive:"der Vorgehensweise",translations:["approach","procedure"],examples:["Die Vorgehensweise ist sinnvoll.","Wir ändern die Vorgehensweise im Team.","Welche Vorgehensweise empfiehlst du?"]},
  {word:"die Bewertung",gender:"f",plural:"die Bewertungen",genitive:"der Bewertung",translations:["evaluation","rating"],examples:["Die Bewertung fällt positiv aus.","Wir brauchen eine objektive Bewertung.","Seine Bewertung war zu streng."]},
  {word:"die Umsetzung",gender:"f",plural:"die Umsetzungen",genitive:"der Umsetzung",translations:["implementation"],examples:["Die Umsetzung dauert länger als geplant.","Für die Umsetzung fehlen Ressourcen.","Die Umsetzung der Idee gelingt."]},
  {word:"die Voraussetzungslosigkeit",gender:"f",plural:"die Voraussetzungslosigkeiten",genitive:"der Voraussetzungslosigkeit",translations:["lack of prerequisites"],examples:["Die Voraussetzungslosigkeit des Angebots wirkt attraktiv.","Voraussetzungslosigkeit kann auch Risiken bergen.","Wir diskutieren die Voraussetzungslosigkeit im Konzept."]},
  {word:"der Standpunkt",gender:"m",plural:"die Standpunkte",genitive:"des Standpunkts",translations:["point of view","position"],examples:["Ich verstehe deinen Standpunkt.","Sein Standpunkt ist nachvollziehbar.","Wir erklären unseren Standpunkt klar."]},
  {word:"die Haltung",gender:"f",plural:"die Haltungen",genitive:"der Haltung",translations:["attitude","stance"],examples:["Ihre Haltung ist kritisch.","Eine offene Haltung hilft im Dialog.","Seine Haltung hat sich geändert."]},
  {word:"die Belastung",gender:"f",plural:"die Belastungen",genitive:"der Belastung",translations:["strain","burden"],examples:["Die Belastung im Job ist hoch.","Zu viele Belastungen machen krank.","Wir reduzieren die Belastung durch Planung."]},
  {word:"die Voraussetzung",gender:"f",plural:"die Voraussetzungen",genitive:"der Voraussetzung",translations:["condition","requirement"],examples:["Unter dieser Voraussetzung stimme ich zu.","Die Voraussetzung ist nicht erfüllt.","Wir prüfen die Voraussetzungen genau."]},
  {word:"die Perspektive",gender:"f",plural:"die Perspektiven",genitive:"der Perspektive",translations:["perspective"],examples:["Aus meiner Perspektive ist das logisch.","Neue Perspektiven helfen bei Konflikten.","Wir brauchen eine langfristige Perspektive."]},
  {word:"die Relevanz",gender:"f",plural:"die Relevanzen",genitive:"der Relevanz",translations:["relevance"],examples:["Die Relevanz der Daten ist hoch.","Wir prüfen die Relevanz der Quellen.","Ohne Relevanz verliert die Diskussion an Wert."]},
  {word:"die Wirkung",gender:"f",plural:"die Wirkungen",genitive:"der Wirkung",translations:["effect","impact"],examples:["Die Maßnahme zeigt Wirkung.","Die Wirkung ist langfristig.","Welche Wirkung hat das auf die Umwelt?"]},
  {word:"der Widerspruch",gender:"m",plural:"die Widersprüche",genitive:"des Widerspruchs",translations:["contradiction","objection"],examples:["Das ist ein Widerspruch.","Ich lege Widerspruch ein.","In seiner Aussage gibt es Widersprüche."]},
  {word:"die Voraussetzungserfüllung",gender:"f",plural:"die Voraussetzungserfüllungen",genitive:"der Voraussetzungserfüllung",translations:["fulfilment of requirements"],examples:["Die Voraussetzungserfüllung wird geprüft.","Ohne Voraussetzungserfüllung ist keine Teilnahme möglich.","Die Voraussetzungserfüllung dauert mehrere Tage."]},
  {word:"die Entscheidungskompetenz",gender:"f",plural:"die Entscheidungskompetenzen",genitive:"der Entscheidungskompetenz",translations:["decision-making authority"],examples:["Er hat die Entscheidungskompetenz im Team.","Die Entscheidungskompetenz ist klar geregelt.","Wir klären die Entscheidungskompetenzen neu."]},
  {word:"die Verlässlichkeit",gender:"f",plural:"die Verlässlichkeiten",genitive:"der Verlässlichkeit",translations:["reliability"],examples:["Die Verlässlichkeit der Zahlen ist wichtig.","Ich schätze seine Verlässlichkeit.","Wir testen die Verlässlichkeit des Systems."]},
  {word:"die Effizienz",gender:"f",plural:"die Effizienzen",genitive:"der Effizienz",translations:["efficiency"],examples:["Die Effizienz steigt durch Automatisierung.","Wir messen die Effizienz der Prozesse.","Effizienz darf Qualität nicht ersetzen."]},
  {word:"die Nachhaltigkeit",gender:"f",plural:"die Nachhaltigkeiten",genitive:"der Nachhaltigkeit",translations:["sustainability"],examples:["Nachhaltigkeit spielt eine zentrale Rolle.","Wir achten auf die Nachhaltigkeit der Materialien.","Die Nachhaltigkeit der Lösung überzeugt."]},
  {word:"die Priorität",gender:"f",plural:"die Prioritäten",genitive:"der Priorität",translations:["priority"],examples:["Das hat Priorität.","Wir setzen klare Prioritäten.","Sicherheit hat höchste Priorität."]},
  {word:"die Abwägung",gender:"f",plural:"die Abwägungen",genitive:"der Abwägung",translations:["weighing (of pros/cons)","assessment"],examples:["Nach Abwägung aller Faktoren entscheiden wir.","Die Abwägung dauert länger als gedacht.","Eine gute Abwägung braucht Daten."]},

  // ✅ FIXED: comma was missing here in your original code
  {word:"die Schlussfolgerung",gender:"f",plural:"die Schlussfolgerungen",genitive:"der Schlussfolgerung",translations:["conclusion","inference"],examples:["Die Schlussfolgerung ist überzeugend.","Wir ziehen eine Schlussfolgerung aus den Ergebnissen.","Welche Schlussfolgerungen ziehen Sie daraus?"]},

  {word:"die Behauptung",gender:"f",plural:"die Behauptungen",genitive:"der Behauptung",translations:["claim","assertion"],examples:["Eine kühne Behauptung.","Die Behauptung widerlegen."]},
  {word:"die Annahme",gender:"f",plural:"die Annahmen",genitive:"der Annahme",translations:["assumption","acceptance"],examples:["Unter der Annahme, dass...","Diese Annahme ist falsch."]},
  {word:"die Vermutung",gender:"f",plural:"die Vermutungen",genitive:"der Vermutung",translations:["assumption","supposition"],examples:["Eine bloße Vermutung.","Vermutungen anstellen."]},
  {word:"die Hypothese",gender:"f",plural:"die Hypothesen",genitive:"der Hypothese",translations:["hypothesis"],examples:["Eine Hypothese aufstellen.","Die Hypothese testen."]},
  {word:"die Theorie",gender:"f",plural:"die Theorien",genitive:"der Theorie",translations:["theory"],examples:["Die Theorie besagt...","Eine wissenschaftliche Theorie."]},
  {word:"die These",gender:"f",plural:"die Thesen",genitive:"der These",translations:["thesis"],examples:["Die zentrale These.","Eine These aufstellen."]},
  {word:"das Argument",gender:"n",plural:"die Argumente",genitive:"des Arguments",translations:["argument"],examples:["Ein starkes Argument.","Argumente austauschen."]},
  {word:"der Beweis",gender:"m",plural:"die Beweise",genitive:"des Beweises",translations:["proof","evidence"],examples:["Den Beweis erbringen.","Wo sind die Beweise?"]},
  {word:"die Tatsache",gender:"f",plural:"die Tatsachen",genitive:"der Tatsache",translations:["fact"],examples:["Das ist eine Tatsache.","Tatsachen schaffen."]},
  {word:"der Sachverhalt",gender:"m",plural:"die Sachverhalte",genitive:"des Sachverhalts",translations:["facts of the case","situation"],examples:["Den Sachverhalt klären.","Der wahre Sachverhalt."]},
  {word:"der Umstand",gender:"m",plural:"die Umstände",genitive:"des Umstands",translations:["circumstance"],examples:["Unter diesen Umständen.","Die Umstände berücksichtigen."]},
  {word:"der Zusammenhang",gender:"m",plural:"die Zusammenhänge",genitive:"des Zusammenhangs",translations:["context","connection"],examples:["Im Zusammenhang mit...","Den Zusammenhang verstehen."]},
  {word:"die Beziehung",gender:"f",plural:"die Beziehungen",genitive:"der Beziehung",translations:["relationship","relation"],examples:["Eine enge Beziehung.","Beziehungen pflegen."]},
  {word:"die Verbindung",gender:"f",plural:"die Verbindungen",genitive:"der Verbindung",translations:["connection"],examples:["Die Verbindung herstellen.","Eine direkte Verbindung."]},
  {word:"die Verknüpfung",gender:"f",plural:"die Verknüpfungen",genitive:"der Verknüpfung",translations:["link","connection"],examples:["Die Verknüpfung von Ideen.","Eine logische Verknüpfung."]},
  {word:"die Wechselwirkung",gender:"f",plural:"die Wechselwirkungen",genitive:"der Wechselwirkung",translations:["interaction"],examples:["Die Wechselwirkung beachten.","Komplexe Wechselwirkungen."]},
  {word:"die Auswirkung",gender:"f",plural:"die Auswirkungen",genitive:"der Auswirkung",translations:["impact","effect"],examples:["Die Auswirkungen sind groß.","Negative Auswirkungen."]},
  {word:"die Konsequenz",gender:"f",plural:"die Konsequenzen",genitive:"der Konsequenz",translations:["consequence"],examples:["Die Konsequenzen tragen.","Weitreichende Konsequenzen."]},
  {word:"die Implikation",gender:"f",plural:"die Implikationen",genitive:"der Implikation",translations:["implication"],examples:["Die Implikationen verstehen.","Weitreichende Implikationen."]},
  {word:"die Schlussfolgerung",gender:"f",plural:"die Schlussfolgerungen",genitive:"der Schlussfolgerung",translations:["conclusion"],examples:["Zu der Schlussfolgerung kommen.","Eine logische Schlussfolgerung."]},
  {word:"die Interpretation",gender:"f",plural:"die Interpretationen",genitive:"der Interpretation",translations:["interpretation"],examples:["Verschiedene Interpretationen.","Die Interpretation hängt ab von..."]},
  {word:"die Auslegung",gender:"f",plural:"die Auslegungen",genitive:"der Auslegung",translations:["interpretation"],examples:["Die Auslegung des Gesetzes.","Unterschiedliche Auslegungen."]},
  {word:"die Deutung",gender:"f",plural:"die Deutungen",genitive:"der Deutung",translations:["interpretation"],examples:["Eine mögliche Deutung.","Verschiedene Deutungen zulassen."]},
  {word:"die Perspektive",gender:"f",plural:"die Perspektiven",genitive:"der Perspektive",translations:["perspective"],examples:["Aus dieser Perspektive.","Die Perspektive wechseln."]},
  {word:"der Standpunkt",gender:"m",plural:"die Standpunkte",genitive:"des Standpunkts",translations:["point of view"],examples:["Den Standpunkt vertreten.","Verschiedene Standpunkte."]},
  {word:"die Sichtweise",gender:"f",plural:"die Sichtweisen",genitive:"der Sichtweise",translations:["viewpoint","perspective"],examples:["Eine andere Sichtweise.","Die Sichtweise ändern."]},
  {word:"die Auffassung",gender:"f",plural:"die Auffassungen",genitive:"der Auffassung",translations:["view","conception"],examples:["Meiner Auffassung nach.","Unterschiedliche Auffassungen."]},
  {word:"die Ansicht",gender:"f",plural:"die Ansichten",genitive:"der Ansicht",translations:["opinion","view"],examples:["Der Ansicht sein.","Verschiedene Ansichten."]},
  {word:"die Meinung",gender:"f",plural:"die Meinungen",genitive:"der Meinung",translations:["opinion"],examples:["Meiner Meinung nach.","Die öffentliche Meinung."]},
  {word:"die Überzeugung",gender:"f",plural:"die Überzeugungen",genitive:"der Überzeugung",translations:["conviction","belief"],examples:["Die Überzeugung vertreten.","Aus Überzeugung handeln."]},
  {word:"die Einstellung",gender:"f",plural:"die Einstellungen",genitive:"der Einstellung",translations:["attitude"],examples:["Eine positive Einstellung.","Die Einstellung ändern."]},
  {word:"die Haltung",gender:"f",plural:"die Haltungen",genitive:"der Haltung",translations:["attitude","posture"],examples:["Eine kritische Haltung.","Haltung bewahren."]},
  {word:"das Vorurteil",gender:"n",plural:"die Vorurteile",genitive:"des Vorurteils",translations:["prejudice"],examples:["Vorurteile abbauen.","Frei von Vorurteilen."]},
  {word:"die Diskriminierung",gender:"f",plural:"die Diskriminierungen",genitive:"der Diskriminierung",translations:["discrimination"],examples:["Diskriminierung verbieten.","Gegen Diskriminierung kämpfen."]},
  {word:"die Benachteiligung",gender:"f",plural:"die Benachteiligungen",genitive:"der Benachteiligung",translations:["disadvantage","discrimination"],examples:["Eine Benachteiligung erfahren.","Benachteiligungen beseitigen."]},
  {word:"die Gleichberechtigung",gender:"f",plural:"(no plural)",genitive:"der Gleichberechtigung",translations:["equal rights"],examples:["Für Gleichberechtigung kämpfen.","Gleichberechtigung verwirklichen."]},
  {word:"die Gerechtigkeit",gender:"f",plural:"(no plural)",genitive:"der Gerechtigkeit",translations:["justice"],examples:["Gerechtigkeit fordern.","Im Namen der Gerechtigkeit."]},
  {word:"die Ungerechtigkeit",gender:"f",plural:"die Ungerechtigkeiten",genitive:"der Ungerechtigkeit",translations:["injustice"],examples:["Eine Ungerechtigkeit erleiden.","Gegen Ungerechtigkeit kämpfen."]},
  {word:"der Konflikt",gender:"m",plural:"die Konflikte",genitive:"des Konflikts",translations:["conflict"],examples:["Einen Konflikt lösen.","Konflikte vermeiden."]},
  {word:"die Auseinandersetzung",gender:"f",plural:"die Auseinandersetzungen",genitive:"der Auseinandersetzung",translations:["confrontation","dispute"],examples:["Eine heftige Auseinandersetzung.","Sich mit etwas auseinandersetzen."]},
  {word:"der Streit",gender:"m",plural:"die Streite",genitive:"des Streits",translations:["dispute","quarrel"],examples:["Einen Streit haben.","Der Streit eskaliert."]},
  {word:"die Kontroverse",gender:"f",plural:"die Kontroversen",genitive:"der Kontroverse",translations:["controversy"],examples:["Eine Kontroverse auslösen.","Umstrittene Kontroverse."]},
  {word:"die Debatte",gender:"f",plural:"die Debatten",genitive:"der Debatte",translations:["debate"],examples:["Eine Debatte führen.","Die Debatte ist lebhaft."]},
  {word:"die Diskussion",gender:"f",plural:"die Diskussionen",genitive:"der Diskussion",translations:["discussion"],examples:["Eine Diskussion anregen.","An der Diskussion teilnehmen."]},
  {word:"der Diskurs",gender:"m",plural:"die Diskurse",genitive:"des Diskurses",translations:["discourse"],examples:["Der öffentliche Diskurs.","Im wissenschaftlichen Diskurs."]},
  {word:"die Argumentation",gender:"f",plural:"die Argumentationen",genitive:"der Argumentation",translations:["argumentation"],examples:["Die Argumentation ist schlüssig.","Eine überzeugende Argumentation."]},
  {word:"die Begründung",gender:"f",plural:"die Begründungen",genitive:"der Begründung",translations:["justification","reasoning"],examples:["Die Begründung liefern.","Ohne Begründung."]},
  {word:"die Rechtfertigung",gender:"f",plural:"die Rechtfertigungen",genitive:"der Rechtfertigung",translations:["justification"],examples:["Eine Rechtfertigung verlangen.","Ohne Rechtfertigung."]},
  {word:"die Erklärung",gender:"f",plural:"die Erklärungen",genitive:"der Erklärung",translations:["explanation","declaration"],examples:["Eine Erklärung abgeben.","Die Erklärung ist plausibel."]},
  {word:"die Darstellung",gender:"f",plural:"die Darstellungen",genitive:"der Darstellung",translations:["presentation","portrayal"],examples:["Die Darstellung der Fakten.","Eine anschauliche Darstellung."]}
];

export default nounsC1;
