// nouns-db-a1.js - A1 Level Nouns (100 essential nouns)
const nounsA1 = [
  {word:"der Mann",gender:"m",plural:"die Männer",genitive:"des Mannes",translations:["man"],examples:["Der Mann arbeitet.","Ich sehe den Mann."]},
  {word:"die Frau",gender:"f",plural:"die Frauen",genitive:"der Frau",translations:["woman","wife"],examples:["Die Frau ist nett.","Das ist meine Frau."]},
  {word:"das Kind",gender:"n",plural:"die Kinder",genitive:"des Kindes",translations:["child"],examples:["Das Kind spielt.","Wir haben zwei Kinder."]},
  {word:"der Mensch",gender:"m",plural:"die Menschen",genitive:"des Menschen",translations:["human","person"],examples:["Der Mensch ist gut.","Viele Menschen sind hier."]},
  {word:"die Leute",gender:"f",plural:"die Leute",genitive:"der Leute",translations:["people"],examples:["Die Leute warten.","Nette Leute!"]},
  {word:"der Tag",gender:"m",plural:"die Tage",genitive:"des Tages",translations:["day"],examples:["Der Tag ist schön.","Guten Tag!"]},
  {word:"die Woche",gender:"f",plural:"die Wochen",genitive:"der Woche",translations:["week"],examples:["Die Woche hat sieben Tage.","Nächste Woche komme ich."]},
  {word:"das Jahr",gender:"n",plural:"die Jahre",genitive:"des Jahres",translations:["year"],examples:["Das Jahr hat zwölf Monate.","Ich bin 25 Jahre alt."]},
  {word:"der Monat",gender:"m",plural:"die Monate",genitive:"des Monats",translations:["month"],examples:["Der Monat Januar ist kalt.","In drei Monaten."]},
  {word:"die Zeit",gender:"f",plural:"die Zeiten",genitive:"der Zeit",translations:["time"],examples:["Die Zeit vergeht schnell.","Ich habe keine Zeit."]},
  {word:"die Stunde",gender:"f",plural:"die Stunden",genitive:"der Stunde",translations:["hour"],examples:["Eine Stunde hat 60 Minuten.","In zwei Stunden."]},
  {word:"die Minute",gender:"f",plural:"die Minuten",genitive:"der Minute",translations:["minute"],examples:["Ich brauche fünf Minuten.","Warte eine Minute!"]},
  {word:"das Haus",gender:"n",plural:"die Häuser",genitive:"des Hauses",translations:["house"],examples:["Das Haus ist groß.","Ich gehe nach Hause."]},
  {word:"die Wohnung",gender:"f",plural:"die Wohnungen",genitive:"der Wohnung",translations:["apartment"],examples:["Die Wohnung ist schön.","Ich suche eine Wohnung."]},
  {word:"das Zimmer",gender:"n",plural:"die Zimmer",genitive:"des Zimmers",translations:["room"],examples:["Das Zimmer ist klein.","Mein Zimmer ist oben."]},
  {word:"die Tür",gender:"f",plural:"die Türen",genitive:"der Tür",translations:["door"],examples:["Die Tür ist offen.","Mach die Tür zu!"]},
  {word:"das Fenster",gender:"n",plural:"die Fenster",genitive:"des Fensters",translations:["window"],examples:["Das Fenster ist groß.","Öffne das Fenster!"]},
  {word:"der Tisch",gender:"m",plural:"die Tische",genitive:"des Tisches",translations:["table"],examples:["Der Tisch ist rund.","Auf dem Tisch liegt ein Buch."]},
  {word:"der Stuhl",gender:"m",plural:"die Stühle",genitive:"des Stuhles",translations:["chair"],examples:["Der Stuhl ist bequem.","Nimm einen Stuhl!"]},
  {word:"das Bett",gender:"n",plural:"die Betten",genitive:"des Bettes",translations:["bed"],examples:["Das Bett ist weich.","Ich gehe ins Bett."]},
  {word:"der Schrank",gender:"m",plural:"die Schränke",genitive:"des Schrankes",translations:["cabinet","wardrobe"],examples:["Der Schrank ist voll.","Ich stelle es in den Schrank."]},
  {word:"die Küche",gender:"f",plural:"die Küchen",genitive:"der Küche",translations:["kitchen"],examples:["Die Küche ist modern.","Ich koche in der Küche."]},
  {word:"das Bad",gender:"n",plural:"die Bäder",genitive:"des Bades",translations:["bathroom"],examples:["Das Bad ist sauber.","Ich gehe ins Bad."]},
  {word:"der Garten",gender:"m",plural:"die Gärten",genitive:"des Gartens",translations:["garden"],examples:["Der Garten ist schön.","Im Garten spielen Kinder."]},
  {word:"die Straße",gender:"f",plural:"die Straßen",genitive:"der Straße",translations:["street"],examples:["Die Straße ist breit.","Auf der Straße fahren Autos."]},
  {word:"der Weg",gender:"m",plural:"die Wege",genitive:"des Weges",translations:["way","path"],examples:["Der Weg ist lang.","Welchen Weg gehst du?"]},
  {word:"die Stadt",gender:"f",plural:"die Städte",genitive:"der Stadt",translations:["city"],examples:["Die Stadt ist groß.","Ich wohne in der Stadt."]},
  {word:"das Land",gender:"n",plural:"die Länder",genitive:"des Landes",translations:["country","countryside"],examples:["Das Land ist schön.","Ich komme aus diesem Land."]},
  {word:"das Auto",gender:"n",plural:"die Autos",genitive:"des Autos",translations:["car"],examples:["Das Auto ist neu.","Ich fahre mit dem Auto."]},
  {word:"der Bus",gender:"m",plural:"die Busse",genitive:"des Busses",translations:["bus"],examples:["Der Bus kommt.","Ich fahre mit dem Bus."]},
  {word:"die Bahn",gender:"f",plural:"die Bahnen",genitive:"der Bahn",translations:["train","railway"],examples:["Die Bahn fährt ab.","Ich fahre mit der Bahn."]},
  {word:"das Fahrrad",gender:"n",plural:"die Fahrräder",genitive:"des Fahrrads",translations:["bicycle"],examples:["Das Fahrrad ist kaputt.","Ich fahre Fahrrad."]},
  {word:"das Flugzeug",gender:"n",plural:"die Flugzeuge",genitive:"des Flugzeugs",translations:["airplane"],examples:["Das Flugzeug fliegt.","Wir fliegen mit dem Flugzeug."]},
  {word:"der Bahnhof",gender:"m",plural:"die Bahnhöfe",genitive:"des Bahnhofs",translations:["train station"],examples:["Der Bahnhof ist groß.","Ich bin am Bahnhof."]},
  {word:"der Flughafen",gender:"m",plural:"die Flughäfen",genitive:"des Flughafens",translations:["airport"],examples:["Der Flughafen ist weit.","Wir sind am Flughafen."]},
  {word:"die Schule",gender:"f",plural:"die Schulen",genitive:"der Schule",translations:["school"],examples:["Die Schule beginnt um 8 Uhr.","Ich gehe zur Schule."]},
  {word:"die Universität",gender:"f",plural:"die Universitäten",genitive:"der Universität",translations:["university"],examples:["Die Universität ist groß.","Ich studiere an der Universität."]},
  {word:"das Büro",gender:"n",plural:"die Büros",genitive:"des Büros",translations:["office"],examples:["Das Büro ist modern.","Ich arbeite im Büro."]},
  {word:"die Arbeit",gender:"f",plural:"die Arbeiten",genitive:"der Arbeit",translations:["work","job"],examples:["Die Arbeit ist schwer.","Ich gehe zur Arbeit."]},
  {word:"der Job",gender:"m",plural:"die Jobs",genitive:"des Jobs",translations:["job"],examples:["Der Job ist gut.","Ich suche einen Job."]},
  {word:"das Geld",gender:"n",plural:"die Gelder",genitive:"des Geldes",translations:["money"],examples:["Das Geld ist wichtig.","Ich habe kein Geld."]},
  {word:"der Euro",gender:"m",plural:"die Euro/Euros",genitive:"des Euros",translations:["euro"],examples:["Das kostet 5 Euro.","Ich brauche mehr Euros."]},
  {word:"der Preis",gender:"m",plural:"die Preise",genitive:"des Preises",translations:["price"],examples:["Der Preis ist hoch.","Was ist der Preis?"]},
  {word:"das Geschäft",gender:"n",plural:"die Geschäfte",genitive:"des Geschäfts",translations:["shop","business"],examples:["Das Geschäft ist geöffnet.","Ich gehe ins Geschäft."]},
  {word:"der Laden",gender:"m",plural:"die Läden",genitive:"des Ladens",translations:["shop","store"],examples:["Der Laden hat zu.","Im Laden kaufe ich ein."]},
  {word:"der Supermarkt",gender:"m",plural:"die Supermärkte",genitive:"des Supermarkts",translations:["supermarket"],examples:["Der Supermarkt ist groß.","Ich gehe zum Supermarkt."]},
  {word:"das Restaurant",gender:"n",plural:"die Restaurants",genitive:"des Restaurants",translations:["restaurant"],examples:["Das Restaurant ist voll.","Wir essen im Restaurant."]},
  {word:"das Café",gender:"n",plural:"die Cafés",genitive:"des Cafés",translations:["café"],examples:["Das Café ist gemütlich.","Wir treffen uns im Café."]},
  {word:"das Hotel",gender:"n",plural:"die Hotels",genitive:"des Hotels",translations:["hotel"],examples:["Das Hotel ist teuer.","Wir übernachten im Hotel."]},
  {word:"der Arzt",gender:"m",plural:"die Ärzte",genitive:"des Arztes",translations:["doctor (male)"],examples:["Der Arzt hilft mir.","Ich gehe zum Arzt."]},
  {word:"die Ärztin",gender:"f",plural:"die Ärztinnen",genitive:"der Ärztin",translations:["doctor (female)"],examples:["Die Ärztin ist nett.","Meine Ärztin heißt Müller."]},
  {word:"der Lehrer",gender:"m",plural:"die Lehrer",genitive:"des Lehrers",translations:["teacher (male)"],examples:["Der Lehrer erklärt gut.","Mein Lehrer ist streng."]},
  {word:"die Lehrerin",gender:"f",plural:"die Lehrerinnen",genitive:"der Lehrerin",translations:["teacher (female)"],examples:["Die Lehrerin ist jung.","Unsere Lehrerin ist sehr gut."]},
  {word:"der Freund",gender:"m",plural:"die Freunde",genitive:"des Freundes",translations:["friend (male)","boyfriend"],examples:["Mein Freund kommt.","Das ist ein guter Freund."]},
  {word:"die Freundin",gender:"f",plural:"die Freundinnen",genitive:"der Freundin",translations:["friend (female)","girlfriend"],examples:["Meine Freundin heißt Anna.","Das ist meine beste Freundin."]},
  {word:"die Familie",gender:"f",plural:"die Familien",genitive:"der Familie",translations:["family"],examples:["Die Familie ist groß.","Meine Familie wohnt in Berlin."]},
  {word:"der Vater",gender:"m",plural:"die Väter",genitive:"des Vaters",translations:["father"],examples:["Mein Vater arbeitet.","Der Vater ist stolz."]},
  {word:"die Mutter",gender:"f",plural:"die Mütter",genitive:"der Mutter",translations:["mother"],examples:["Meine Mutter kocht.","Die Mutter ist lieb."]},
  {word:"das Elternteil",gender:"n",plural:"die Eltern",genitive:"des Elternteils",translations:["parent"],examples:["Die Eltern kommen.","Ich liebe meine Eltern."]},
  {word:"der Sohn",gender:"m",plural:"die Söhne",genitive:"des Sohnes",translations:["son"],examples:["Mein Sohn ist 10.","Der Sohn spielt."]},
  {word:"die Tochter",gender:"f",plural:"die Töchter",genitive:"der Tochter",translations:["daughter"],examples:["Meine Tochter singt.","Die Tochter ist klug."]},
  {word:"der Bruder",gender:"m",plural:"die Brüder",genitive:"des Bruders",translations:["brother"],examples:["Mein Bruder ist älter.","Der Bruder hilft mir."]},
  {word:"die Schwester",gender:"f",plural:"die Schwestern",genitive:"der Schwester",translations:["sister"],examples:["Meine Schwester ist nett.","Die Schwester wohnt hier."]},
  {word:"der Hund",gender:"m",plural:"die Hunde",genitive:"des Hundes",translations:["dog"],examples:["Der Hund bellt.","Ich habe einen Hund."]},
  {word:"die Katze",gender:"f",plural:"die Katzen",genitive:"der Katze",translations:["cat"],examples:["Die Katze schläft.","Meine Katze ist süß."]},
  {word:"das Tier",gender:"n",plural:"die Tiere",genitive:"des Tieres",translations:["animal"],examples:["Das Tier ist groß.","Ich mag Tiere."]},
  {word:"der Vogel",gender:"m",plural:"die Vögel",genitive:"des Vogels",translations:["bird"],examples:["Der Vogel singt.","Vögel fliegen."]},
  {word:"der Fisch",gender:"m",plural:"die Fische",genitive:"des Fisches",translations:["fish"],examples:["Der Fisch schwimmt.","Ich esse gern Fisch."]},
  {word:"das Essen",gender:"n",plural:"die Essen",genitive:"des Essens",translations:["food","meal"],examples:["Das Essen ist lecker.","Ich brauche Essen."]},
  {word:"das Frühstück",gender:"n",plural:"die Frühstücke",genitive:"des Frühstücks",translations:["breakfast"],examples:["Das Frühstück ist fertig.","Ich esse Frühstück."]},
  {word:"das Mittagessen",gender:"n",plural:"die Mittagessen",genitive:"des Mittagessens",translations:["lunch"],examples:["Das Mittagessen schmeckt gut.","Wir essen Mittagessen."]},
  {word:"das Abendessen",gender:"n",plural:"die Abendessen",genitive:"des Abendessens",translations:["dinner"],examples:["Das Abendessen ist warm.","Ich koche Abendessen."]},
  {word:"das Brot",gender:"n",plural:"die Brote",genitive:"des Brotes",translations:["bread"],examples:["Das Brot ist frisch.","Ich esse Brot."]},
  {word:"die Butter",gender:"f",plural:"die Buttern",genitive:"der Butter",translations:["butter"],examples:["Die Butter ist weich.","Brot mit Butter."]},
  {word:"der Käse",gender:"m",plural:"die Käse",genitive:"des Käses",translations:["cheese"],examples:["Der Käse ist alt.","Ich mag Käse."]},
  {word:"die Milch",gender:"f",plural:"die Milchsorten",genitive:"der Milch",translations:["milk"],examples:["Die Milch ist kalt.","Ich trinke Milch."]},
  {word:"das Wasser",gender:"n",plural:"die Wasser/Wässer",genitive:"des Wassers",translations:["water"],examples:["Das Wasser ist klar.","Ich brauche Wasser."]},
  {word:"der Kaffee",gender:"m",plural:"die Kaffees",genitive:"des Kaffees",translations:["coffee"],examples:["Der Kaffee ist heiß.","Ich trinke Kaffee."]},
  {word:"der Tee",gender:"m",plural:"die Tees",genitive:"des Tees",translations:["tea"],examples:["Der Tee ist warm.","Möchtest du Tee?"]},
  {word:"der Saft",gender:"m",plural:"die Säfte",genitive:"des Saftes",translations:["juice"],examples:["Der Saft ist süß.","Orangensaft bitte!"]},
  {word:"das Bier",gender:"n",plural:"die Biere",genitive:"des Bieres",translations:["beer"],examples:["Das Bier ist kalt.","Ein Bier, bitte!"]},
  {word:"der Wein",gender:"m",plural:"die Weine",genitive:"des Weines",translations:["wine"],examples:["Der Wein ist rot.","Ich trinke gern Wein."]},
  {word:"der Apfel",gender:"m",plural:"die Äpfel",genitive:"des Apfels",translations:["apple"],examples:["Der Apfel ist rot.","Ich esse einen Apfel."]},
  {word:"die Banane",gender:"f",plural:"die Bananen",genitive:"der Banane",translations:["banana"],examples:["Die Banane ist gelb.","Bananen sind gesund."]},
  {word:"die Orange",gender:"f",plural:"die Orangen",genitive:"der Orange",translations:["orange"],examples:["Die Orange ist saftig.","Ich mag Orangen."]},
  {word:"das Buch",gender:"n",plural:"die Bücher",genitive:"des Buches",translations:["book"],examples:["Das Buch ist spannend.","Ich lese ein Buch."]},
  {word:"die Zeitung",gender:"f",plural:"die Zeitungen",genitive:"der Zeitung",translations:["newspaper"],examples:["Die Zeitung ist aktuell.","Ich lese die Zeitung."]},
  {word:"der Stift",gender:"m",plural:"die Stifte",genitive:"des Stiftes",translations:["pen","pencil"],examples:["Der Stift schreibt gut.","Hast du einen Stift?"]},
  {word:"das Papier",gender:"n",plural:"die Papiere",genitive:"des Papiers",translations:["paper"],examples:["Das Papier ist weiß.","Ich brauche Papier."]},
  {word:"der Computer",gender:"m",plural:"die Computer",genitive:"des Computers",translations:["computer"],examples:["Der Computer ist neu.","Ich arbeite am Computer."]},
  {word:"das Telefon",gender:"n",plural:"die Telefone",genitive:"des Telefons",translations:["telephone"],examples:["Das Telefon klingelt.","Ich telefoniere."]},
  {word:"das Handy",gender:"n",plural:"die Handys",genitive:"des Handys",translations:["mobile phone"],examples:["Das Handy ist modern.","Mein Handy ist kaputt."]},
  {word:"die Uhr",gender:"f",plural:"die Uhren",genitive:"der Uhr",translations:["clock","watch","o'clock"],examples:["Die Uhr zeigt 3.","Es ist 5 Uhr."]},
  {word:"die Frage",gender:"f",plural:"die Fragen",genitive:"der Frage",translations:["question"],examples:["Die Frage ist schwer.","Ich habe eine Frage."]},
  {word:"die Antwort",gender:"f",plural:"die Antworten",genitive:"der Antwort",translations:["answer"],examples:["Die Antwort ist richtig.","Was ist die Antwort?"]},
  {word:"das Wort",gender:"n",plural:"die Wörter/Worte",genitive:"des Wortes",translations:["word"],examples:["Das Wort ist neu.","Ich kenne dieses Wort nicht."]},
  {word:"die Sprache",gender:"f",plural:"die Sprachen",genitive:"der Sprache",translations:["language"],examples:["Die Sprache ist schön.","Welche Sprache sprichst du?"]},
  {word:"das Problem",gender:"n",plural:"die Probleme",genitive:"des Problems",translations:["problem"],examples:["Das Problem ist groß.","Wir haben ein Problem."]},
  {word:"die Lösung",gender:"f",plural:"die Lösungen",genitive:"der Lösung",translations:["solution"],examples:["Die Lösung ist einfach.","Ich habe die Lösung."]}
];

export default nounsA1;
