// verbs-db-b2.js - B2 Level - 225 verbs
const verbsB2 = [
  {base:"aufwachen",past:"wachte auf",participle:"aufgewacht",translations:["to wake up"],derived:["wache auf","wachst auf","wacht auf"],varieties:[]},
  {base:"einladen",past:"lud ein",participle:"eingeladen",translations:["to invite"],derived:["lade ein","lädst ein","lädt ein"],varieties:[{variant:"einladen + zu",prepositions:["zu"],explanation:"To invite to.",examples:["Ich lade dich zur Party ein."]}]},
  {base:"nachdenken",past:"dachte nach",participle:"nachgedacht",translations:["to think about","to reflect"],derived:["denke nach","denkst nach","denkt nach"],varieties:[{variant:"nachdenken + über",prepositions:["über"],explanation:"To reflect on.",examples:["Ich denke über meine Zukunft nach."]}]},
  {base:"zurückkommen",past:"kam zurück",participle:"zurückgekommen",translations:["to come back","to return"],derived:["komme zurück","kommst zurück","kommt zurück"],varieties:[]},
  {base:"sich beschäftigen",past:"beschäftigte sich",participle:"beschäftigt",translations:["to occupy oneself","to deal with"],reflexive:true,derived:["beschäftige mich","beschäftigst dich","beschäftigt sich"],varieties:[{variant:"sich beschäftigen + mit",prepositions:["mit"],explanation:"To deal with.",examples:["Ich beschäftige mich mit einem Projekt."]}]},
  {base:"überlegen",past:"überlegte",participle:"überlegt",translations:["to consider","to think about"],derived:["überlege","überlegst","überlegt"],varieties:[]},
  {base:"sich entschuldigen",past:"entschuldigte sich",participle:"entschuldigt",translations:["to apologize"],reflexive:true,derived:["entschuldige mich","entschuldigst dich","entschuldigt sich"],varieties:[{variant:"sich entschuldigen + bei",prepositions:["bei"],explanation:"To apologize to.",examples:["Ich entschuldige mich bei dir."]}]},
  {base:"sich bewerben",past:"bewarb sich",participle:"beworben",translations:["to apply"],reflexive:true,derived:["bewerbe mich","bewirbst dich","bewirbt sich"],varieties:[{variant:"sich bewerben + um",prepositions:["um"],explanation:"To apply for.",examples:["Ich bewerbe mich um die Stelle."]}]},
  {base:"vorstellen",past:"stellte vor",participle:"vorgestellt",translations:["to introduce","to imagine"],derived:["stelle vor","stellst vor","stellt vor"],varieties:[{variant:"sich vorstellen",explanation:"Reflexive: to introduce oneself or imagine.",examples:["Darf ich mich vorstellen?","Ich stelle mir vor, wie es wäre."]}]},
  {base:"umgehen",past:"ging um",participle:"umgegangen",translations:["to deal with","to handle"],derived:["gehe um","gehst um","geht um"],varieties:[{variant:"umgehen + mit",prepositions:["mit"],explanation:"To handle something.",examples:["Wie gehst du mit Stress um?"]}]},
  {base:"sich kümmern",past:"kümmerte sich",participle:"gekümmert",translations:["to take care of","to look after"],reflexive:true,derived:["kümmere mich","kümmerst dich","kümmert sich"],varieties:[{variant:"sich kümmern + um",prepositions:["um"],explanation:"To take care of.",examples:["Ich kümmere mich um die Kinder."]}]},
  {base:"beitragen",past:"trug bei",participle:"beigetragen",translations:["to contribute"],derived:["trage bei","trägst bei","trägt bei"],varieties:[{variant:"beitragen + zu",prepositions:["zu"],explanation:"To contribute to.",examples:["Das trägt zum Erfolg bei."]}]},
  {base:"teilhaben",past:"hatte teil",participle:"teilgehabt",translations:["to participate","to share in"],derived:["habe teil","hast teil","hat teil"],varieties:[{variant:"teilhaben + an",prepositions:["an"],explanation:"To share in.",examples:["Er hat am Gewinn teil."]}]},
  {base:"mitwirken",past:"wirkte mit",participle:"mitgewirkt",translations:["to participate","to cooperate"],derived:["wirke mit","wirkst mit","wirkt mit"],varieties:[{variant:"mitwirken + an",prepositions:["an"],explanation:"To participate in.",examples:["Sie wirkt am Projekt mit."]}]},
  {base:"einbeziehen",past:"bezog ein",participle:"einbezogen",translations:["to include","to involve"],derived:["beziehe ein","beziehst ein","bezieht ein"],varieties:[]},
  {base:"berücksichtigen",past:"berücksichtigte",participle:"berücksichtigt",translations:["to consider","to take into account"],derived:["berücksichtige","berücksichtigst","berücksichtigt"],varieties:[]},
  {base:"beachten",past:"beachtete",participle:"beachtet",translations:["to observe","to pay attention to"],derived:["beachte","beachtest","beachtet"],varieties:[]},
  {base:"ignorieren",past:"ignorierte",participle:"ignoriert",translations:["to ignore"],derived:["ignoriere","ignorierst","ignoriert"],varieties:[]},
  {base:"missachten",past:"missachtete",participle:"missachtet",translations:["to disregard","to ignore"],derived:["missachte","missachtest","missachtet"],varieties:[]},
  {base:"vernachlässigen",past:"vernachlässigte",participle:"vernachlässigt",translations:["to neglect"],derived:["vernachlässige","vernachlässigst","vernachlässigt"],varieties:[]},
  {base:"versäumen",past:"versäumte",participle:"versäumt",translations:["to miss","to neglect"],derived:["versäume","versäumst","versäumt"],varieties:[]},
  {base:"verpassen",past:"verpasste",participle:"verpasst",translations:["to miss"],derived:["verpasse","verpasst","verpasst"],varieties:[]},
  {base:"nachholen",past:"holte nach",participle:"nachgeholt",translations:["to make up for","to catch up on"],derived:["hole nach","holst nach","holt nach"],varieties:[]},
  {base:"wiederholen",past:"wiederholte",participle:"wiederholt",translations:["to repeat"],derived:["wiederhole","wiederholst","wiederholt"],varieties:[]},
  {base:"zurückholen",past:"holte zurück",participle:"zurückgeholt",translations:["to bring back","to retrieve"],derived:["hole zurück","holst zurück","holt zurück"],varieties:[]},
  {base:"abholen",past:"holte ab",participle:"abgeholt",translations:["to pick up","to collect"],derived:["hole ab","holst ab","holt ab"],varieties:[]},
  {base:"einholen",past:"holte ein",participle:"eingeholt",translations:["to catch up","to obtain"],derived:["hole ein","holst ein","holt ein"],varieties:[]},
  {base:"aufholen",past:"holte auf",participle:"aufgeholt",translations:["to catch up","to make up"],derived:["hole auf","holst auf","holt auf"],varieties:[]},
  {base:"überholen",past:"überholte",participle:"überholt",translations:["to overtake","to surpass"],derived:["überhole","überholst","überholt"],varieties:[]},
  {base:"einholen",past:"holte ein",participle:"eingeholt",translations:["to catch up with"],derived:["hole ein","holst ein","holt ein"],varieties:[]},
  {base:"vorankommen",past:"kam voran",participle:"vorangekommen",translations:["to make progress","to get ahead"],derived:["komme voran","kommst voran","kommt voran"],varieties:[]},
  {base:"fortschreiten",past:"schritt fort",participle:"fortgeschritten",translations:["to progress","to advance"],derived:["schreite fort","schreitest fort","schreitet fort"],varieties:[]},
  {base:"gedeihen",past:"gedieh",participle:"gediehen",translations:["to thrive","to prosper"],derived:["gedeihe","gedeihst","gedeiht"],varieties:[]},
  {base:"florieren",past:"florierte",participle:"floriert",translations:["to flourish","to thrive"],derived:["floriere","florierst","floriert"],varieties:[]},
  {base:"blühen",past:"blühte",participle:"geblüht",translations:["to bloom","to flourish"],derived:["blühe","blühst","blüht"],varieties:[]},
  {base:"erblühen",past:"erblühte",participle:"erblüht",translations:["to blossom"],derived:["erblühe","erblühst","erblüht"],varieties:[]},
  {base:"aufblühen",past:"blühte auf",participle:"aufgeblüht",translations:["to blossom","to flourish"],derived:["blühe auf","blühst auf","blüht auf"],varieties:[]},
  {base:"verblühen",past:"verblühte",participle:"verblüht",translations:["to wither","to fade"],derived:["verblühe","verblühst","verblüht"],varieties:[]},
  {base:"welken",past:"welkte",participle:"gewelkt",translations:["to wilt","to wither"],derived:["welke","welkst","welkt"],varieties:[]},
  {base:"verwelken",past:"verwelkte",participle:"verwelkt",translations:["to wither"],derived:["verwelke","verwelkst","verwelkt"],varieties:[]},
  {base:"verdorren",past:"verdorrte",participle:"verdorrt",translations:["to wither","to dry up"],derived:["verdorre","verdorrst","verdorrt"],varieties:[]},
  {base:"austrocknen",past:"trocknete aus",participle:"ausgetrocknet",translations:["to dry out"],derived:["trockne aus","trocknest aus","trocknet aus"],varieties:[]},
  {base:"vertrocknen",past:"vertrocknete",participle:"vertrocknet",translations:["to dry up"],derived:["vertrockne","vertrocknest","vertrocknet"],varieties:[]},
  {base:"verdursten",past:"verdurstete",participle:"verdurstet",translations:["to die of thirst"],derived:["verdurste","verdurstest","verdurstet"],varieties:[]},
  {base:"verhungern",past:"verhungerte",participle:"verhungert",translations:["to starve"],derived:["verhungere","verhungerst","verhungert"],varieties:[]},
  {base:"erfrieren",past:"erfror",participle:"erfroren",translations:["to freeze to death"],derived:["erfriere","erfrierst","erfriert"],varieties:[]},
  {base:"ersticken",past:"erstickte",participle:"erstickt",translations:["to suffocate","to choke"],derived:["ersticke","erstickst","erstickt"],varieties:[]},
  {base:"ertrinken",past:"ertrank",participle:"ertrunken",translations:["to drown"],derived:["ertrinke","ertrinkst","ertrinkt"],varieties:[]},
  {base:"versinken",past:"versank",participle:"versunken",translations:["to sink"],derived:["versinke","versinkst","versinkt"],varieties:[]},
  {base:"untergehen",past:"ging unter",participle:"untergegangen",translations:["to sink","to set (sun)"],derived:["gehe unter","gehst unter","geht unter"],varieties:[]},
  {base:"aufgehen",past:"ging auf",participle:"aufgegangen",translations:["to rise (sun)","to open"],derived:["gehe auf","gehst auf","geht auf"],varieties:[]},
  {base:"eingehen",past:"ging ein",participle:"eingegangen",translations:["to agree to","to die (plant)"],derived:["gehe ein","gehst ein","geht ein"],varieties:[{variant:"eingehen + auf",prepositions:["auf"],explanation:"To agree to or address something.",examples:["Ich gehe auf deinen Vorschlag ein."]}]},
  {base:"ausgehen",past:"ging aus",participle:"ausgegangen",translations:["to go out","to run out"],derived:["gehe aus","gehst aus","geht aus"],varieties:[{variant:"ausgehen + von",prepositions:["von"],explanation:"To assume or start from.",examples:["Ich gehe davon aus, dass du kommst."]}]},
  {base:"vorübergehen",past:"ging vorüber",participle:"vorübergegangen",translations:["to pass by","to pass (time)"],derived:["gehe vorüber","gehst vorüber","geht vorüber"],varieties:[]},
  {base:"vergehen",past:"verging",participle:"vergangen",translations:["to pass (time)","to fade"],derived:["vergehe","vergehst","vergeht"],varieties:[]},
  {base:"verlaufen",past:"verlief",participle:"verlaufen",translations:["to proceed","to get lost"],derived:["verlaufe","verläufst","verläuft"],varieties:[{variant:"sich verlaufen",explanation:"Reflexive: to get lost.",examples:["Ich habe mich verlaufen."]}]},
  {base:"verirren",past:"verirrte",participle:"verirrt",translations:["to get lost","to stray"],derived:["verirre","verirrst","verirrt"],varieties:[{variant:"sich verirren",explanation:"Reflexive: to lose one's way.",examples:["Wir haben uns verirrt."]}]},
  {base:"orientieren",past:"orientierte",participle:"orientiert",translations:["to orient"],derived:["orientiere","orientierst","orientiert"],varieties:[{variant:"sich orientieren",explanation:"Reflexive: to get one's bearings.",examples:["Ich orientiere mich an der Karte."]}]},
  {base:"zurechtfinden",past:"fand zurecht",participle:"zurechtgefunden",translations:["to find one's way"],derived:["finde zurecht","findest zurecht","findet zurecht"],varieties:[{variant:"sich zurechtfinden",explanation:"Reflexive: to find one's way around.",examples:["Ich finde mich hier zurecht."]}]},
  {base:"auskennen",past:"kannte aus",participle:"ausgekannt",translations:["to know one's way around"],derived:["kenne aus","kennst aus","kennt aus"],varieties:[{variant:"sich auskennen + in",prepositions:["in"],explanation:"To know one's way around.",examples:["Ich kenne mich in Berlin aus."]}]},
  {base:"bewandert",past:"bewanderte",participle:"bewandert",translations:["to be versed in"],derived:["bewandert","bewandert","bewandert"],varieties:[]},
  {base:"vertraut",past:"vertraute",participle:"vertraut",translations:["to be familiar with"],derived:["vertraut","vertraut","vertraut"],varieties:[{variant:"vertraut + mit",prepositions:["mit"],explanation:"To be familiar with.",examples:["Ich bin mit dem System vertraut."]}]},
  {base:"gewöhnt",past:"gewöhnte",participle:"gewöhnt",translations:["to be used to"],derived:["gewöhnt","gewöhnt","gewöhnt"],varieties:[{variant:"gewöhnt + an",prepositions:["an"],explanation:"To be accustomed to.",examples:["Ich bin an das Klima gewöhnt."]}]},
  {base:"anpassen",past:"passte an",participle:"angepasst",translations:["to adapt","to adjust"],derived:["passe an","passt an","passt an"],varieties:[{variant:"sich anpassen + an",prepositions:["an"],explanation:"To adapt to.",examples:["Ich passe mich an die Situation an."]}]},
  {base:"angleichen",past:"glich an",participle:"angeglichen",translations:["to adjust","to align"],derived:["gleiche an","gleichst an","gleicht an"],varieties:[]},
  {base:"abstimmen",past:"stimmte ab",participle:"abgestimmt",translations:["to vote","to coordinate"],derived:["stimme ab","stimmst ab","stimmt ab"],varieties:[{variant:"abstimmen + über",prepositions:["über"],explanation:"To vote on.",examples:["Wir stimmen über den Vorschlag ab."]}]},
  {base:"koordinieren",past:"koordinierte",participle:"koordiniert",translations:["to coordinate"],derived:["koordiniere","koordinierst","koordiniert"],varieties:[]},
  {base:"synchronisieren",past:"synchronisierte",participle:"synchronisiert",translations:["to synchronize"],derived:["synchronisiere","synchronisierst","synchronisiert"],varieties:[]},
  {base:"harmonisieren",past:"harmonisierte",participle:"harmonisiert",translations:["to harmonize"],derived:["harmonisiere","harmonisierst","harmonisiert"],varieties:[]},
  {base:"vereinheitlichen",past:"vereinheitlichte",participle:"vereinheitlicht",translations:["to standardize","to unify"],derived:["vereinheitliche","vereinheitlichst","vereinheitlicht"],varieties:[]},
  {base:"standardisieren",past:"standardisierte",participle:"standardisiert",translations:["to standardize"],derived:["standardisiere","standardisierst","standardisiert"],varieties:[]},
  {base:"normalisieren",past:"normalisierte",participle:"normalisiert",translations:["to normalize"],derived:["normalisiere","normalisierst","normalisiert"],varieties:[]},
  {base:"regulieren",past:"regulierte",participle:"reguliert",translations:["to regulate"],derived:["reguliere","regulierst","reguliert"],varieties:[]},
  {base:"regeln",past:"regelte",participle:"geregelt",translations:["to regulate","to arrange"],derived:["regle","regelst","regelt"],varieties:[]},
  {base:"festlegen",past:"legte fest",participle:"festgelegt",translations:["to determine","to establish"],derived:["lege fest","legst fest","legt fest"],varieties:[]},
  {base:"bestimmen",past:"bestimmte",participle:"bestimmt",translations:["to determine","to decide"],derived:["bestimme","bestimmst","bestimmt"],varieties:[]},
  {base:"definieren",past:"definierte",participle:"definiert",translations:["to define"],derived:["definiere","definierst","definiert"],varieties:[]},
  {base:"festsetzen",past:"setzte fest",participle:"festgesetzt",translations:["to fix","to set"],derived:["setze fest","setzt fest","setzt fest"],varieties:[]},
  {base:"fixieren",past:"fixierte",participle:"fixiert",translations:["to fix"],derived:["fixiere","fixierst","fixiert"],varieties:[]},
  {base:"verankern",past:"verankerte",participle:"verankert",translations:["to anchor"],derived:["verankere","verankerst","verankert"],varieties:[]},
  {base:"befestigen",past:"befestigte",participle:"befestigt",translations:["to fasten","to attach"],derived:["befestige","befestigst","befestigt"],varieties:[]},
  {base:"anbringen",past:"brachte an",participle:"angebracht",translations:["to attach","to install"],derived:["bringe an","bringst an","bringt an"],varieties:[]},
  {base:"montieren",past:"montierte",participle:"montiert",translations:["to install","to assemble"],derived:["montiere","montierst","montiert"],varieties:[]},
  {base:"installieren",past:"installierte",participle:"installiert",translations:["to install"],derived:["installiere","installierst","installiert"],varieties:[]},
  {base:"einrichten",past:"richtete ein",participle:"eingerichtet",translations:["to set up","to furnish"],derived:["richte ein","richtest ein","richtet ein"],varieties:[]},
  {base:"ausstatten",past:"stattete aus",participle:"ausgestattet",translations:["to equip"],derived:["statte aus","stattest aus","stattet aus"],varieties:[{variant:"ausstatten + mit",prepositions:["mit"],explanation:"To equip with.",examples:["Das Zimmer ist gut ausgestattet."]}]},
  {base:"ausrüsten",past:"rüstete aus",participle:"ausgerüstet",translations:["to equip"],derived:["rüste aus","rüstest aus","rüstet aus"],varieties:[]},
  {base:"versehen",past:"versah",participle:"versehen",translations:["to provide","to equip"],derived:["versehe","versiehst","versieht"],varieties:[{variant:"versehen + mit",prepositions:["mit"],explanation:"To provide with.",examples:["Das Auto ist mit GPS versehen."]}]},
  {base:"beliefern",past:"belieferte",participle:"beliefert",translations:["to supply"],derived:["beliefere","belieferst","beliefert"],varieties:[{variant:"beliefern + mit",prepositions:["mit"],explanation:"To supply with.",examples:["Wir beliefern Sie mit frischen Produkten."]}]},
  {base:"versorgen",past:"versorgte",participle:"versorgt",translations:["to supply","to provide"],derived:["versorge","versorgst","versorgt"],varieties:[{variant:"versorgen + mit",prepositions:["mit"],explanation:"To supply with.",examples:["Die Stadt versorgt uns mit Wasser."]}]},
  {base:"bereitstellen",past:"stellte bereit",participle:"bereitgestellt",translations:["to provide","to make available"],derived:["stelle bereit","stellst bereit","stellt bereit"],varieties:[]},
  {base:"zur Verfügung stellen",past:"stellte zur Verfügung",participle:"zur Verfügung gestellt",translations:["to make available"],derived:["stelle zur Verfügung","stellst zur Verfügung","stellt zur Verfügung"],varieties:[]},
  {base:"bieten",past:"bot",participle:"geboten",translations:["to offer","to provide"],derived:["biete","bietest","bietet"],varieties:[]},
  {base:"gewähren",past:"gewährte",participle:"gewährt",translations:["to grant","to provide"],derived:["gewähre","gewährst","gewährt"],varieties:[]},
  {base:"gewährleisten",past:"gewährleistete",participle:"gewährleistet",translations:["to ensure","to guarantee"],derived:["gewährleiste","gewährleistest","gewährleistet"],varieties:[]},
  {base:"sicherstellen",past:"stellte sicher",participle:"sichergestellt",translations:["to ensure"],derived:["stelle sicher","stellst sicher","stellt sicher"],varieties:[]},
  {base:"zusichern",past:"sicherte zu",participle:"zugesichert",translations:["to assure"],derived:["sichere zu","sicherst zu","sichert zu"],varieties:[]},
  {base:"versprechen",past:"versprach",participle:"versprochen",translations:["to promise"],derived:["verspreche","versprichst","verspricht"],varieties:[]},
  {base:"zusagen",past:"sagte zu",participle:"zugesagt",translations:["to promise","to accept invitation"],derived:["sage zu","sagst zu","sagt zu"],varieties:[]},
  {base:"absagen",past:"sagte ab",participle:"abgesagt",translations:["to cancel","to decline"],derived:["sage ab","sagst ab","sagt ab"],varieties:[]},
  {base:"stornieren",past:"stornierte",participle:"storniert",translations:["to cancel"],derived:["storniere","stornierst","storniert"],varieties:[]},
  {base:"annullieren",past:"annullierte",participle:"annulliert",translations:["to annul","to cancel"],derived:["annulliere","annullierst","annulliert"],varieties:[]},
  {base:"widerrufen",past:"widerrief",participle:"widerrufen",translations:["to revoke","to retract"],derived:["widerrufe","widerrufst","widerruft"],varieties:[]},
  {base:"zurücknehmen",past:"nahm zurück",participle:"zurückgenommen",translations:["to take back","to withdraw"],derived:["nehme zurück","nimmst zurück","nimmt zurück"],varieties:[]},
  {base:"zurückziehen",past:"zog zurück",participle:"zurückgezogen",translations:["to withdraw"],derived:["ziehe zurück","ziehst zurück","zieht zurück"],varieties:[{variant:"sich zurückziehen",explanation:"Reflexive: to retreat or withdraw.",examples:["Ich ziehe mich zurück."]}]},
  {base:"rückgängig machen",past:"machte rückgängig",participle:"rückgängig gemacht",translations:["to undo","to reverse"],derived:["mache rückgängig","machst rückgängig","macht rückgängig"],varieties:[]},
  {base:"revidieren",past:"revidierte",participle:"revidiert",translations:["to revise"],derived:["revidiere","revidierst","revidiert"],varieties:[]},
  {base:"korrigieren",past:"korrigierte",participle:"korrigiert",translations:["to correct"],derived:["korrigiere","korrigierst","korrigiert"],varieties:[]},
  {base:"berichtigen",past:"berichtigte",participle:"berichtigt",translations:["to correct","to rectify"],derived:["berichtige","berichtigst","berichtigt"],varieties:[]},
  {base:"richtigstellen",past:"stellte richtig",participle:"richtiggestellt",translations:["to correct","to set straight"],derived:["stelle richtig","stellst richtig","stellt richtig"],varieties:[]},
  {base:"klarstellen",past:"stellte klar",participle:"klargestellt",translations:["to clarify"],derived:["stelle klar","stellst klar","stellt klar"],varieties:[]},
  {base:"präzisieren",past:"präzisierte",participle:"präzisiert",translations:["to specify"],derived:["präzisiere","präzisierst","präzisiert"],varieties:[]},
  {base:"spezifizieren",past:"spezifizierte",participle:"spezifiziert",translations:["to specify"],derived:["spezifiziere","spezifizierst","spezifiziert"],varieties:[]},
  {base:"konkretisieren",past:"konkretisierte",participle:"konkretisiert",translations:["to make concrete","to specify"],derived:["konkretisiere","konkretisierst","konkretisiert"],varieties:[]},
  {base:"ausarbeiten",past:"arbeitete aus",participle:"ausgearbeitet",translations:["to work out","to elaborate"],derived:["arbeite aus","arbeitest aus","arbeitet aus"],varieties:[]},
  {base:"ausführen",past:"führte aus",participle:"ausgeführt",translations:["to execute","to carry out"],derived:["führe aus","führst aus","führt aus"],varieties:[]},
  {base:"durchführen",past:"führte durch",participle:"durchgeführt",translations:["to carry out","to conduct"],derived:["führe durch","führst durch","führt durch"],varieties:[]},
  {base:"vollziehen",past:"vollzog",participle:"vollzogen",translations:["to execute","to carry out"],derived:["vollziehe","vollziehst","vollzieht"],varieties:[]},
  {base:"umsetzen",past:"setzte um",participle:"umgesetzt",translations:["to implement","to realize"],derived:["setze um","setzt um","setzt um"],varieties:[]},
  {base:"verwirklichen",past:"verwirklichte",participle:"verwirklicht",translations:["to realize","to achieve"],derived:["verwirkliche","verwirklichst","verwirklicht"],varieties:[]},
  {base:"realisieren",past:"realisierte",participle:"realisiert",translations:["to realize"],derived:["realisiere","realisierst","realisiert"],varieties:[]},
  {base:"implementieren",past:"implementierte",participle:"implementiert",translations:["to implement"],derived:["implementiere","implementierst","implementiert"],varieties:[]},
  {base:"einführen",past:"führte ein",participle:"eingeführt",translations:["to introduce","to implement"],derived:["führe ein","führst ein","führt ein"],varieties:[]},
  {base:"etablieren",past:"etablierte",participle:"etabliert",translations:["to establish"],derived:["etabliere","etablierst","etabliert"],varieties:[]},
  {base:"gründen",past:"gründete",participle:"gegründet",translations:["to found","to establish"],derived:["gründe","gründest","gründet"],varieties:[]},
  {base:"stiften",past:"stiftete",participle:"gestiftet",translations:["to found","to donate"],derived:["stifte","stiftest","stiftet"],varieties:[]},
  {base:"einsetzen",past:"setzte ein",participle:"eingesetzt",translations:["to deploy","to use"],derived:["setze ein","setzt ein","setzt ein"],varieties:[{variant:"sich einsetzen + für",prepositions:["für"],explanation:"To advocate for.",examples:["Sie setzt sich für Umweltschutz ein."]}]},
  {base:"anwenden",past:"wandte an",participle:"angewandt",translations:["to apply","to use"],derived:["wende an","wendest an","wendet an"],varieties:[]},
  {base:"verwenden",past:"verwendete",participle:"verwendet",translations:["to use"],derived:["verwende","verwendest","verwendet"],varieties:[]},
  {base:"benutzen",past:"benutzte",participle:"benutzt",translations:["to use"],derived:["benutze","benutzt","benutzt"],varieties:[]},
  {base:"gebrauchen",past:"gebrauchte",participle:"gebraucht",translations:["to use"],derived:["gebrauche","gebrauchst","gebraucht"],varieties:[]},
  {base:"nutzen",past:"nutzte",participle:"genutzt",translations:["to use","to utilize"],derived:["nutze","nutzt","nutzt"],varieties:[]},
  {base:"ausnutzen",past:"nutzte aus",participle:"ausgenutzt",translations:["to exploit","to take advantage of"],derived:["nutze aus","nutzt aus","nutzt aus"],varieties:[]},
  {base:"missbrauchen",past:"missbrauchte",participle:"missbraucht",translations:["to abuse","to misuse"],derived:["missbrauche","missbrauchst","missbraucht"],varieties:[]},
  {base:"manipulieren",past:"manipulierte",participle:"manipuliert",translations:["to manipulate"],derived:["manipuliere","manipulierst","manipuliert"],varieties:[]},
  {base:"beeinflussen",past:"beeinflusste",participle:"beeinflusst",translations:["to influence"],derived:["beeinflusse","beeinflusst","beeinflusst"],varieties:[]},
  {base:"lenken",past:"lenkte",participle:"gelenkt",translations:["to direct","to steer"],derived:["lenke","lenkst","lenkt"],varieties:[]},
  {base:"steuern",past:"steuerte",participle:"gesteuert",translations:["to steer","to control"],derived:["steuere","steuerst","steuert"],varieties:[]},
  {base:"regulieren",past:"regulierte",participle:"reguliert",translations:["to regulate"],derived:["reguliere","regulierst","reguliert"],varieties:[]},
  {base:"begrenzen",past:"begrenzte",participle:"begrenzt",translations:["to limit"],derived:["begrenze","begrenzt","begrenzt"],varieties:[]},
  {base:"einschränken",past:"schränkte ein",participle:"eingeschränkt",translations:["to restrict","to limit"],derived:["schränke ein","schränkst ein","schränkt ein"],varieties:[]},
  {base:"beschränken",past:"beschränkte",participle:"beschränkt",translations:["to restrict","to limit"],derived:["beschränke","beschränkst","beschränkt"],varieties:[{variant:"sich beschränken + auf",prepositions:["auf"],explanation:"To limit oneself to.",examples:["Ich beschränke mich auf das Wesentliche."]}]},
  {base:"einengen",past:"engte ein",participle:"eingeengt",translations:["to narrow","to constrict"],derived:["enge ein","engst ein","engt ein"],varieties:[]},
  {base:"erweitern",past:"erweiterte",participle:"erweitert",translations:["to expand","to extend"],derived:["erweitere","erweiterst","erweitert"],varieties:[]},
  {base:"ausdehnen",past:"dehnte aus",participle:"ausgedehnt",translations:["to extend","to expand"],derived:["dehne aus","dehnst aus","dehnt aus"],varieties:[]},
  {base:"ausbreiten",past:"breitete aus",participle:"ausgebreitet",translations:["to spread out"],derived:["breite aus","breitest aus","breitet aus"],varieties:[{variant:"sich ausbreiten",explanation:"Reflexive: to spread.",examples:["Die Krankheit breitet sich aus."]}]},
  {base:"verbreiten",past:"verbreitete",participle:"verbreitet",translations:["to spread","to disseminate"],derived:["verbreite","verbreitest","verbreitet"],varieties:[]},
  {base:"streuen",past:"streute",participle:"gestreut",translations:["to scatter","to spread"],derived:["streue","streust","streut"],varieties:[]},
  {base:"verstreuen",past:"verstreute",participle:"verstreut",translations:["to scatter"],derived:["verstreue","verstreust","verstreut"],varieties:[]},
  {base:"zerstreuen",past:"zerstreute",participle:"zerstreut",translations:["to scatter","to disperse"],derived:["zerstreue","zerstreust","zerstreut"],varieties:[]},
  {base:"auflösen",past:"löste auf",participle:"aufgelöst",translations:["to dissolve","to disband"],derived:["löse auf","löst auf","löst auf"],varieties:[{variant:"sich auflösen",explanation:"Reflexive: to dissolve.",examples:["Der Zucker löst sich auf."]}]},
  {base:"zerlegen",past:"zerlegte",participle:"zerlegt",translations:["to dismantle","to take apart"],derived:["zerlege","zerlegst","zerlegt"],varieties:[]},
  {base:"demontieren",past:"demontierte",participle:"demontiert",translations:["to dismantle"],derived:["demontiere","demontierst","demontiert"],varieties:[]},
  {base:"deinstallieren",past:"deinstallierte",participle:"deinstalliert",translations:["to uninstall"],derived:["deinstalliere","deinstallierst","deinstalliert"],varieties:[]},
  {base:"entfernen",past:"entfernte",participle:"entfernt",translations:["to remove"],derived:["entferne","entfernst","entfernt"],varieties:[]},
  {base:"beseitigen",past:"beseitigte",participle:"beseitigt",translations:["to remove","to eliminate"],derived:["beseitige","beseitigst","beseitigt"],varieties:[]},
  {base:"eliminieren",past:"eliminierte",participle:"eliminiert",translations:["to eliminate"],derived:["eliminiere","eliminierst","eliminiert"],varieties:[]},
  {base:"tilgen",past:"tilgte",participle:"getilgt",translations:["to erase","to eliminate"],derived:["tilge","tilgst","tilgt"],varieties:[]},
  {base:"löschen",past:"löschte",participle:"gelöscht",translations:["to delete","to extinguish"],derived:["lösche","löscht","löscht"],varieties:[]},
  {base:"streichen",past:"strich",participle:"gestrichen",translations:["to delete","to paint"],derived:["streiche","streichst","streicht"],varieties:[]},
  {base:"durchstreichen",past:"strich durch",participle:"durchgestrichen",translations:["to cross out"],derived:["streiche durch","streichst durch","streicht durch"],varieties:[]},
  {base:"ausstreichen",past:"strich aus",participle:"ausgestrichen",translations:["to delete","to strike out"],derived:["streiche aus","streichst aus","streicht aus"],varieties:[]},
  {base:"radieren",past:"radierte",participle:"radiert",translations:["to erase"],derived:["radiere","radierst","radiert"],varieties:[]},
  {base:"auslöschen",past:"löschte aus",participle:"ausgelöscht",translations:["to extinguish","to eradicate"],derived:["lösche aus","löscht aus","löscht aus"],varieties:[]},
  {base:"vernichten",past:"vernichtete",participle:"vernichtet",translations:["to destroy","to annihilate"],derived:["vernichte","vernichtest","vernichtet"],varieties:[]},
  {base:"ausrotten",past:"rottete aus",participle:"ausgerottet",translations:["to eradicate","to exterminate"],derived:["rotte aus","rottest aus","rottet aus"],varieties:[]},
  {base:"ausmerzen",past:"merzte aus",participle:"ausgemerzt",translations:["to eradicate","to eliminate"],derived:["merze aus","merzt aus","merzt aus"],varieties:[]},
  {base:"tilgen",past:"tilgte",participle:"getilgt",translations:["to eradicate","to pay off (debt)"],derived:["tilge","tilgst","tilgt"],varieties:[]},
  {base:"zurückzahlen",past:"zahlte zurück",participle:"zurückgezahlt",translations:["to repay"],derived:["zahle zurück","zahlst zurück","zahlt zurück"],varieties:[]},
  {base:"abbezahlen",past:"bezahlte ab",participle:"abbezahlt",translations:["to pay off"],derived:["bezahle ab","bezahlst ab","bezahlt ab"],varieties:[]},
  {base:"abzahlen",past:"zahlte ab",participle:"abgezahlt",translations:["to pay off in installments"],derived:["zahle ab","zahlst ab","zahlt ab"],varieties:[]},
  {base:"begleichen",past:"beglich",participle:"beglichen",translations:["to settle","to pay"],derived:["begleiche","begleichst","begleicht"],varieties:[]},
  {base:"erstatten",past:"erstattete",participle:"erstattet",translations:["to refund","to reimburse"],derived:["erstatte","erstattest","erstattet"],varieties:[]},
  {base:"zurückerstatten",past:"erstattete zurück",participle:"zurückerstattet",translations:["to refund"],derived:["erstatte zurück","erstattest zurück","erstattet zurück"],varieties:[]},
  {base:"rückerstatten",past:"erstattete zurück",participle:"rückerstattet",translations:["to reimburse"],derived:["erstatte zurück","erstattest zurück","erstattet zurück"],varieties:[]},
  {base:"vergüten",past:"vergütete",participle:"vergütet",translations:["to reimburse","to compensate"],derived:["vergüte","vergütest","vergütet"],varieties:[]},
  {base:"entschädigen",past:"entschädigte",participle:"entschädigt",translations:["to compensate"],derived:["entschädige","entschädigst","entschädigt"],varieties:[]},
  {base:"kompensieren",past:"kompensierte",participle:"kompensiert",translations:["to compensate"],derived:["kompensiere","kompensierst","kompensiert"],varieties:[]},
  {base:"ausgleichen",past:"glich aus",participle:"ausgeglichen",translations:["to balance","to compensate"],derived:["gleiche aus","gleichst aus","gleicht aus"],varieties:[]},
  {base:"abwägen",past:"wog ab",participle:"abgewogen",translations:["to weigh","to consider"],derived:["wäge ab","wägst ab","wägt ab"],varieties:[]},
  {base:"erwägen",past:"erwog",participle:"erwogen",translations:["to consider"],derived:["erwäge","erwägst","erwägt"],varieties:[]},
  {base:"in Betracht ziehen",past:"zog in Betracht",participle:"in Betracht gezogen",translations:["to consider"],derived:["ziehe in Betracht","ziehst in Betracht","zieht in Betracht"],varieties:[]},
  {base:"in Erwägung ziehen",past:"zog in Erwägung",participle:"in Erwägung gezogen",translations:["to consider"],derived:["ziehe in Erwägung","ziehst in Erwägung","zieht in Erwägung"],varieties:[]},
  {base:"bedenken",past:"bedachte",participle:"bedacht",translations:["to consider","to bear in mind"],derived:["bedenke","bedenkst","bedenkt"],varieties:[]},
  {base:"nachdenken",past:"dachte nach",participle:"nachgedacht",translations:["to think about"],derived:["denke nach","denkst nach","denkt nach"],varieties:[{variant:"nachdenken + über",prepositions:["über"],explanation:"To think about.",examples:["Ich denke über das Problem nach."]}]},
  {base:"überdenken",past:"überdachte",participle:"überdacht",translations:["to reconsider","to think over"],derived:["überdenke","überdenkst","überdenkt"],varieties:[]},
  {base:"durchdenken",past:"dachte durch",participle:"durchdacht",translations:["to think through"],derived:["denke durch","denkst durch","denkt durch"],varieties:[]},
  {base:"ausdenken",past:"dachte aus",participle:"ausgedacht",translations:["to think up","to devise"],derived:["denke aus","denkst aus","denkt aus"],varieties:[{variant:"sich ausdenken",explanation:"Reflexive: to come up with.",examples:["Ich denke mir etwas aus."]}]}
];

export default verbsB2;
