// verbs-db-c1.js - C1 Level - 225 verbs
const verbsC1 = [
  {base:"ablehnen",past:"lehnte ab",participle:"abgelehnt",translations:["to reject","to decline"],derived:["lehne ab","lehnst ab","lehnt ab"],varieties:[]},
  {base:"sich auseinandersetzen",past:"setzte sich auseinander",participle:"auseinandergesetzt",translations:["to deal with","to engage with"],reflexive:true,derived:["setze mich auseinander","setzt dich auseinander","setzt sich auseinander"],varieties:[{variant:"sich auseinandersetzen + mit",prepositions:["mit"],explanation:"To engage intensively with.",examples:["Wir setzen uns mit dem Thema auseinander."]}]},
  {base:"sich beziehen",past:"bezog sich",participle:"bezogen",translations:["to refer to"],reflexive:true,derived:["beziehe mich","beziehst dich","bezieht sich"],varieties:[{variant:"sich beziehen + auf",prepositions:["auf"],explanation:"To relate to.",examples:["Der Artikel bezieht sich auf aktuelle Forschung."]}]},
  {base:"überprüfen",past:"überprüfte",participle:"überprüft",translations:["to check","to verify"],derived:["überprüfe","überprüfst","überprüft"],varieties:[]},
  {base:"zurechtkommen",past:"kam zurecht",participle:"zurechtgekommen",translations:["to manage","to cope"],derived:["komme zurecht","kommst zurecht","kommt zurecht"],varieties:[{variant:"zurechtkommen + mit",prepositions:["mit"],explanation:"To cope with.",examples:["Er kommt gut mit Stress zurecht."]}]},
  {base:"sich verabschieden",past:"verabschiedete sich",participle:"verabschiedet",translations:["to say goodbye"],reflexive:true,derived:["verabschiede mich","verabschiedest dich","verabschiedet sich"],varieties:[{variant:"sich verabschieden + von",prepositions:["von"],explanation:"To say goodbye to.",examples:["Ich verabschiede mich von meinen Kollegen."]}]},
  {base:"hinterfragen",past:"hinterfragte",participle:"hinterfragt",translations:["to question","to challenge"],derived:["hinterfrage","hinterfragst","hinterfragt"],varieties:[]},
  {base:"voraussetzen",past:"setzte voraus",participle:"vorausgesetzt",translations:["to assume","to presuppose"],derived:["setze voraus","setzt voraus","setzt voraus"],varieties:[]},
  {base:"gewährleisten",past:"gewährleistete",participle:"gewährleistet",translations:["to ensure","to guarantee"],derived:["gewährleiste","gewährleistest","gewährleistet"],varieties:[]},
  {base:"sich bewähren",past:"bewährte sich",participle:"bewährt",translations:["to prove oneself"],reflexive:true,derived:["bewähre mich","bewährst dich","bewährt sich"],varieties:[]},
  {base:"erörtern",past:"erörterte",participle:"erörtert",translations:["to discuss","to debate"],derived:["erörtere","erörterst","erörtert"],varieties:[]},
  {base:"darlegen",past:"legte dar",participle:"dargelegt",translations:["to present","to explain"],derived:["lege dar","legst dar","legt dar"],varieties:[]},
  {base:"veranschaulichen",past:"veranschaulichte",participle:"veranschaulicht",translations:["to illustrate"],derived:["veranschauliche","veranschaulichst","veranschaulicht"],varieties:[]},
  {base:"konkretisieren",past:"konkretisierte",participle:"konkretisiert",translations:["to make concrete","to specify"],derived:["konkretisiere","konkretisierst","konkretisiert"],varieties:[]},
  {base:"differenzieren",past:"differenzierte",participle:"differenziert",translations:["to differentiate"],derived:["differenziere","differenzierst","differenziert"],varieties:[]},
  {base:"kategorisieren",past:"kategorisierte",participle:"kategorisiert",translations:["to categorize"],derived:["kategorisiere","kategorisierst","kategorisiert"],varieties:[]},
  {base:"klassifizieren",past:"klassifizierte",participle:"klassifiziert",translations:["to classify"],derived:["klassifiziere","klassifizierst","klassifiziert"],varieties:[]},
  {base:"einordnen",past:"ordnete ein",participle:"eingeordnet",translations:["to classify","to categorize"],derived:["ordne ein","ordnest ein","ordnet ein"],varieties:[]},
  {base:"zuordnen",past:"ordnete zu",participle:"zugeordnet",translations:["to assign","to allocate"],derived:["ordne zu","ordnest zu","ordnet zu"],varieties:[]},
  {base:"untergliedern",past:"gliederte unter",participle:"untergliedert",translations:["to subdivide"],derived:["gliedere unter","gliederst unter","gliedert unter"],varieties:[]},
  {base:"aufgliedern",past:"gliederte auf",participle:"aufgegliedert",translations:["to break down","to subdivide"],derived:["gliedere auf","gliederst auf","gliedert auf"],varieties:[]},
  {base:"unterteilen",past:"unterteilte",participle:"unterteilt",translations:["to subdivide","to divide"],derived:["unterteile","unterteilst","unterteilt"],varieties:[]},
  {base:"aufteilen",past:"teilte auf",participle:"aufgeteilt",translations:["to divide up","to split"],derived:["teile auf","teilst auf","teilt auf"],varieties:[]},
  {base:"zerlegen",past:"zerlegte",participle:"zerlegt",translations:["to dismantle","to analyze"],derived:["zerlege","zerlegst","zerlegt"],varieties:[]},
  {base:"sezieren",past:"sezierte",participle:"seziert",translations:["to dissect"],derived:["seziere","sezierst","seziert"],varieties:[]},
  {base:"aufschlüsseln",past:"schlüsselte auf",participle:"aufgeschlüsselt",translations:["to break down","to itemize"],derived:["schlüssle auf","schlüsselst auf","schlüsselt auf"],varieties:[]},
  {base:"detaillieren",past:"detaillierte",participle:"detailliert",translations:["to detail"],derived:["detailliere","detaillierst","detailliert"],varieties:[]},
  {base:"ausführlich darstellen",past:"stellte ausführlich dar",participle:"ausführlich dargestellt",translations:["to present in detail"],derived:["stelle ausführlich dar","stellst ausführlich dar","stellt ausführlich dar"],varieties:[]},
  {base:"elaborieren",past:"elaborierte",participle:"elaboriert",translations:["to elaborate"],derived:["elaboriere","elaborierst","elaboriert"],varieties:[]},
  {base:"vertiefen",past:"vertiefte",participle:"vertieft",translations:["to deepen"],derived:["vertiefe","vertiefst","vertieft"],varieties:[{variant:"sich vertiefen + in",prepositions:["in"],explanation:"To immerse oneself in.",examples:["Ich vertiefe mich in das Thema."]}]},
  {base:"intensivieren",past:"intensivierte",participle:"intensiviert",translations:["to intensify"],derived:["intensiviere","intensivierst","intensiviert"],varieties:[]},
  {base:"verstärken",past:"verstärkte",participle:"verstärkt",translations:["to strengthen","to reinforce"],derived:["verstärke","verstärkst","verstärkt"],varieties:[]},
  {base:"verschärfen",past:"verschärfte",participle:"verschärft",translations:["to tighten","to intensify"],derived:["verschärfe","verschärfst","verschärft"],varieties:[]},
  {base:"zuspitzen",past:"spitzte zu",participle:"zugespitzt",translations:["to intensify","to exacerbate"],derived:["spitze zu","spitzt zu","spitzt zu"],varieties:[{variant:"sich zuspitzen",explanation:"Reflexive: to intensify or worsen.",examples:["Die Lage spitzt sich zu."]}]},
  {base:"eskalieren",past:"eskalierte",participle:"eskaliert",translations:["to escalate"],derived:["eskaliere","eskalierst","eskaliert"],varieties:[]},
  {base:"entschärfen",past:"entschärfte",participle:"entschärft",translations:["to defuse","to de-escalate"],derived:["entschärfe","entschärfst","entschärft"],varieties:[]},
  {base:"besänftigen",past:"besänftigte",participle:"besänftigt",translations:["to appease","to calm"],derived:["besänftige","besänftigst","besänftigt"],varieties:[]},
  {base:"schlichten",past:"schlichtete",participle:"geschlichtet",translations:["to mediate","to settle"],derived:["schlichte","schlichtest","schlichtet"],varieties:[]},
  {base:"vermitteln",past:"vermittelte",participle:"vermittelt",translations:["to mediate","to convey"],derived:["vermittle","vermittelst","vermittelt"],varieties:[]},
  {base:"moderieren",past:"moderierte",participle:"moderiert",translations:["to moderate"],derived:["moderiere","moderierst","moderiert"],varieties:[]},
  {base:"intervenieren",past:"intervenierte",participle:"interveniert",translations:["to intervene"],derived:["interveniere","intervenierst","interveniert"],varieties:[]},
  {base:"eingreifen",past:"griff ein",participle:"eingegriffen",translations:["to intervene"],derived:["greife ein","greifst ein","greift ein"],varieties:[]},
  {base:"einschreiten",past:"schritt ein",participle:"eingeschritten",translations:["to intervene","to take action"],derived:["schreite ein","schreitest ein","schreitet ein"],varieties:[]},
  {base:"dazwischenkommen",past:"kam dazwischen",participle:"dazwischengekommen",translations:["to intervene","to interfere"],derived:["komme dazwischen","kommst dazwischen","kommt dazwischen"],varieties:[]},
  {base:"stören",past:"störte",participle:"gestört",translations:["to disturb","to interfere"],derived:["störe","störst","stört"],varieties:[]},
  {base:"beeinträchtigen",past:"beeinträchtigte",participle:"beeinträchtigt",translations:["to impair","to adversely affect"],derived:["beeinträchtige","beeinträchtigst","beeinträchtigt"],varieties:[]},
  {base:"hemmen",past:"hemmte",participle:"gehemmt",translations:["to inhibit","to hamper"],derived:["hemme","hemmst","hemmt"],varieties:[]},
  {base:"unterbinden",past:"unterband",participle:"unterbunden",translations:["to prevent","to stop"],derived:["unterbinde","unterbindest","unterbindet"],varieties:[]},
  {base:"unterlassen",past:"unterließ",participle:"unterlassen",translations:["to refrain from","to omit"],derived:["unterlasse","unterlässt","unterlässt"],varieties:[]},
  {base:"absehen",past:"sah ab",participle:"abgesehen",translations:["to refrain from","to foresee"],derived:["sehe ab","siehst ab","sieht ab"],varieties:[{variant:"absehen + von",prepositions:["von"],explanation:"To refrain from.",examples:["Ich sehe davon ab."]}]},
  {base:"abstand nehmen",past:"nahm Abstand",participle:"Abstand genommen",translations:["to refrain from"],derived:["nehme Abstand","nimmst Abstand","nimmt Abstand"],varieties:[{variant:"Abstand nehmen + von",prepositions:["von"],explanation:"To distance oneself from.",examples:["Er nimmt von dem Plan Abstand."]}]},
  {base:"distanzieren",past:"distanzierte",participle:"distanziert",translations:["to distance"],derived:["distanziere","distanzierst","distanziert"],varieties:[{variant:"sich distanzieren + von",prepositions:["von"],explanation:"To distance oneself from.",examples:["Ich distanziere mich von dieser Aussage."]}]},
  {base:"abgrenzen",past:"grenzte ab",participle:"abgegrenzt",translations:["to demarcate","to distinguish"],derived:["grenze ab","grenzt ab","grenzt ab"],varieties:[{variant:"sich abgrenzen + von",prepositions:["von"],explanation:"To distinguish oneself from.",examples:["Wir grenzen uns vom Wettbewerb ab."]}]},
  {base:"unterscheiden",past:"unterschied",participle:"unterschieden",translations:["to distinguish","to differentiate"],derived:["unterscheide","unterscheidest","unterscheidet"],varieties:[{variant:"sich unterscheiden + von",prepositions:["von"],explanation:"To differ from.",examples:["Das unterscheidet sich von anderen Methoden."]}]},
  {base:"abweichen",past:"wich ab",participle:"abgewichen",translations:["to deviate","to differ"],derived:["weiche ab","weichst ab","weicht ab"],varieties:[{variant:"abweichen + von",prepositions:["von"],explanation:"To deviate from.",examples:["Die Ergebnisse weichen von der Prognose ab."]}]},
  {base:"variieren",past:"variierte",participle:"variiert",translations:["to vary"],derived:["variiere","variierst","variiert"],varieties:[]},
  {base:"divergieren",past:"divergierte",participle:"divergiert",translations:["to diverge"],derived:["divergiere","divergierst","divergiert"],varieties:[]},
  {base:"konvergieren",past:"konvergierte",participle:"konvergiert",translations:["to converge"],derived:["konvergiere","konvergierst","konvergiert"],varieties:[]},
  {base:"übereinstimmen",past:"stimmte überein",participle:"übereingestimmt",translations:["to agree","to correspond"],derived:["stimme überein","stimmst überein","stimmt überein"],varieties:[{variant:"übereinstimmen + mit",prepositions:["mit"],explanation:"To agree with.",examples:["Das stimmt mit den Fakten überein."]}]},
  {base:"korrespondieren",past:"korrespondierte",participle:"korrespondiert",translations:["to correspond"],derived:["korrespondiere","korrespondierst","korrespondiert"],varieties:[{variant:"korrespondieren + mit",prepositions:["mit"],explanation:"To correspond with.",examples:["Die Theorie korrespondiert mit der Praxis."]}]},
  {base:"harmonieren",past:"harmonierte",participle:"harmoniert",translations:["to harmonize"],derived:["harmoniere","harmonierst","harmoniert"],varieties:[{variant:"harmonieren + mit",prepositions:["mit"],explanation:"To harmonize with.",examples:["Die Farben harmonieren miteinander."]}]},
  {base:"passen",past:"passte",participle:"gepasst",translations:["to fit","to suit"],derived:["passe","passt","passt"],varieties:[{variant:"passen + zu",prepositions:["zu"],explanation:"To match or suit.",examples:["Das Hemd passt zur Hose."]}]},
  {base:"eignen",past:"eignete",participle:"geeignet",translations:["to be suitable"],derived:["eigne","eignest","eignet"],varieties:[{variant:"sich eignen + für",prepositions:["für"],explanation:"To be suitable for.",examples:["Diese Methode eignet sich für Anfänger."]}]},
  {base:"taugen",past:"taugte",participle:"getaugt",translations:["to be good for"],derived:["tauge","taugst","taugt"],varieties:[{variant:"taugen + für",prepositions:["für"],explanation:"To be suitable for.",examples:["Das taugt nichts."]}]},
  {base:"genügen",past:"genügte",participle:"genügt",translations:["to suffice","to be enough"],derived:["genüge","genügst","genügt"],varieties:[]},
  {base:"ausreichen",past:"reichte aus",participle:"ausgereicht",translations:["to suffice","to be sufficient"],derived:["reiche aus","reichst aus","reicht aus"],varieties:[]},
  {base:"hinreichen",past:"reichte hin",participle:"hingereicht",translations:["to suffice"],derived:["reiche hin","reichst hin","reicht hin"],varieties:[]},
  {base:"langen",past:"langte",participle:"gelangt",translations:["to suffice","to reach"],derived:["lange","langst","langt"],varieties:[]},
  {base:"reichen",past:"reichte",participle:"gereicht",translations:["to reach","to suffice","to hand"],derived:["reiche","reichst","reicht"],varieties:[]},
  {base:"erstrecken",past:"erstreckte",participle:"erstreckt",translations:["to extend","to stretch"],derived:["erstrecke","erstreckst","erstreckt"],varieties:[{variant:"sich erstrecken + über",prepositions:["über"],explanation:"To extend over.",examples:["Das Gebiet erstreckt sich über mehrere Kilometer."]}]},
  {base:"dehnen",past:"dehnte",participle:"gedehnt",translations:["to stretch","to extend"],derived:["dehne","dehnst","dehnt"],varieties:[]},
  {base:"spannen",past:"spannte",participle:"gespannt",translations:["to stretch","to tighten"],derived:["spanne","spannst","spannt"],varieties:[]},
  {base:"straffen",past:"straffte",participle:"gestrafft",translations:["to tighten"],derived:["straffe","straffst","strafft"],varieties:[]},
  {base:"anspannen",past:"spannte an",participle:"angespannt",translations:["to tense","to strain"],derived:["spanne an","spannst an","spannt an"],varieties:[]},
  {base:"entspannen",past:"entspannte",participle:"entspannt",translations:["to relax"],derived:["entspanne","entspannst","entspannt"],varieties:[{variant:"sich entspannen",explanation:"Reflexive: to relax.",examples:["Ich entspanne mich am Strand."]}]},
  {base:"lockern",past:"lockerte",participle:"gelockert",translations:["to loosen","to relax"],derived:["lockere","lockerst","lockert"],varieties:[]},
  {base:"lösen",past:"löste",participle:"gelöst",translations:["to loosen","to solve"],derived:["löse","löst","löst"],varieties:[{variant:"sich lösen",explanation:"Reflexive: to come loose.",examples:["Die Schraube löst sich."]}]},
  {base:"entwirren",past:"entwirrte",participle:"entwirrt",translations:["to untangle","to unravel"],derived:["entwirre","entwirrst","entwirrt"],varieties:[]},
  {base:"enträtseln",past:"enträtselete",participle:"enträtselt",translations:["to solve","to decipher"],derived:["enträtsele","enträtselst","enträtselt"],varieties:[]},
  {base:"entschlüsseln",past:"entschlüsselte",participle:"entschlüsselt",translations:["to decipher","to decode"],derived:["entschlüssele","entschlüsselst","entschlüsselt"],varieties:[]},
  {base:"dechiffrieren",past:"dechiffrierte",participle:"dechiffriert",translations:["to decipher","to decode"],derived:["dechiffriere","dechiffrierst","dechiffriert"],varieties:[]},
  {base:"dekodieren",past:"dekodierte",participle:"dekodiert",translations:["to decode"],derived:["dekodiere","dekodierst","dekodiert"],varieties:[]},
  {base:"kodieren",past:"kodierte",participle:"kodiert",translations:["to code","to encode"],derived:["kodiere","kodierst","kodiert"],varieties:[]},
  {base:"verschlüsseln",past:"verschlüsselte",participle:"verschlüsselt",translations:["to encrypt","to encode"],derived:["verschlüssele","verschlüsselst","verschlüsselt"],varieties:[]},
  {base:"chiffrieren",past:"chiffrierte",participle:"chiffriert",translations:["to encrypt"],derived:["chiffriere","chiffrierst","chiffriert"],varieties:[]},
  {base:"codieren",past:"codierte",participle:"codiert",translations:["to encode"],derived:["codiere","codierst","codiert"],varieties:[]},
  {base:"transkribieren",past:"transkribierte",participle:"transkribiert",translations:["to transcribe"],derived:["transkribiere","transkribierst","transkribiert"],varieties:[]},
  {base:"übertragen",past:"übertrug",participle:"übertragen",translations:["to transfer","to transmit","to translate"],derived:["übertrage","überträgst","überträgt"],varieties:[]},
  {base:"übersetzen",past:"übersetzte",participle:"übersetzt",translations:["to translate"],derived:["übersetze","übersetzt","übersetzt"],varieties:[]},
  {base:"dolmetschen",past:"dolmetschte",participle:"gedolmetscht",translations:["to interpret"],derived:["dolmetsche","dolmetschst","dolmetscht"],varieties:[]},
  {base:"interpretieren",past:"interpretierte",participle:"interpretiert",translations:["to interpret"],derived:["interpretiere","interpretierst","interpretiert"],varieties:[]},
  {base:"deuten",past:"deutete",participle:"gedeutet",translations:["to interpret","to point"],derived:["deute","deutest","deutet"],varieties:[]},
  {base:"auslegen",past:"legte aus",participle:"ausgelegt",translations:["to interpret","to construe"],derived:["lege aus","legst aus","legt aus"],varieties:[]},
  {base:"auffassen",past:"fasste auf",participle:"aufgefasst",translations:["to interpret","to understand"],derived:["fasse auf","fasst auf","fasst auf"],varieties:[]},
  {base:"begreifen",past:"begriff",participle:"begriffen",translations:["to comprehend","to understand"],derived:["begreife","begreifst","begreift"],varieties:[]},
  {base:"erfassen",past:"erfasste",participle:"erfasst",translations:["to grasp","to comprehend","to record"],derived:["erfasse","erfasst","erfasst"],varieties:[]},
  {base:"nachvollziehen",past:"vollzog nach",participle:"nachvollzogen",translations:["to comprehend","to understand"],derived:["vollziehe nach","vollziehst nach","vollzieht nach"],varieties:[]},
  {base:"einsehen",past:"sah ein",participle:"eingesehen",translations:["to realize","to acknowledge"],derived:["sehe ein","siehst ein","sieht ein"],varieties:[]},
  {base:"einsichten",past:"sichtete ein",participle:"eingesichtet",translations:["to inspect"],derived:["sichte ein","sichtest ein","sichtet ein"],varieties:[]},
  {base:"durchschauen",past:"durchschaute",participle:"durchschaut",translations:["to see through","to understand"],derived:["durchschaue","durchschaust","durchschaut"],varieties:[]},
  {base:"durchblicken",past:"blickte durch",participle:"durchgeblickt",translations:["to see through","to understand"],derived:["blicke durch","blickst durch","blickt durch"],varieties:[]},
  {base:"kapieren",past:"kapierte",participle:"kapiert",translations:["to get it","to understand (informal)"],derived:["kapiere","kapierst","kapiert"],varieties:[]},
  {base:"schnallen",past:"schnallte",participle:"geschnallt",translations:["to get it","to understand (slang)"],derived:["schnalle","schnallst","schnallt"],varieties:[]},
  {base:"checken",past:"checkte",participle:"gecheckt",translations:["to check","to get it (slang)"],derived:["checke","checkst","checkt"],varieties:[]},
  {base:"raffen",past:"raffte",participle:"gerafft",translations:["to get it (slang)"],derived:["raffe","raffst","rafft"],varieties:[]},
  {base:"mitbekommen",past:"bekam mit",participle:"mitbekommen",translations:["to notice","to catch"],derived:["bekomme mit","bekommst mit","bekommt mit"],varieties:[]},
  {base:"mitkriegen",past:"kriegte mit",participle:"mitgekriegt",translations:["to notice","to catch (informal)"],derived:["kriege mit","kriegst mit","kriegt mit"],varieties:[]},
  {base:"wahrnehmen",past:"nahm wahr",participle:"wahrgenommen",translations:["to perceive","to notice"],derived:["nehme wahr","nimmst wahr","nimmt wahr"],varieties:[]},
  {base:"registrieren",past:"registrierte",participle:"registriert",translations:["to register","to notice"],derived:["registriere","registrierst","registriert"],varieties:[]},
  {base:"konstatieren",past:"konstatierte",participle:"konstatiert",translations:["to note","to observe"],derived:["konstatiere","konstatierst","konstatiert"],varieties:[]},
  {base:"feststellen",past:"stellte fest",participle:"festgestellt",translations:["to determine","to note"],derived:["stelle fest","stellst fest","stellt fest"],varieties:[]},
  {base:"ermitteln",past:"ermittelte",participle:"ermittelt",translations:["to determine","to investigate"],derived:["ermittle","ermittelst","ermittelt"],varieties:[]},
  {base:"eruieren",past:"eruierte",participle:"eruiert",translations:["to ascertain","to determine"],derived:["eruiere","eruierst","eruiert"],varieties:[]},
  {base:"ausfindig machen",past:"machte ausfindig",participle:"ausfindig gemacht",translations:["to locate","to track down"],derived:["mache ausfindig","machst ausfindig","macht ausfindig"],varieties:[]},
  {base:"aufspüren",past:"spürte auf",participle:"aufgespürt",translations:["to track down","to trace"],derived:["spüre auf","spürst auf","spürt auf"],varieties:[]},
  {base:"aufstöbern",past:"stöberte auf",participle:"aufgestöbert",translations:["to ferret out","to track down"],derived:["stöbere auf","stöberst auf","stöbert auf"],varieties:[]},
  {base:"aufdecken",past:"deckte auf",participle:"aufgedeckt",translations:["to uncover","to reveal"],derived:["decke auf","deckst auf","deckt auf"],varieties:[]},
  {base:"enthüllen",past:"enthüllte",participle:"enthüllt",translations:["to reveal","to unveil"],derived:["enthülle","enthüllst","enthüllt"],varieties:[]},
  {base:"offenbaren",past:"offenbarte",participle:"offenbart",translations:["to reveal"],derived:["offenbare","offenbarst","offenbart"],varieties:[]},
  {base:"preisgeben",past:"gab preis",participle:"preisgegeben",translations:["to reveal","to disclose"],derived:["gebe preis","gibst preis","gibt preis"],varieties:[]},
  {base:"verraten",past:"verriet",participle:"verraten",translations:["to betray","to reveal"],derived:["verrate","verrätst","verrät"],varieties:[]},
  {base:"ausplaudern",past:"plauderte aus",participle:"ausgeplaudert",translations:["to blab","to divulge"],derived:["plaudere aus","plauderst aus","plaudert aus"],varieties:[]},
  {base:"ausposaunen",past:"posaun te aus",participle:"ausposaunt",translations:["to trumpet","to broadcast"],derived:["posaune aus","posaunst aus","posaunt aus"],varieties:[]},
  {base:"verbreiten",past:"verbreitete",participle:"verbreitet",translations:["to spread","to disseminate"],derived:["verbreite","verbreitest","verbreitet"],varieties:[]},
  {base:"verkünden",past:"verkündete",participle:"verkündet",translations:["to announce","to proclaim"],derived:["verkünde","verkündest","verkündet"],varieties:[]},
  {base:"proklamieren",past:"proklamierte",participle:"proklamiert",translations:["to proclaim"],derived:["proklamiere","proklamierst","proklamiert"],varieties:[]},
  {base:"deklarieren",past:"deklarierte",participle:"deklariert",translations:["to declare"],derived:["deklariere","deklarierst","deklariert"],varieties:[]},
  {base:"kundtun",past:"tat kund",participle:"kundgetan",translations:["to make known"],derived:["tue kund","tust kund","tut kund"],varieties:[]},
  {base:"mitteilen",past:"teilte mit",participle:"mitgeteilt",translations:["to communicate","to inform"],derived:["teile mit","teilst mit","teilt mit"],varieties:[]},
  {base:"kundgeben",past:"gab kund",participle:"kundgegeben",translations:["to announce"],derived:["gebe kund","gibst kund","gibt kund"],varieties:[]},
  {base:"verlautbaren",past:"verlautbarte",participle:"verlautbart",translations:["to announce","to state"],derived:["verlautbare","verlautbarst","verlautbart"],varieties:[]},
  {base:"dementieren",past:"dementierte",participle:"dementiert",translations:["to deny","to refute"],derived:["dementiere","dementierst","dementiert"],varieties:[]},
  {base:"widerlegen",past:"widerlegte",participle:"widerlegt",translations:["to refute","to disprove"],derived:["widerlege","widerlegst","widerlegt"],varieties:[]},
  {base:"entkräften",past:"entkräftete",participle:"entkräftet",translations:["to refute","to weaken"],derived:["entkräfte","entkräftest","entkräftet"],varieties:[]},
  {base:"anfechten",past:"focht an",participle:"angefochten",translations:["to challenge","to contest"],derived:["fechte an","fichtst an","ficht an"],varieties:[]},
  {base:"bestreiten",past:"bestritt",participle:"bestritten",translations:["to contest","to dispute"],derived:["bestreite","bestreitest","bestreitet"],varieties:[]},
  {base:"beanstanden",past:"beanstandete",participle:"beanstandet",translations:["to object to","to complain about"],derived:["beanstande","beanstandest","beanstandet"],varieties:[]},
  {base:"reklamieren",past:"reklamierte",participle:"reklamiert",translations:["to complain","to claim"],derived:["reklamiere","reklamierst","reklamiert"],varieties:[]},
  {base:"monieren",past:"monierte",participle:"moniert",translations:["to criticize","to complain"],derived:["moniere","monierst","moniert"],varieties:[]},
  {base:"bemängeln",past:"bemängelte",participle:"bemängelt",translations:["to criticize","to find fault with"],derived:["bemängle","bemängelst","bemängelt"],varieties:[]},
  {base:"beanstandungen erheben",past:"erhob Beanstandungen",participle:"Beanstandungen erhoben",translations:["to raise objections"],derived:["erhebe Beanstandungen","erhebst Beanstandungen","erhebt Beanstandungen"],varieties:[]},
  {base:"kritisieren",past:"kritisierte",participle:"kritisiert",translations:["to criticize"],derived:["kritisiere","kritisierst","kritisiert"],varieties:[]},
  {base:"tadeln",past:"tadelte",participle:"getadelt",translations:["to reprimand","to criticize"],derived:["tadle","tadelst","tadelt"],varieties:[]},
  {base:"rügen",past:"rügte",participle:"gerügt",translations:["to reprimand"],derived:["rüge","rügst","rügt"],varieties:[]},
  {base:"zurechtweisen",past:"wies zurecht",participle:"zurechtgewiesen",translations:["to reprimand"],derived:["weise zurecht","weist zurecht","weist zurecht"],varieties:[]},
  {base:"verwarnen",past:"verwarnte",participle:"verwarnt",translations:["to caution","to warn"],derived:["verwarne","verwarnst","verwarnt"],varieties:[]},
  {base:"ermahnen",past:"ermahnte",participle:"ermahnt",translations:["to admonish"],derived:["ermahne","ermahnst","ermahnt"],varieties:[]},
  {base:"mahnen",past:"mahnte",participle:"gemahnt",translations:["to admonish","to remind"],derived:["mahne","mahnst","mahnt"],varieties:[]},
  {base:"appellieren",past:"appellierte",participle:"appelliert",translations:["to appeal"],derived:["appelliere","appellierst","appelliert"],varieties:[{variant:"appellieren + an",prepositions:["an"],explanation:"To appeal to.",examples:["Ich appelliere an Ihre Vernunft."]}]},
  {base:"plädieren",past:"plädierte",participle:"plädiert",translations:["to plead","to argue for"],derived:["plädiere","plädierst","plädiert"],varieties:[{variant:"plädieren + für",prepositions:["für"],explanation:"To argue for.",examples:["Er plädiert für mehr Toleranz."]}]},
  {base:"eintreten",past:"trat ein",participle:"eingetreten",translations:["to enter","to advocate"],derived:["trete ein","trittst ein","tritt ein"],varieties:[{variant:"eintreten + für",prepositions:["für"],explanation:"To advocate for.",examples:["Sie tritt für Frauenrechte ein."]}]},
  {base:"sich stark machen",past:"machte sich stark",participle:"sich stark gemacht",translations:["to advocate"],derived:["mache mich stark","machst dich stark","macht sich stark"],varieties:[{variant:"sich stark machen + für",prepositions:["für"],explanation:"To advocate strongly for.",examples:["Er macht sich stark für den Umweltschutz."]}]},
  {base:"einsetzen",past:"setzte ein",participle:"eingesetzt",translations:["to deploy","to advocate"],derived:["setze ein","setzt ein","setzt ein"],varieties:[{variant:"sich einsetzen + für",prepositions:["für"],explanation:"To commit oneself to.",examples:["Ich setze mich für diese Sache ein."]}]},
  {base:"engagieren",past:"engagierte",participle:"engagiert",translations:["to hire","to engage"],derived:["engagiere","engagierst","engagiert"],varieties:[{variant:"sich engagieren + für",prepositions:["für"],explanation:"To commit oneself to.",examples:["Sie engagiert sich für Kinder."]}]},
  {base:"verpflichten",past:"verpflichtete",participle:"verpflichtet",translations:["to oblige","to commit"],derived:["verpflichte","verpflichtest","verpflichtet"],varieties:[{variant:"sich verpflichten",explanation:"Reflexive: to commit oneself.",examples:["Ich verpflichte mich dazu."]}]},
  {base:"binden",past:"band",participle:"gebunden",translations:["to bind","to tie"],derived:["binde","bindest","bindet"],varieties:[{variant:"sich binden + an",prepositions:["an"],explanation:"To commit to.",examples:["Er bindet sich an das Unternehmen."]}]},
  {base:"fesseln",past:"fesselte",participle:"gefesselt",translations:["to captivate","to tie up"],derived:["fessle","fesselst","fesselt"],varieties:[]},
  {base:"bezaubern",past:"bezauberte",participle:"bezaubert",translations:["to enchant"],derived:["bezaubere","bezauberst","bezaubert"],varieties:[]},
  {base:"verzaubern",past:"verzauberte",participle:"verzaubert",translations:["to enchant","to bewitch"],derived:["verzaubere","verzauberst","verzaubert"],varieties:[]},
  {base:"verhexen",past:"verhexte",participle:"verhext",translations:["to bewitch"],derived:["verhexe","verhext","verhext"],varieties:[]},
  {base:"bannen",past:"bannte",participle:"gebannt",translations:["to captivate","to ban"],derived:["banne","bannst","bannt"],varieties:[]},
  {base:"in Bann ziehen",past:"zog in Bann",participle:"in Bann gezogen",translations:["to captivate"],derived:["ziehe in Bann","ziehst in Bann","zieht in Bann"],varieties:[]},
  {base:"faszinieren",past:"faszinierte",participle:"fasziniert",translations:["to fascinate"],derived:["fasziniere","faszinierst","fasziniert"],varieties:[]},
  {base:"beeindrucken",past:"beeindruckte",participle:"beeindruckt",translations:["to impress"],derived:["beeindrucke","beeindruckst","beeindruckt"],varieties:[]},
  {base:"imponieren",past:"imponierte",participle:"imponiert",translations:["to impress"],derived:["imponiere","imponierst","imponiert"],varieties:[]},
  {base:"einschüchtern",past:"schüchterte ein",participle:"eingeschüchtert",translations:["to intimidate"],derived:["schüchtere ein","schüchterst ein","schüchtert ein"],varieties:[]},
  {base:"abschrecken",past:"schreckte ab",participle:"abgeschreckt",translations:["to deter","to scare off"],derived:["schrecke ab","schreckst ab","schreckt ab"],varieties:[]},
  {base:"zurückschrecken",past:"schreckte zurück",participle:"zurückgeschreckt",translations:["to shrink back"],derived:["schrecke zurück","schreckst zurück","schreckt zurück"],varieties:[{variant:"zurückschrecken + vor",prepositions:["vor"],explanation:"To shrink from.",examples:["Er schreckt vor nichts zurück."]}]},
  {base:"scheuen",past:"scheute",participle:"gescheut",translations:["to shy away from"],derived:["scheue","scheust","scheut"],varieties:[{variant:"sich scheuen + vor",prepositions:["vor"],explanation:"To be reluctant.",examples:["Ich scheue mich nicht vor der Aufgabe."]}]},
  {base:"zögern",past:"zögerte",participle:"gezögert",translations:["to hesitate"],derived:["zögere","zögerst","zögert"],varieties:[]},
  {base:"zaudern",past:"zauderte",participle:"gezaudert",translations:["to hesitate","to waver"],derived:["zaudere","zauderst","zaudert"],varieties:[]},
  {base:"schwanken",past:"schwankte",participle:"geschwankt",translations:["to waver","to fluctuate"],derived:["schwanke","schwankst","schwankt"],varieties:[]},
  {base:"oszillieren",past:"oszillierte",participle:"oszilliert",translations:["to oscillate"],derived:["oszilliere","oszillierst","oszilliert"],varieties:[]},
  {base:"fluktuieren",past:"fluktuierte",participle:"fluktuiert",translations:["to fluctuate"],derived:["fluktuiere","fluktuierst","fluktuiert"],varieties:[]},
  {base:"pendeln",past:"pendelte",participle:"gependelt",translations:["to commute","to oscillate"],derived:["pendle","pendelst","pendelt"],varieties:[]},
  {base:"alternieren",past:"alternierte",participle:"alterniert",translations:["to alternate"],derived:["alterniere","alternierst","alterniert"],varieties:[]},
  {base:"abwechseln",past:"wechselte ab",participle:"abgewechselt",translations:["to alternate"],derived:["wechsle ab","wechselst ab","wechselt ab"],varieties:[{variant:"sich abwechseln",explanation:"Reflexive: to take turns.",examples:["Wir wechseln uns ab."]}]},
  {base:"rotieren",past:"rotierte",participle:"rotiert",translations:["to rotate"],derived:["rotiere","rotierst","rotiert"],varieties:[]},
  {base:"kreisen",past:"kreiste",participle:"gekreist",translations:["to circle","to revolve"],derived:["kreise","kreist","kreist"],varieties:[]},
  {base:"umkreisen",past:"umkreiste",participle:"umkreist",translations:["to orbit","to circle"],derived:["umkreise","umkreist","umkreist"],varieties:[]},
  {base:"zirkulieren",past:"zirkulierte",participle:"zirkuliert",translations:["to circulate"],derived:["zirkuliere","zirkulierst","zirkuliert"],varieties:[]},
  {base:"kursieren",past:"kursierte",participle:"kursiert",translations:["to circulate"],derived:["kursiere","kursierst","kursiert"],varieties:[]},
  {base:"umlaufen",past:"lief um",participle:"umgelaufen",translations:["to circulate","to orbit"],derived:["laufe um","läufst um","läuft um"],varieties:[]},
  {base:"umgehen",past:"ging um",participle:"umgegangen",translations:["to circulate","to bypass"],derived:["gehe um","gehst um","geht um"],varieties:[]},
  {base:"umrunden",past:"umrundete",participle:"umrundet",translations:["to circle","to round"],derived:["umrunde","umrundest","umrundet"],varieties:[]},
  {base:"umschiffen",past:"umschiffte",participle:"umschifft",translations:["to circumnavigate","to avoid"],derived:["umschiffe","umschiffst","umschifft"],varieties:[]},
  {base:"umsegeln",past:"umsegelte",participle:"umsegelt",translations:["to sail around"],derived:["umsegele","umsegelst","umsegelt"],varieties:[]},
  {base:"umfahren",past:"umfuhr",participle:"umfahren",translations:["to drive around","to knock down"],derived:["umfahre","umfährst","umfährt"],varieties:[]},
  {base:"umgehen",past:"umging",participle:"umgangen",translations:["to bypass","to evade"],derived:["umgehe","umgehst","umgeht"],varieties:[]},
  {base:"überspringen",past:"übersprang",participle:"übersprungen",translations:["to skip","to jump over"],derived:["überspringe","überspringst","überspringt"],varieties:[]},
  {base:"auslassen",past:"ließ aus",participle:"ausgelassen",translations:["to omit","to skip"],derived:["lasse aus","lässt aus","lässt aus"],varieties:[]},
  {base:"weglassen",past:"ließ weg",participle:"weggelassen",translations:["to omit"],derived:["lasse weg","lässt weg","lässt weg"],varieties:[]},
  {base:"überspringen",past:"übersprang",participle:"übersprungen",translations:["to skip"],derived:["überspringe","überspringst","überspringt"],varieties:[]},
  {base:"überschlagen",past:"überschlug",participle:"überschlagen",translations:["to skip","to estimate"],derived:["überschlage","überschlägst","überschlägt"],varieties:[]},
  {base:"überfliegen",past:"überflog",participle:"überflogen",translations:["to skim","to fly over"],derived:["überfliege","überfliegst","überfliegt"],varieties:[]}
];

export default verbsC1;
