// verbs-db-a2.js - A2 Level - 200 verbs

const verbsA2 = [
  {base:"beginnen",past:"begann",participle:"begonnen",translations:["to begin","to start"],derived:["beginne","beginnst","beginnt","beginnen"],varieties:[{variant:"beginnen + mit",prepositions:["mit"],explanation:"To start with something.",examples:["Der Kurs beginnt mit einer Einführung.","Ich beginne mit der Arbeit."]}]},
  {base:"arbeiten",past:"arbeitete",participle:"gearbeitet",translations:["to work"],derived:["arbeite","arbeitest","arbeitet","arbeiten"],varieties:[{variant:"arbeiten + bei",prepositions:["bei"],explanation:"To work at a company.",examples:["Ich arbeite bei Siemens."]},{variant:"arbeiten + als",prepositions:["als"],explanation:"To work as something.",examples:["Er arbeitet als Lehrer."]}]},
  {base:"sprechen",past:"sprach",participle:"gesprochen",translations:["to speak"],derived:["spreche","sprichst","spricht","sprechen"],varieties:[{variant:"sprechen + mit",prepositions:["mit"],explanation:"To speak with someone.",examples:["Ich spreche mit dir."]},{variant:"sprechen + über",prepositions:["über"],explanation:"To talk about something.",examples:["Wir sprechen über das Wetter."]}]},
  {base:"verstehen",past:"verstand",participle:"verstanden",translations:["to understand"],derived:["verstehe","verstehst","versteht","verstehen"],varieties:[]},
  {base:"bekommen",past:"bekam",participle:"bekommen",translations:["to get","to receive"],derived:["bekomme","bekommst","bekommt","bekommen"],varieties:[{variant:"bekommen + von",prepositions:["von"],explanation:"To receive from someone.",examples:["Ich bekomme Post von dir."]}]},
  {base:"bringen",past:"brachte",participle:"gebracht",translations:["to bring"],derived:["bringe","bringst","bringt","bringen"],varieties:[{variant:"mitbringen",prepositions:[],explanation:"Separable: to bring along.",examples:["Bring deine Freunde mit!"]}]},
  {base:"warten",past:"wartete",participle:"gewartet",translations:["to wait"],derived:["warte","wartest","wartet","warten"],varieties:[{variant:"warten + auf",prepositions:["auf"],explanation:"To wait for something.",examples:["Ich warte auf den Bus."]}]},
  {base:"finden",past:"fand",participle:"gefunden",translations:["to find"],derived:["finde","findest","findet","finden"],varieties:[]},
  {base:"suchen",past:"suchte",participle:"gesucht",translations:["to search"],derived:["suche","suchst","sucht","suchen"],varieties:[{variant:"suchen + nach",prepositions:["nach"],explanation:"To search for something.",examples:["Ich suche nach meinem Handy."]}]},
  {base:"fahren",past:"fuhr",participle:"gefahren",translations:["to drive","to go by vehicle"],derived:["fahre","fährst","fährt","fahren"],varieties:[{variant:"fahren + nach",prepositions:["nach"],explanation:"To drive to a place.",examples:["Ich fahre nach Berlin."]},{variant:"abfahren",prepositions:[],explanation:"Separable: to depart.",examples:["Der Zug fährt ab."]}]},
  {base:"aufstehen",past:"stand auf",participle:"aufgestanden",translations:["to get up"],derived:["stehe auf","stehst auf","steht auf"],varieties:[]},
  {base:"umziehen",past:"zog um",participle:"umgezogen",translations:["to move house"],derived:["ziehe um","ziehst um","zieht um"],varieties:[]},
  {base:"anziehen",past:"zog an",participle:"angezogen",translations:["to put on clothes","to dress"],derived:["ziehe an","ziehst an","zieht an"],varieties:[]},
  {base:"ausziehen",past:"zog aus",participle:"ausgezogen",translations:["to take off clothes","to move out"],derived:["ziehe aus","ziehst aus","zieht aus"],varieties:[]},
  {base:"einziehen",past:"zog ein",participle:"eingezogen",translations:["to move in"],derived:["ziehe ein","ziehst ein","zieht ein"],varieties:[]},
  {base:"laufen",past:"lief",participle:"gelaufen",translations:["to run","to walk"],derived:["laufe","läufst","läuft","laufen"],varieties:[]},
  {base:"rennen",past:"rannte",participle:"gerannt",translations:["to run fast"],derived:["renne","rennst","rennt","rennen"],varieties:[]},
  {base:"springen",past:"sprang",participle:"gesprungen",translations:["to jump"],derived:["springe","springst","springt","springen"],varieties:[]},
  {base:"fallen",past:"fiel",participle:"gefallen",translations:["to fall"],derived:["falle","fällst","fällt","fallen"],varieties:[]},
  {base:"steigen",past:"stieg",participle:"gestiegen",translations:["to climb","to rise"],derived:["steige","steigst","steigt","steigen"],varieties:[{variant:"einsteigen",prepositions:[],explanation:"Separable: to board.",examples:["Steig ein!"]}]},
  {base:"fliegen",past:"flog",participle:"geflogen",translations:["to fly"],derived:["fliege","fliegst","fliegt","fliegen"],varieties:[]},
  {base:"schwimmen",past:"schwamm",participle:"geschwommen",translations:["to swim"],derived:["schwimme","schwimmst","schwimmt","schwimmen"],varieties:[{variant:"schwimmen + in",prepositions:["in"],explanation:"To swim in something.",examples:["Ich schwimme im Meer."]}]},
  {base:"tauchen",past:"tauchte",participle:"getaucht",translations:["to dive"],derived:["tauche","tauchst","taucht","tauchen"],varieties:[]},
  {base:"segeln",past:"segelte",participle:"gesegelt",translations:["to sail"],derived:["segle","segelst","segelt","segeln"],varieties:[]},
  {base:"rudern",past:"ruderte",participle:"gerudert",translations:["to row"],derived:["rudere","ruderst","rudert","rudern"],varieties:[]},
  {base:"klettern",past:"kletterte",participle:"geklettert",translations:["to climb"],derived:["klettere","kletterst","klettert","klettern"],varieties:[]},
  {base:"wandern",past:"wanderte",participle:"gewandert",translations:["to hike"],derived:["wandere","wanderst","wandert","wandern"],varieties:[]},
  {base:"joggen",past:"joggte",participle:"gejoggt",translations:["to jog"],derived:["jogge","joggst","joggt","joggen"],varieties:[]},
  {base:"trainieren",past:"trainierte",participle:"trainiert",translations:["to train"],derived:["trainiere","trainierst","trainiert","trainieren"],varieties:[]},
  {base:"üben",past:"übte",participle:"geübt",translations:["to practice"],derived:["übe","übst","übt","üben"],varieties:[]},
  {base:"spielen",past:"spielte",participle:"gespielt",translations:["to play"],derived:["spiele","spielst","spielt","spielen"],varieties:[{variant:"spielen + Akkusativ",prepositions:[],explanation:"To play a game or instrument.",examples:["Ich spiele Fußball.","Er spielt Gitarre."]}]},
  {base:"tanzen",past:"tanzte",participle:"getanzt",translations:["to dance"],derived:["tanze","tanzt","tanzt","tanzen"],varieties:[]},
  {base:"singen",past:"sang",participle:"gesungen",translations:["to sing"],derived:["singe","singst","singt","singen"],varieties:[]},
  {base:"malen",past:"malte",participle:"gemalt",translations:["to paint"],derived:["male","malst","malt","malen"],varieties:[]},
  {base:"zeichnen",past:"zeichnete",participle:"gegezeichnet",translations:["to draw"],derived:["zeichne","zeichnest","zeichnet","zeichnen"],varieties:[]},
  {base:"fotografieren",past:"fotografierte",participle:"fotografiert",translations:["to photograph"],derived:["fotografiere","fotografierst","fotografiert","fotografieren"],varieties:[]},
  {base:"filmen",past:"filmte",participle:"gefilmt",translations:["to film"],derived:["filme","filmst","filmt","filmen"],varieties:[]},
  {base:"basteln",past:"bastelte",participle:"gebastelt",translations:["to craft","to tinker"],derived:["bastle","bastelst","bastelt","basteln"],varieties:[]},
  {base:"nähen",past:"nähte",participle:"genäht",translations:["to sew"],derived:["nähe","nähst","näht","nähen"],varieties:[]},
  {base:"stricken",past:"strickte",participle:"gestrickt",translations:["to knit"],derived:["stricke","strickst","strickt","stricken"],varieties:[]},
  {base:"häkeln",past:"häkelte",participle:"gehäkelt",translations:["to crochet"],derived:["häkle","häkelst","häkelt","häkeln"],varieties:[]},
  {base:"sammeln",past:"sammelte",participle:"gesammelt",translations:["to collect"],derived:["sammle","sammelst","sammelt","sammeln"],varieties:[]},
  {base:"organisieren",past:"organisierte",participle:"organisiert",translations:["to organize"],derived:["organisiere","organisierst","organisiert","organisieren"],varieties:[]},
  {base:"planen",past:"plante",participle:"geplant",translations:["to plan"],derived:["plane","planst","plant","planen"],varieties:[]},
  {base:"vorbereiten",past:"bereitete vor",participle:"vorbereitet",translations:["to prepare"],derived:["bereite vor","bereitest vor","bereitet vor"],varieties:[{variant:"sich vorbereiten + auf",prepositions:["auf"],explanation:"To prepare for something.",examples:["Ich bereite mich auf die Prüfung vor."]}]},
  {base:"bestellen",past:"bestellte",participle:"bestellt",translations:["to order"],derived:["bestelle","bestellst","bestellt","bestellen"],varieties:[]},
  {base:"reservieren",past:"reservierte",participle:"reserviert",translations:["to reserve"],derived:["reserviere","reservierst","reserviert","reservieren"],varieties:[]},
  {base:"buchen",past:"buchte",participle:"gebucht",translations:["to book"],derived:["buche","buchst","bucht","buchen"],varieties:[]},
  {base:"packen",past:"packte",participle:"gepackt",translations:["to pack"],derived:["packe","packst","packt","packen"],varieties:[]},
  {base:"auspacken",past:"packte aus",participle:"ausgepackt",translations:["to unpack"],derived:["packe aus","packst aus","packt aus"],varieties:[]},
  {base:"mieten",past:"mietete",participle:"gemietet",translations:["to rent"],derived:["miete","mietest","mietet","mieten"],varieties:[]},
  {base:"vermieten",past:"vermietete",participle:"vermietet",translations:["to rent out"],derived:["vermiete","vermietest","vermietet","vermieten"],varieties:[]},
  {base:"wechseln",past:"wechselte",participle:"gewechselt",translations:["to change","to exchange"],derived:["wechsle","wechselst","wechselt","wechseln"],varieties:[]},
  {base:"tauschen",past:"tauschte",participle:"getauscht",translations:["to exchange","to swap"],derived:["tausche","tauschst","tauscht","tauschen"],varieties:[]},
  {base:"vergleichen",past:"verglich",participle:"verglichen",translations:["to compare"],derived:["vergleiche","vergleichst","vergleicht","vergleichen"],varieties:[{variant:"vergleichen + mit",prepositions:["mit"],explanation:"To compare with something.",examples:["Vergleich die Preise!"]}]},
  {base:"messen",past:"maß",participle:"gemessen",translations:["to measure"],derived:["messe","misst","misst","messen"],varieties:[]},
  {base:"zählen",past:"zählte",participle:"gezählt",translations:["to count"],derived:["zähle","zählst","zählt","zählen"],varieties:[]},
  {base:"rechnen",past:"rechnete",participle:"gerechnet",translations:["to calculate"],derived:["rechne","rechnest","rechnet","rechnen"],varieties:[]},
  {base:"lösen",past:"löste",participle:"gelöst",translations:["to solve"],derived:["löse","löst","löst","lösen"],varieties:[]},
  {base:"erklären",past:"erklärte",participle:"erklärt",translations:["to explain"],derived:["erkläre","erklärst","erklärt","erklären"],varieties:[]},
  {base:"beschreiben",past:"beschrieb",participle:"beschrieben",translations:["to describe"],derived:["beschreibe","beschreibst","beschreibt","beschreiben"],varieties:[]},
  {base:"nennen",past:"nannte",participle:"genannt",translations:["to name","to call"],derived:["nenne","nennst","nennt","nennen"],varieties:[]},
  {base:"bedeuten",past:"bedeutete",participle:"bedeutet",translations:["to mean"],derived:["bedeute","bedeutest","bedeutet","bedeuten"],varieties:[]},
  {base:"beweisen",past:"bewies",participle:"bewiesen",translations:["to prove"],derived:["beweise","beweist","beweist","beweisen"],varieties:[]},
  {base:"demonstrieren",past:"demonstrierte",participle:"demonstriert",translations:["to demonstrate"],derived:["demonstriere","demonstrierst","demonstriert","demonstrieren"],varieties:[]},
  {base:"präsentieren",past:"präsentierte",participle:"präsentiert",translations:["to present"],derived:["präsentiere","präsentierst","präsentiert","präsentieren"],varieties:[]},
  {base:"darstellen",past:"stellte dar",participle:"dargestellt",translations:["to represent"],derived:["stelle dar","stellst dar","stellt dar"],varieties:[]},
  {base:"erscheinen",past:"erschien",participle:"erschienen",translations:["to appear"],derived:["erscheine","erscheinst","erscheint","erscheinen"],varieties:[]},
  {base:"verschwinden",past:"verschwand",participle:"verschwunden",translations:["to disappear"],derived:["verschwinde","verschwindest","verschwindet","verschwinden"],varieties:[]},
  {base:"entstehen",past:"entstand",participle:"entstanden",translations:["to arise","to emerge"],derived:["entstehe","entstehst","entsteht","entstehen"],varieties:[]},
  {base:"wachsen",past:"wuchs",participle:"gewachsen",translations:["to grow"],derived:["wachse","wächst","wächst","wachsen"],varieties:[]},
  {base:"zunehmen",past:"nahm zu",participle:"zugenommen",translations:["to increase"],derived:["nehme zu","nimmst zu","nimmt zu"],varieties:[]},
  {base:"abnehmen",past:"nahm ab",participle:"abgenommen",translations:["to decrease","to lose weight"],derived:["nehme ab","nimmst ab","nimmt ab"],varieties:[]},
  {base:"steigen",past:"stieg",participle:"gestiegen",translations:["to rise"],derived:["steige","steigst","steigt","steigen"],varieties:[]},
  {base:"sinken",past:"sank",participle:"gesunken",translations:["to sink"],derived:["sinke","sinkst","sinkt","sinken"],varieties:[]},
  {base:"verbessern",past:"verbesserte",participle:"verbessert",translations:["to improve"],derived:["verbessere","verbesserst","verbessert","verbessern"],varieties:[]},
  {base:"verschlechtern",past:"verschlechterte",participle:"verschlechtert",translations:["to worsen"],derived:["verschlechtere","verschlechterst","verschlechtert","verschlechtern"],varieties:[]},
  {base:"erhöhen",past:"erhöhte",participle:"erhöht",translations:["to increase","to raise"],derived:["erhöhe","erhöhst","erhöht","erhöhen"],varieties:[]},
  {base:"senken",past:"senkte",participle:"gesenkt",translations:["to lower"],derived:["senke","senkst","senkt","senken"],varieties:[]},
  {base:"reduzieren",past:"reduzierte",participle:"reduziert",translations:["to reduce"],derived:["reduziere","reduzierst","reduziert","reduzieren"],varieties:[]},
  {base:"erweitern",past:"erweiterte",participle:"erweitert",translations:["to expand"],derived:["erweitere","erweiterst","erweitert","erweitern"],varieties:[]},
  {base:"verringern",past:"verringerte",participle:"verringert",translations:["to decrease"],derived:["verringere","verringerst","verringert","verringern"],varieties:[]},
  {base:"verstärken",past:"verstärkte",participle:"verstärkt",translations:["to strengthen"],derived:["verstärke","verstärkst","verstärkt","verstärken"],varieties:[]},
  {base:"schwächen",past:"schwächte",participle:"geschwächt",translations:["to weaken"],derived:["schwäche","schwächst","schwächt","schwächen"],varieties:[]},
  {base:"fördern",past:"förderte",participle:"gefördert",translations:["to promote","to support"],derived:["fördere","förderst","fördert","fördern"],varieties:[]},
  {base:"hindern",past:"hinderte",participle:"gehindert",translations:["to hinder"],derived:["hindere","hinderst","hindert","hindern"],varieties:[{variant:"hindern + an",prepositions:["an"],explanation:"To hinder from something.",examples:["Nichts hindert mich daran."]}]},
  {base:"erlauben",past:"erlaubte",participle:"erlaubt",translations:["to allow"],derived:["erlaube","erlaubst","erlaubt","erlauben"],varieties:[]},
  {base:"verbieten",past:"verbot",participle:"verboten",translations:["to forbid"],derived:["verbiete","verbietest","verbietet","verbieten"],varieties:[]},
  {base:"zwingen",past:"zwang",participle:"gezwungen",translations:["to force"],derived:["zwinge","zwingst","zwingt","zwingen"],varieties:[{variant:"zwingen + zu",prepositions:["zu"],explanation:"To force to do something.",examples:["Niemand zwingt dich dazu."]}]},
  {base:"bitten",past:"bat",participle:"gebeten",translations:["to ask","to request"],derived:["bitte","bittest","bittet","bitten"],varieties:[{variant:"bitten + um",prepositions:["um"],explanation:"To ask for something.",examples:["Ich bitte um Hilfe."]}]},
  {base:"fordern",past:"forderte",participle:"gefordert",translations:["to demand"],derived:["fordere","forderst","fordert","fordern"],varieties:[]},
  {base:"verlangen",past:"verlangte",participle:"verlangt",translations:["to demand","to require"],derived:["verlange","verlangst","verlangt","verlangen"],varieties:[]},
  {base:"anbieten",past:"bot an",participle:"angeboten",translations:["to offer"],derived:["biete an","bietest an","bietet an"],varieties:[]},
  {base:"vorschlagen",past:"schlug vor",participle:"vorgeschlagen",translations:["to suggest"],derived:["schlage vor","schlägst vor","schlägt vor"],varieties:[]},
  {base:"empfehlen",past:"empfahl",participle:"empfohlen",translations:["to recommend"],derived:["empfehle","empfiehlst","empfiehlt","empfehlen"],varieties:[]},
  {base:"raten",past:"riet",participle:"geraten",translations:["to advise"],derived:["rate","rätst","rät","raten"],varieties:[{variant:"raten + zu",prepositions:["zu"],explanation:"To advise to do something.",examples:["Ich rate dir dazu."]}]},
  {base:"warnen",past:"warnte",participle:"gewarnt",translations:["to warn"],derived:["warne","warnst","warnt","warnen"],varieties:[{variant:"warnen + vor",prepositions:["vor"],explanation:"To warn about something.",examples:["Ich warne dich vor ihm."]}]},
  {base:"drohen",past:"drohte",participle:"gedroht",translations:["to threaten"],derived:["drohe","drohst","droht","drohen"],varieties:[{variant:"drohen + mit",prepositions:["mit"],explanation:"To threaten with something.",examples:["Er droht mit Konsequenzen."]}]},
  {base:"versprechen",past:"versprach",participle:"versprochen",translations:["to promise"],derived:["verspreche","versprichst","verspricht","versprechen"],varieties:[]},
  {base:"schwören",past:"schwor",participle:"geschworen",translations:["to swear"],derived:["schwöre","schwörst","schwört","schwören"],varieties:[]},
  {base:"garantieren",past:"garantierte",participle:"garantiert",translations:["to guarantee"],derived:["garantiere","garantierst","garantiert","garantieren"],varieties:[]},
  {base:"bestätigen",past:"bestätigte",participle:"bestätigt",translations:["to confirm"],derived:["bestätige","bestätigst","bestätigt","bestätigen"],varieties:[]},
  {base:"leugnen",past:"leugnete",participle:"geleugnet",translations:["to deny"],derived:["leugne","leugnest","leugnet","leugnen"],varieties:[]},
  {base:"zugeben",past:"gab zu",participle:"zugegeben",translations:["to admit"],derived:["gebe zu","gibst zu","gibt zu"],varieties:[]},
  {base:"gestehen",past:"gestand",participle:"gestanden",translations:["to confess"],derived:["gestehe","gestehst","gesteht","gestehen"],varieties:[]},
  {base:"lügen",past:"log",participle:"gelogen",translations:["to lie"],derived:["lüge","lügst","lügt","lügen"],varieties:[]},
  {base:"täuschen",past:"täuschte",participle:"getäuscht",translations:["to deceive"],derived:["täusche","täuschst","täuscht","täuschen"],varieties:[]},
  {base:"betrügen",past:"betrog",participle:"betrogen",translations:["to cheat"],derived:["betrüge","betrügst","betrügt","betrügen"],varieties:[]},
  {base:"stehlen",past:"stahl",participle:"gestohlen",translations:["to steal"],derived:["stehle","stiehlst","stiehlt","stehlen"],varieties:[]},
  {base:"rauben",past:"raubte",participle:"geraubt",translations:["to rob"],derived:["raube","raubst","raubt","rauben"],varieties:[]},
  {base:"entdecken",past:"entdeckte",participle:"entdeckt",translations:["to discover"],derived:["entdecke","entdeckst","entdeckt","entdecken"],varieties:[]},
  {base:"erfinden",past:"erfand",participle:"erfunden",translations:["to invent"],derived:["erfinde","erfindest","erfindet","erfinden"],varieties:[]},
  {base:"prüfen",past:"prüfte",participle:"geprüft",translations:["to test","to examine"],derived:["prüfe","prüfst","prüft","prüfen"],varieties:[]},
  {base:"testen",past:"testete",participle:"getestet",translations:["to test"],derived:["teste","testest","testet","testen"],varieties:[]},
  {base:"untersuchen",past:"untersuchte",participle:"untersucht",translations:["to examine","to investigate"],derived:["untersuche","untersuchst","untersucht","untersuchen"],varieties:[]},
  {base:"forschen",past:"forschte",participle:"geforscht",translations:["to research"],derived:["forsche","forschst","forscht","forschen"],varieties:[]},
  {base:"experimentieren",past:"experimentierte",participle:"experimentiert",translations:["to experiment"],derived:["experimentiere","experimentierst","experimentiert","experimentieren"],varieties:[{variant:"experimentieren + mit",prepositions:["mit"],explanation:"To experiment with something.",examples:["Wir experimentieren mit neuen Methoden."]}]},
  {base:"analysieren",past:"analysierte",participle:"analysiert",translations:["to analyze"],derived:["analysiere","analysierst","analysiert","analysieren"],varieties:[]},
  {base:"beobachten",past:"beobachtete",participle:"beobachtet",translations:["to observe"],derived:["beobachte","beobachtest","beobachtet","beobachten"],varieties:[]},
  {base:"betrachten",past:"betrachtete",participle:"betrachtet",translations:["to consider","to look at"],derived:["betrachte","betrachtest","betrachtet","betrachten"],varieties:[]},
  {base:"blicken",past:"blickte",participle:"geblickt",translations:["to look","to glance"],derived:["blicke","blickst","blickt","blicken"],varieties:[{variant:"blicken + auf",prepositions:["auf"],explanation:"To look at something.",examples:["Ich blicke auf das Meer."]}]},
  {base:"starren",past:"starrte",participle:"gestarrt",translations:["to stare"],derived:["starre","starrst","starrt","starren"],varieties:[{variant:"starren + auf",prepositions:["auf"],explanation:"To stare at something.",examples:["Er starrt auf den Bildschirm."]}]},
  {base:"schauen",past:"schaute",participle:"geschaut",translations:["to look"],derived:["schaue","schaust","schaut","schauen"],varieties:[]},
  {base:"gucken",past:"guckte",participle:"geguckt",translations:["to look (informal)"],derived:["gucke","guckst","guckt","gucken"],varieties:[]},
  {base:"übersehen",past:"übersah",participle:"übersehen",translations:["to overlook"],derived:["übersehe","übersiehst","übersieht","übersehen"],varieties:[]},
  {base:"erkennen",past:"erkannte",participle:"erkannt",translations:["to recognize"],derived:["erkenne","erkennst","erkennt","erkennen"],varieties:[]},
  {base:"identifizieren",past:"identifizierte",participle:"identifiziert",translations:["to identify"],derived:["identifiziere","identifizierst","identifiziert","identifizieren"],varieties:[]},
  {base:"unterscheiden",past:"unterschied",participle:"unterschieden",translations:["to distinguish"],derived:["unterscheide","unterscheidest","unterscheidet","unterscheiden"],varieties:[{variant:"unterscheiden + zwischen",prepositions:["zwischen"],explanation:"To distinguish between things.",examples:["Ich unterscheide zwischen gut und schlecht."]}]},
  {base:"verwechseln",past:"verwechselte",participle:"verwechselt",translations:["to confuse","to mix up"],derived:["verwechsle","verwechselst","verwechselt","verwechseln"],varieties:[{variant:"verwechseln + mit",prepositions:["mit"],explanation:"To confuse with something.",examples:["Ich verwechsle dich mit deinem Bruder."]}]},
  {base:"akzeptieren",past:"akzeptierte",participle:"akzeptiert",translations:["to accept"],derived:["akzeptiere","akzeptierst","akzeptiert","akzeptieren"],varieties:[]},
  {base:"annehmen",past:"nahm an",participle:"angenommen",translations:["to accept","to assume"],derived:["nehme an","nimmst an","nimmt an"],varieties:[]},
  {base:"ablehnen",past:"lehnte ab",participle:"abgelehnt",translations:["to reject"],derived:["lehne ab","lehnst ab","lehnt ab"],varieties:[]},
  {base:"zurückweisen",past:"wies zurück",participle:"zurückgewiesen",translations:["to reject"],derived:["weise zurück","weist zurück","weist zurück"],varieties:[]},
  {base:"widersprechen",past:"widersprach",participle:"widersprochen",translations:["to contradict"],derived:["widerspreche","widersprichst","widerspricht","widersprechen"],varieties:[]},
  {base:"zustimmen",past:"stimmte zu",participle:"zugestimmt",translations:["to agree"],derived:["stimme zu","stimmst zu","stimmt zu"],varieties:[]},
  {base:"protestieren",past:"protestierte",participle:"protestiert",translations:["to protest"],derived:["protestiere","protestierst","protestiert","protestieren"],varieties:[{variant:"protestieren + gegen",prepositions:["gegen"],explanation:"To protest against something.",examples:["Sie protestieren gegen die Regierung."]}]},
  {base:"streiken",past:"streikte",participle:"gestreikt",translations:["to strike"],derived:["streike","streikst","streikt","streiken"],varieties:[]},
  {base:"kämpfen",past:"kämpfte",participle:"gekämpft",translations:["to fight"],derived:["kämpfe","kämpfst","kämpft","kämpfen"],varieties:[{variant:"kämpfen + für",prepositions:["für"],explanation:"To fight for something.",examples:["Wir kämpfen für Gerechtigkeit."]},{variant:"kämpfen + gegen",prepositions:["gegen"],explanation:"To fight against something.",examples:["Sie kämpfen gegen die Krankheit."]}]},
  {base:"siegen",past:"siegte",participle:"gesiegt",translations:["to win","to triumph"],derived:["siege","siegst","siegt","siegen"],varieties:[{variant:"siegen + über",prepositions:["über"],explanation:"To triumph over someone.",examples:["Sie siegten über den Gegner."]}]},
  {base:"verlieren",past:"verlor",participle:"verloren",translations:["to lose"],derived:["verliere","verlierst","verliert","verlieren"],varieties:[]},
  {base:"gewinnen",past:"gewann",participle:"gewonnen",translations:["to win"],derived:["gewinne","gewinnst","gewinnt","gewinnen"],varieties:[]},
  {base:"verdienen",past:"verdiente",participle:"verdient",translations:["to earn","to deserve"],derived:["verdiene","verdienst","verdient","verdienen"],varieties:[]},
  {base:"sparen",past:"sparte",participle:"gespart",translations:["to save (money)"],derived:["spare","sparst","spart","sparen"],varieties:[]},
  {base:"ausgeben",past:"gab aus",participle:"ausgegeben",translations:["to spend"],derived:["gebe aus","gibst aus","gibt aus"],varieties:[{variant:"ausgeben + für",prepositions:["für"],explanation:"To spend on something.",examples:["Ich gebe viel Geld für Bücher aus."]}]},
  {base:"investieren",past:"investierte",participle:"investiert",translations:["to invest"],derived:["investiere","investierst","investiert","investieren"],varieties:[{variant:"investieren + in",prepositions:["in"],explanation:"To invest in something.",examples:["Wir investieren in Bildung."]}]},
  {base:"leihen",past:"lieh",participle:"geliehen",translations:["to lend","to borrow"],derived:["leihe","leihst","leiht","leihen"],varieties:[]},
  {base:"borgen",past:"borgte",participle:"geborgt",translations:["to borrow"],derived:["borge","borgst","borgt","borgen"],varieties:[{variant:"borgen + von",prepositions:["von"],explanation:"To borrow from someone.",examples:["Ich borge Geld von meinem Freund."]}]},
  {base:"schulden",past:"schuldete",participle:"geschuldet",translations:["to owe"],derived:["schulde","schuldest","schuldet","schulden"],varieties:[]},
  {base:"zurückzahlen",past:"zahlte zurück",participle:"zurückgezahlt",translations:["to pay back"],derived:["zahle zurück","zahlst zurück","zahlt zurück"],varieties:[]},
  {base:"besitzen",past:"besaß",participle:"besessen",translations:["to own"],derived:["besitze","besitzt","besitzt","besitzen"],varieties:[]},
  {base:"gehören",past:"gehörte",participle:"gehört",translations:["to belong"],derived:["gehöre","gehörst","gehört","gehören"],varieties:[]},
  {base:"besichtigen",past:"besichtigte",participle:"besichtigt",translations:["to visit","to view"],derived:["besichtige","besichtigst","besichtigt","besichtigen"],varieties:[]},
  {base:"erkunden",past:"erkundete",participle:"erkundet",translations:["to explore"],derived:["erkunde","erkundest","erkundet","erkunden"],varieties:[]},
  {base:"reisen",past:"reiste",participle:"gereist",translations:["to travel"],derived:["reise","reist","reist","reisen"],varieties:[]},
  {base:"zurückkehren",past:"kehrte zurück",participle:"zurückgekehrt",translations:["to return"],derived:["kehre zurück","kehrst zurück","kehrt zurück"],varieties:[]},
  {base:"abreisen",past:"reiste ab",participle:"abgereist",translations:["to depart"],derived:["reise ab","reist ab","reist ab"],varieties:[]},
  {base:"anreisen",past:"reiste an",participle:"angereist",translations:["to arrive"],derived:["reise an","reist an","reist an"],varieties:[]},
  {base:"übernachten",past:"übernachtete",participle:"übernachtet",translations:["to stay overnight"],derived:["übernachte","übernachtest","übernachtet","übernachten"],varieties:[{variant:"übernachten + in",prepositions:["in"],explanation:"To stay overnight in a place.",examples:["Wir übernachten im Hotel."]}]},
  {base:"campen",past:"campte",participle:"gecampt",translations:["to camp"],derived:["campe","campst","campt","campen"],varieties:[]},
  {base:"zelten",past:"zeltete",participle:"gezeltet",translations:["to camp in a tent"],derived:["zelte","zeltest","zeltet","zelten"],varieties:[]},
  {base:"parken",past:"parkte",participle:"geparkt",translations:["to park"],derived:["parke","parkst","parkt","parken"],varieties:[]},
  {base:"tanken",past:"tankte",participle:"getankt",translations:["to refuel"],derived:["tanke","tankst","tankt","tanken"],varieties:[]},
  {base:"bremsen",past:"bremste",participle:"gebremst",translations:["to brake"],derived:["bremse","bremst","bremst","bremsen"],varieties:[]},
  {base:"beschleunigen",past:"beschleunigte",participle:"beschleunigt",translations:["to accelerate"],derived:["beschleunige","beschleunigst","beschleunigt","beschleunigen"],varieties:[]},
  {base:"lenken",past:"lenkte",participle:"gelenkt",translations:["to steer"],derived:["lenke","lenkst","lenkt","lenken"],varieties:[]},
  {base:"überholen",past:"überholte",participle:"überholt",translations:["to overtake"],derived:["überhole","überholst","überholt","überholen"],varieties:[]},
  {base:"biegen",past:"bog",participle:"gebogen",translations:["to bend","to turn"],derived:["biege","biegst","biegt","biegen"],varieties:[]},
  {base:"abbiegen",past:"bog ab",participle:"abgebogen",translations:["to turn (direction)"],derived:["biege ab","biegst ab","biegt ab"],varieties:[]}
];

export default verbsA2;
