// verbs-db-b1.js - B1 Level - 250 verbs
const verbsB1 = [
  {base:"entscheiden",past:"entschied",participle:"entschieden",translations:["to decide"],derived:["entscheide","entscheidest","entscheidet"],varieties:[{variant:"entscheiden + über",prepositions:["über"],explanation:"To decide about something.",examples:["Wir entscheiden über das Projekt."]}]},
  {base:"vergessen",past:"vergaß",participle:"vergessen",translations:["to forget"],derived:["vergesse","vergisst","vergisst"],varieties:[]},
  {base:"teilnehmen",past:"nahm teil",participle:"teilgenommen",translations:["to participate"],derived:["nehme teil","nimmst teil","nimmt teil"],varieties:[{variant:"teilnehmen + an",prepositions:["an"],explanation:"To participate in.",examples:["Ich nehme an der Konferenz teil."]}]},
  {base:"sich interessieren",past:"interessierte sich",participle:"interessiert",translations:["to be interested"],reflexive:true,derived:["interessiere mich","interessierst dich","interessiert sich"],varieties:[{variant:"sich interessieren für",prepositions:["für"],explanation:"To be interested in.",examples:["Ich interessiere mich für Kunst."]}]},
  {base:"abhängen",past:"hing ab",participle:"abgehangen",translations:["to depend"],derived:["hänge ab","hängst ab","hängt ab"],varieties:[{variant:"abhängen + von",prepositions:["von"],explanation:"To depend on.",examples:["Es hängt vom Wetter ab."]}]},
  {base:"sich beschweren",past:"beschwerte sich",participle:"beschwert",translations:["to complain"],reflexive:true,derived:["beschwere mich","beschwerst dich","beschwert sich"],varieties:[{variant:"sich beschweren + über",prepositions:["über"],explanation:"To complain about.",examples:["Er beschwert sich über das Essen."]}]},
  {base:"sich erinnern",past:"erinnerte sich",participle:"erinnert",translations:["to remember"],reflexive:true,derived:["erinnere mich","erinnerst dich","erinnert sich"],varieties:[{variant:"sich erinnern + an",prepositions:["an"],explanation:"To remember something.",examples:["Ich erinnere mich an meinen ersten Schultag."]}]},
  {base:"sich unterhalten",past:"unterhielt sich",participle:"unterhalten",translations:["to converse"],reflexive:true,derived:["unterhalte mich","unterhältst dich","unterhält sich"],varieties:[{variant:"sich unterhalten + über",prepositions:["über"],explanation:"To talk about.",examples:["Wir unterhalten uns über das Wetter."]}]},
  {base:"vergleichen",past:"verglich",participle:"verglichen",translations:["to compare"],derived:["vergleiche","vergleichst","vergleicht"],varieties:[{variant:"vergleichen + mit",prepositions:["mit"],explanation:"To compare with.",examples:["Vergleich die Preise!"]}]},
  {base:"sich vorbereiten",past:"bereitete sich vor",participle:"vorbereitet",translations:["to prepare"],reflexive:true,derived:["bereite mich vor","bereitest dich vor","bereitet sich vor"],varieties:[{variant:"sich vorbereiten + auf",prepositions:["auf"],explanation:"To prepare for.",examples:["Ich bereite mich auf die Prüfung vor."]}]},
  {base:"erreichen",past:"erreichte",participle:"erreicht",translations:["to reach","to achieve"],derived:["erreiche","erreichst","erreicht"],varieties:[]},
  {base:"überzeugen",past:"überzeugte",participle:"überzeugt",translations:["to convince"],derived:["überzeuge","überzeugst","überzeugt"],varieties:[{variant:"überzeugen + von",prepositions:["von"],explanation:"To convince of.",examples:["Ich überzeuge dich von meiner Idee."]}]},
  {base:"sich gewöhnen",past:"gewöhnte sich",participle:"gewöhnt",translations:["to get used to"],reflexive:true,derived:["gewöhne mich","gewöhnst dich","gewöhnt sich"],varieties:[{variant:"sich gewöhnen + an",prepositions:["an"],explanation:"To get used to.",examples:["Ich gewöhne mich an das Wetter."]}]},
  {base:"vorziehen",past:"zog vor",participle:"vorgezogen",translations:["to prefer"],derived:["ziehe vor","ziehst vor","zieht vor"],varieties:[]},
  {base:"vorhaben",past:"hatte vor",participle:"vorgehabt",translations:["to intend","to plan"],derived:["habe vor","hast vor","hat vor"],varieties:[]},
  {base:"beabsichtigen",past:"beabsichtigte",participle:"beabsichtigt",translations:["to intend"],derived:["beabsichtige","beabsichtigst","beabsichtigt"],varieties:[]},
  {base:"schaffen",past:"schaffte",participle:"geschafft",translations:["to manage","to create"],derived:["schaffe","schaffst","schafft"],varieties:[]},
  {base:"erledigen",past:"erledigte",participle:"erledigt",translations:["to complete","to finish"],derived:["erledige","erledigst","erledigt"],varieties:[]},
  {base:"vollenden",past:"vollendete",participle:"vollendet",translations:["to complete"],derived:["vollende","vollendest","vollendet"],varieties:[]},
  {base:"fortsetzen",past:"setzte fort",participle:"fortgesetzt",translations:["to continue"],derived:["setze fort","setzt fort","setzt fort"],varieties:[]},
  {base:"weitermachen",past:"machte weiter",participle:"weitergemacht",translations:["to continue"],derived:["mache weiter","machst weiter","macht weiter"],varieties:[]},
  {base:"pausieren",past:"pausierte",participle:"pausiert",translations:["to pause","to take a break"],derived:["pausiere","pausierst","pausiert"],varieties:[]},
  {base:"unterbrechen",past:"unterbrach",participle:"unterbrochen",translations:["to interrupt"],derived:["unterbreche","unterbrichst","unterbricht"],varieties:[]},
  {base:"stören",past:"störte",participle:"gestört",translations:["to disturb"],derived:["störe","störst","stört"],varieties:[]},
  {base:"behindern",past:"behinderte",participle:"behindert",translations:["to hinder","to obstruct"],derived:["behindere","behinderst","behindert"],varieties:[]},
  {base:"unterstützen",past:"unterstützte",participle:"unterstützt",translations:["to support"],derived:["unterstütze","unterstützt","unterstützt"],varieties:[]},
  {base:"fördern",past:"förderte",participle:"gefördert",translations:["to promote","to support"],derived:["fördere","förderst","fördert"],varieties:[]},
  {base:"ermutigen",past:"ermutigte",participle:"ermutigt",translations:["to encourage"],derived:["ermutige","ermutigst","ermutigt"],varieties:[]},
  {base:"entmutigen",past:"entmutigte",participle:"entmutigt",translations:["to discourage"],derived:["entmutige","entmutigst","entmutigt"],varieties:[]},
  {base:"motivieren",past:"motivierte",participle:"motiviert",translations:["to motivate"],derived:["motiviere","motivierst","motiviert"],varieties:[]},
  {base:"inspirieren",past:"inspirierte",participle:"inspiriert",translations:["to inspire"],derived:["inspiriere","inspirierst","inspiriert"],varieties:[]},
  {base:"beeinflussen",past:"beeinflusste",participle:"beeinflusst",translations:["to influence"],derived:["beeinflusse","beeinflusst","beeinflusst"],varieties:[]},
  {base:"verändern",past:"veränderte",participle:"verändert",translations:["to change"],derived:["verändere","veränderst","verändert"],varieties:[]},
  {base:"umwandeln",past:"wandelte um",participle:"umgewandelt",translations:["to transform"],derived:["wandle um","wandelst um","wandelt um"],varieties:[]},
  {base:"verwandeln",past:"verwandelte",participle:"verwandelt",translations:["to transform"],derived:["verwandle","verwandelst","verwandelt"],varieties:[]},
  {base:"entwickeln",past:"entwickelte",participle:"entwickelt",translations:["to develop"],derived:["entwickle","entwickelst","entwickelt"],varieties:[]},
  {base:"gestalten",past:"gestaltete",participle:"gestaltet",translations:["to design","to shape"],derived:["gestalte","gestaltest","gestaltet"],varieties:[]},
  {base:"formen",past:"formte",participle:"geformt",translations:["to form","to shape"],derived:["forme","formst","formt"],varieties:[]},
  {base:"bilden",past:"bildete",participle:"gebildet",translations:["to form","to educate"],derived:["bilde","bildest","bildet"],varieties:[]},
  {base:"ausbilden",past:"bildete aus",participle:"ausgebildet",translations:["to train"],derived:["bilde aus","bildest aus","bildet aus"],varieties:[]},
  {base:"erziehen",past:"erzog",participle:"erzogen",translations:["to educate","to raise"],derived:["erziehe","erziehst","erzieht"],varieties:[]},
  {base:"unterrichten",past:"unterrichtete",participle:"unterrichtet",translations:["to teach","to instruct"],derived:["unterrichte","unterrichtest","unterrichtet"],varieties:[]},
  {base:"beibringen",past:"brachte bei",participle:"beigebracht",translations:["to teach"],derived:["bringe bei","bringst bei","bringt bei"],varieties:[]},
  {base:"vermitteln",past:"vermittelte",participle:"vermittelt",translations:["to mediate","to convey"],derived:["vermittle","vermittelst","vermittelt"],varieties:[]},
  {base:"übertragen",past:"übertrug",participle:"übertragen",translations:["to transfer","to transmit"],derived:["übertrage","überträgst","überträgt"],varieties:[]},
  {base:"weitergeben",past:"gab weiter",participle:"weitergegeben",translations:["to pass on"],derived:["gebe weiter","gibst weiter","gibt weiter"],varieties:[]},
  {base:"überliefern",past:"überlieferte",participle:"überliefert",translations:["to hand down","to transmit"],derived:["überliefere","überlieferst","überliefert"],varieties:[]},
  {base:"bewahren",past:"bewahrte",participle:"bewahrt",translations:["to preserve","to keep"],derived:["bewahre","bewahrst","bewahrt"],varieties:[]},
  {base:"erhalten",past:"erhielt",participle:"erhalten",translations:["to receive","to preserve"],derived:["erhalte","erhältst","erhält"],varieties:[]},
  {base:"behalten",past:"behielt",participle:"behalten",translations:["to keep","to retain"],derived:["behalte","behältst","behält"],varieties:[]},
  {base:"aufbewahren",past:"bewahrte auf",participle:"aufbewahrt",translations:["to store","to keep"],derived:["bewahre auf","bewahrst auf","bewahrt auf"],varieties:[]},
  {base:"lagern",past:"lagerte",participle:"gelagert",translations:["to store"],derived:["lagere","lagerst","lagert"],varieties:[]},
  {base:"speichern",past:"speicherte",participle:"gespeichert",translations:["to save","to store"],derived:["speichere","speicherst","speichert"],varieties:[]},
  {base:"sichern",past:"sicherte",participle:"gesichert",translations:["to secure","to back up"],derived:["sichere","sicherst","sichert"],varieties:[]},
  {base:"schützen",past:"schützte",participle:"geschützt",translations:["to protect"],derived:["schütze","schützt","schützt"],varieties:[]},
  {base:"verteidigen",past:"verteidigte",participle:"verteidigt",translations:["to defend"],derived:["verteidige","verteidigst","verteidigt"],varieties:[]},
  {base:"bewachen",past:"bewachte",participle:"bewacht",translations:["to guard"],derived:["bewache","bewachst","bewacht"],varieties:[]},
  {base:"überwachen",past:"überwachte",participle:"überwacht",translations:["to monitor","to supervise"],derived:["überwache","überwachst","überwacht"],varieties:[]},
  {base:"kontrollieren",past:"kontrollierte",participle:"kontrolliert",translations:["to control","to check"],derived:["kontrolliere","kontrollierst","kontrolliert"],varieties:[]},
  {base:"überprüfen",past:"überprüfte",participle:"überprüft",translations:["to check","to verify"],derived:["überprüfe","überprüfst","überprüft"],varieties:[]},
  {base:"nachprüfen",past:"prüfte nach",participle:"nachgeprüft",translations:["to verify","to check"],derived:["prüfe nach","prüfst nach","prüft nach"],varieties:[]},
  {base:"verifizieren",past:"verifizierte",participle:"verifiziert",translations:["to verify"],derived:["verifiziere","verifizierst","verifiziert"],varieties:[]},
  {base:"bestätigen",past:"bestätigte",participle:"bestätigt",translations:["to confirm"],derived:["bestätige","bestätigst","bestätigt"],varieties:[]},
  {base:"versichern",past:"versicherte",participle:"versichert",translations:["to assure","to insure"],derived:["versichere","versicherst","versichert"],varieties:[]},
  {base:"zusichern",past:"sicherte zu",participle:"zugesichert",translations:["to assure"],derived:["sichere zu","sicherst zu","sichert zu"],varieties:[]},
  {base:"bezweifeln",past:"bezweifelte",participle:"bezweifelt",translations:["to doubt"],derived:["bezweifle","bezweifelst","bezweifelt"],varieties:[]},
  {base:"anzweifeln",past:"zweifelte an",participle:"angezweifelt",translations:["to question","to doubt"],derived:["zweifle an","zweifelst an","zweifelt an"],varieties:[]},
  {base:"misstrauen",past:"misstraute",participle:"misstraut",translations:["to distrust"],derived:["misstraue","misstraust","misstraut"],varieties:[]},
  {base:"trauen",past:"traute",participle:"getraut",translations:["to trust","to dare"],derived:["traue","traust","traut"],varieties:[]},
  {base:"vertrauen",past:"vertraute",participle:"vertraut",translations:["to trust"],derived:["vertraue","vertraust","vertraut"],varieties:[{variant:"vertrauen + auf",prepositions:["auf"],explanation:"To trust in.",examples:["Ich vertraue auf dich."]}]},
  {base:"verlassen",past:"verließ",participle:"verlassen",translations:["to leave","to rely on"],derived:["verlasse","verlässt","verlässt"],varieties:[{variant:"sich verlassen + auf",prepositions:["auf"],explanation:"To rely on.",examples:["Ich verlasse mich auf dich."]}]},
  {base:"rechnen",past:"rechnete",participle:"gerechnet",translations:["to calculate","to count on"],derived:["rechne","rechnest","rechnet"],varieties:[{variant:"rechnen + mit",prepositions:["mit"],explanation:"To count on.",examples:["Ich rechne mit deiner Hilfe."]}]},
  {base:"hoffen",past:"hoffte",participle:"gehofft",translations:["to hope"],derived:["hoffe","hoffst","hofft"],varieties:[{variant:"hoffen + auf",prepositions:["auf"],explanation:"To hope for.",examples:["Ich hoffe auf gutes Wetter."]}]},
  {base:"erwarten",past:"erwartete",participle:"erwartet",translations:["to expect"],derived:["erwarte","erwartest","erwartet"],varieties:[]},
  {base:"befürchten",past:"befürchtete",participle:"befürchtet",translations:["to fear"],derived:["befürchte","befürchtest","befürchtet"],varieties:[]},
  {base:"fürchten",past:"fürchtete",participle:"gefürchtet",translations:["to fear"],derived:["fürchte","fürchtest","fürchtet"],varieties:[{variant:"sich fürchten + vor",prepositions:["vor"],explanation:"To be afraid of.",examples:["Ich fürchte mich vor Spinnen."]}]},
  {base:"ängstigen",past:"ängstigte",participle:"geängstigt",translations:["to frighten"],derived:["ängstige","ängstigst","ängstigt"],varieties:[]},
  {base:"erschrecken",past:"erschrak",participle:"erschrocken",translations:["to be frightened"],derived:["erschrecke","erschrickst","erschrickt"],varieties:[]},
  {base:"beunruhigen",past:"beunruhigte",participle:"beunruhigt",translations:["to worry","to disturb"],derived:["beunruhige","beunruhigst","beunruhigt"],varieties:[]},
  {base:"beruhigen",past:"beruhigte",participle:"beruhigt",translations:["to calm"],derived:["beruhige","beruhigst","beruhigt"],varieties:[]},
  {base:"trösten",past:"tröstete",participle:"getröstet",translations:["to comfort"],derived:["tröste","tröstest","tröstet"],varieties:[]},
  {base:"aufmuntern",past:"munterte auf",participle:"aufgemuntert",translations:["to cheer up"],derived:["muntere auf","munterst auf","muntert auf"],varieties:[]},
  {base:"erheitern",past:"heiterte auf",participle:"aufgeheitert",translations:["to cheer up"],derived:["heitere auf","heiterst auf","heitert auf"],varieties:[]},
  {base:"amüsieren",past:"amüsierte",participle:"amüsiert",translations:["to amuse"],derived:["amüsiere","amüsierst","amüsiert"],varieties:[]},
  {base:"unterhalten",past:"unterhielt",participle:"unterhalten",translations:["to entertain"],derived:["unterhalte","unterhältst","unterhält"],varieties:[]},
  {base:"langweilen",past:"langweilte",participle:"gelangweilt",translations:["to bore"],derived:["langweile","langweilst","langweilt"],varieties:[]},
  {base:"interessieren",past:"interessierte",participle:"interessiert",translations:["to interest"],derived:["interessiere","interessierst","interessiert"],varieties:[]},
  {base:"faszinieren",past:"faszinierte",participle:"fasziniert",translations:["to fascinate"],derived:["fasziniere","faszinierst","fasziniert"],varieties:[]},
  {base:"begeistern",past:"begeisterte",participle:"begeistert",translations:["to enthuse","to inspire"],derived:["begeistere","begeisterst","begeistert"],varieties:[]},
  {base:"enttäuschen",past:"enttäuschte",participle:"enttäuscht",translations:["to disappoint"],derived:["enttäusche","enttäuschst","enttäuscht"],varieties:[]},
  {base:"überraschen",past:"überraschte",participle:"überrascht",translations:["to surprise"],derived:["überrasche","überraschst","überrascht"],varieties:[]},
  {base:"schocken",past:"schockte",participle:"geschockt",translations:["to shock"],derived:["schocke","schockst","schockt"],varieties:[]},
  {base:"verblüffen",past:"verblüffte",participle:"verblüfft",translations:["to amaze","to astound"],derived:["verblüffe","verblüffst","verblüfft"],varieties:[]},
  {base:"erstaunen",past:"erstaunte",participle:"erstaunt",translations:["to astonish"],derived:["erstaune","erstaunst","erstaunt"],varieties:[]},
  {base:"verwundern",past:"verwunderte",participle:"verwundert",translations:["to surprise"],derived:["verwundere","verwunderst","verwundert"],varieties:[]},
  {base:"irritieren",past:"irritierte",participle:"irritiert",translations:["to irritate","to confuse"],derived:["irritiere","irritierst","irritiert"],varieties:[]},
  {base:"verwirren",past:"verwirrte",participle:"verwirrt",translations:["to confuse"],derived:["verwirre","verwirrst","verwirrt"],varieties:[]},
  {base:"durcheinanderbringen",past:"brachte durcheinander",participle:"durcheinandergebracht",translations:["to confuse"],derived:["bringe durcheinander","bringst durcheinander","bringt durcheinander"],varieties:[]},
  {base:"aufklären",past:"klärte auf",participle:"aufgeklärt",translations:["to clarify","to enlighten"],derived:["kläre auf","klärst auf","klärt auf"],varieties:[]},
  {base:"erläutern",past:"erläuterte",participle:"erläutert",translations:["to explain","to illustrate"],derived:["erläutere","erläuterst","erläutert"],varieties:[]},
  {base:"verdeutlichen",past:"verdeutlichte",participle:"verdeutlicht",translations:["to clarify"],derived:["verdeutliche","verdeutlichst","verdeutlicht"],varieties:[]},
  {base:"veranschaulichen",past:"veranschaulichte",participle:"veranschaulicht",translations:["to illustrate"],derived:["veranschauliche","veranschaulichst","veranschaulicht"],varieties:[]},
  {base:"illustrieren",past:"illustrierte",participle:"illustriert",translations:["to illustrate"],derived:["illustriere","illustrierst","illustriert"],varieties:[]},
  {base:"darstellen",past:"stellte dar",participle:"dargestellt",translations:["to represent","to depict"],derived:["stelle dar","stellst dar","stellt dar"],varieties:[]},
  {base:"schildern",past:"schilderte",participle:"geschildert",translations:["to describe","to depict"],derived:["schildere","schilderst","schildert"],varieties:[]},
  {base:"erzählen",past:"erzählte",participle:"erzählt",translations:["to tell","to narrate"],derived:["erzähle","erzählst","erzählt"],varieties:[]},
  {base:"berichten",past:"berichtete",participle:"berichtet",translations:["to report"],derived:["berichte","berichtest","berichtet"],varieties:[]},
  {base:"mitteilen",past:"teilte mit",participle:"mitgeteilt",translations:["to inform","to communicate"],derived:["teile mit","teilst mit","teilt mit"],varieties:[]},
  {base:"informieren",past:"informierte",participle:"informiert",translations:["to inform"],derived:["informiere","informierst","informiert"],varieties:[]},
  {base:"benachrichtigen",past:"benachrichtigte",participle:"benachrichtigt",translations:["to notify"],derived:["benachrichtige","benachrichtigst","benachrichtigt"],varieties:[]},
  {base:"ankündigen",past:"kündigte an",participle:"angekündigt",translations:["to announce"],derived:["kündige an","kündigst an","kündigt an"],varieties:[]},
  {base:"verkünden",past:"verkündete",participle:"verkündet",translations:["to announce","to proclaim"],derived:["verkünde","verkündest","verkündet"],varieties:[]},
  {base:"bekanntgeben",past:"gab bekannt",participle:"bekanntgegeben",translations:["to announce"],derived:["gebe bekannt","gibst bekannt","gibt bekannt"],varieties:[]},
  {base:"veröffentlichen",past:"veröffentlichte",participle:"veröffentlicht",translations:["to publish"],derived:["veröffentliche","veröffentlichst","veröffentlicht"],varieties:[]},
  {base:"publizieren",past:"publizierte",participle:"publiziert",translations:["to publish"],derived:["publiziere","publizierst","publiziert"],varieties:[]},
  {base:"herausgeben",past:"gab heraus",participle:"herausgegeben",translations:["to publish","to issue"],derived:["gebe heraus","gibst heraus","gibt heraus"],varieties:[]},
  {base:"drucken",past:"druckte",participle:"gedruckt",translations:["to print"],derived:["drucke","druckst","druckt"],varieties:[]},
  {base:"ausdrucken",past:"druckte aus",participle:"ausgedruckt",translations:["to print out"],derived:["drucke aus","druckst aus","druckt aus"],varieties:[]},
  {base:"kopieren",past:"kopierte",participle:"kopiert",translations:["to copy"],derived:["kopiere","kopierst","kopiert"],varieties:[]},
  {base:"vervielfältigen",past:"vervielfältigte",participle:"vervielfältigt",translations:["to duplicate"],derived:["vervielfältige","vervielfältigst","vervielfältigt"],varieties:[]},
  {base:"nachahmen",past:"ahmte nach",participle:"nachgeahmt",translations:["to imitate"],derived:["ahme nach","ahmst nach","ahmt nach"],varieties:[]},
  {base:"imitieren",past:"imitierte",participle:"imitiert",translations:["to imitate"],derived:["imitiere","imitierst","imitiert"],varieties:[]},
  {base:"nachbilden",past:"bildete nach",participle:"nachgebildet",translations:["to replicate"],derived:["bilde nach","bildest nach","bildet nach"],varieties:[]},
  {base:"reproduzieren",past:"reproduzierte",participle:"reproduziert",translations:["to reproduce"],derived:["reproduziere","reproduzierst","reproduziert"],varieties:[]},
  {base:"herstellen",past:"stellte her",participle:"hergestellt",translations:["to produce","to manufacture"],derived:["stelle her","stellst her","stellt her"],varieties:[]},
  {base:"produzieren",past:"produzierte",participle:"produziert",translations:["to produce"],derived:["produziere","produzierst","produziert"],varieties:[]},
  {base:"erzeugen",past:"erzeugte",participle:"erzeugt",translations:["to produce","to generate"],derived:["erzeuge","erzeugst","erzeugt"],varieties:[]},
  {base:"generieren",past:"generierte",participle:"generiert",translations:["to generate"],derived:["generiere","generierst","generiert"],varieties:[]},
  {base:"erstellen",past:"erstellte",participle:"erstellt",translations:["to create"],derived:["erstelle","erstellst","erstellt"],varieties:[]},
  {base:"anfertigen",past:"fertigte an",participle:"angefertigt",translations:["to make","to produce"],derived:["fertige an","fertigst an","fertigt an"],varieties:[]},
  {base:"konstruieren",past:"konstruierte",participle:"konstruiert",translations:["to construct"],derived:["konstruiere","konstruierst","konstruiert"],varieties:[]},
  {base:"bauen",past:"baute",participle:"gebaut",translations:["to build"],derived:["baue","baust","baut"],varieties:[]},
  {base:"errichten",past:"errichtete",participle:"errichtet",translations:["to erect","to build"],derived:["errichte","errichtest","errichtet"],varieties:[]},
  {base:"aufbauen",past:"baute auf",participle:"aufgebaut",translations:["to build up","to construct"],derived:["baue auf","baust auf","baut auf"],varieties:[]},
  {base:"ausbauen",past:"baute aus",participle:"ausgebaut",translations:["to expand","to extend"],derived:["baue aus","baust aus","baut aus"],varieties:[]},
  {base:"umbauen",past:"baute um",participle:"umgebaut",translations:["to rebuild","to renovate"],derived:["baue um","baust um","baut um"],varieties:[]},
  {base:"abbauen",past:"baute ab",participle:"abgebaut",translations:["to dismantle","to reduce"],derived:["baue ab","baust ab","baut ab"],varieties:[]},
  {base:"zerstören",past:"zerstörte",participle:"zerstört",translations:["to destroy"],derived:["zerstöre","zerstörst","zerstört"],varieties:[]},
  {base:"vernichten",past:"vernichtete",participle:"vernichtet",translations:["to destroy","to annihilate"],derived:["vernichte","vernichtest","vernichtet"],varieties:[]},
  {base:"ruinieren",past:"ruinierte",participle:"ruiniert",translations:["to ruin"],derived:["ruiniere","ruinierst","ruiniert"],varieties:[]},
  {base:"beschädigen",past:"beschädigte",participle:"beschädigt",translations:["to damage"],derived:["beschädige","beschädigst","beschädigt"],varieties:[]},
  {base:"verletzen",past:"verletzte",participle:"verletzt",translations:["to injure","to hurt"],derived:["verletze","verletzt","verletzt"],varieties:[]},
  {base:"schaden",past:"schadete",participle:"geschadet",translations:["to harm","to damage"],derived:["schade","schadest","schadet"],varieties:[]},
  {base:"beeinträchtigen",past:"beeinträchtigte",participle:"beeinträchtigt",translations:["to impair","to affect negatively"],derived:["beeinträchtige","beeinträchtigst","beeinträchtigt"],varieties:[]},
  {base:"schädigen",past:"schädigte",participle:"geschädigt",translations:["to harm","to damage"],derived:["schädige","schädigst","schädigt"],varieties:[]},
  {base:"gefährden",past:"gefährdete",participle:"gefährdet",translations:["to endanger"],derived:["gefährde","gefährdest","gefährdet"],varieties:[]},
  {base:"bedrohen",past:"bedrohte",participle:"bedroht",translations:["to threaten"],derived:["bedrohe","bedrohst","bedroht"],varieties:[]},
  {base:"retten",past:"rettete",participle:"gerettet",translations:["to save","to rescue"],derived:["rette","rettest","rettet"],varieties:[]},
  {base:"befreien",past:"befreite",participle:"befreit",translations:["to free","to liberate"],derived:["befreie","befreist","befreit"],varieties:[]},
  {base:"erlösen",past:"erlöste",participle:"erlöst",translations:["to redeem","to deliver"],derived:["erlöse","erlöst","erlöst"],varieties:[]},
  {base:"heilen",past:"heilte",participle:"geheilt",translations:["to heal","to cure"],derived:["heile","heilst","heilt"],varieties:[]},
  {base:"behandeln",past:"behandelte",participle:"behandelt",translations:["to treat"],derived:["behandle","behandelst","behandelt"],varieties:[]},
  {base:"pflegen",past:"pflegte",participle:"gepflegt",translations:["to care for","to nurse"],derived:["pflege","pflegst","pflegt"],varieties:[]},
  {base:"versorgen",past:"versorgte",participle:"versorgt",translations:["to provide","to supply"],derived:["versorge","versorgst","versorgt"],varieties:[]},
  {base:"beliefern",past:"belieferte",participle:"beliefert",translations:["to supply"],derived:["beliefere","belieferst","beliefert"],varieties:[]},
  {base:"liefern",past:"lieferte",participle:"geliefert",translations:["to deliver","to supply"],derived:["liefere","lieferst","liefert"],varieties:[]},
  {base:"abliefern",past:"lieferte ab",participle:"abgeliefert",translations:["to deliver","to hand in"],derived:["liefere ab","lieferst ab","liefert ab"],varieties:[]},
  {base:"ausliefern",past:"lieferte aus",participle:"ausgeliefert",translations:["to deliver","to extradite"],derived:["liefere aus","lieferst aus","liefert aus"],varieties:[]},
  {base:"zurückgeben",past:"gab zurück",participle:"zurückgegeben",translations:["to return","to give back"],derived:["gebe zurück","gibst zurück","gibt zurück"],varieties:[]},
  {base:"herausgeben",past:"gab heraus",participle:"herausgegeben",translations:["to hand over","to return"],derived:["gebe heraus","gibst heraus","gibt heraus"],varieties:[]},
  {base:"übergeben",past:"übergab",participle:"übergeben",translations:["to hand over"],derived:["übergebe","übergibst","übergibt"],varieties:[]},
  {base:"weitergeben",past:"gab weiter",participle:"weitergegeben",translations:["to pass on"],derived:["gebe weiter","gibst weiter","gibt weiter"],varieties:[]},
  {base:"abgeben",past:"gab ab",participle:"abgegeben",translations:["to hand in","to give up"],derived:["gebe ab","gibst ab","gibt ab"],varieties:[]},
  {base:"aufgeben",past:"gab auf",participle:"aufgegeben",translations:["to give up","to abandon"],derived:["gebe auf","gibst auf","gibt auf"],varieties:[]},
  {base:"verzichten",past:"verzichtete",participle:"verzichtet",translations:["to renounce","to do without"],derived:["verzichte","verzichtest","verzichtet"],varieties:[{variant:"verzichten + auf",prepositions:["auf"],explanation:"To do without.",examples:["Ich verzichte auf Zucker."]}]},
  {base:"entsagen",past:"entsagte",participle:"entsagt",translations:["to renounce"],derived:["entsage","entsagst","entsagt"],varieties:[]},
  {base:"enthalten",past:"enthielt",participle:"enthalten",translations:["to contain","to refrain"],derived:["enthalte","enthältst","enthält"],varieties:[{variant:"sich enthalten",explanation:"Reflexive: to abstain.",examples:["Ich enthalte mich der Stimme."]}]},
  {base:"vermeiden",past:"vermied",participle:"vermieden",translations:["to avoid"],derived:["vermeide","vermeidest","vermeidet"],varieties:[]},
  {base:"umgehen",past:"ging um",participle:"umgangen",translations:["to bypass","to avoid"],derived:["gehe um","gehst um","geht um"],varieties:[]},
  {base:"ausweichen",past:"wich aus",participle:"ausgewichen",translations:["to evade","to dodge"],derived:["weiche aus","weichst aus","weicht aus"],varieties:[]},
  {base:"fliehen",past:"floh",participle:"geflohen",translations:["to flee"],derived:["fliehe","fliehst","flieht"],varieties:[]},
  {base:"entkommen",past:"entkam",participle:"entkommen",translations:["to escape"],derived:["entkomme","entkommst","entkommt"],varieties:[]},
  {base:"entfliehen",past:"entfloh",participle:"entflohen",translations:["to escape"],derived:["entfliehe","entfliehst","entflieht"],varieties:[]},
  {base:"entwischen",past:"entwischte",participle:"entwischt",translations:["to escape","to slip away"],derived:["entwische","entwischst","entwischt"],varieties:[]},
  {base:"davonkommen",past:"kam davon",participle:"davongekommen",translations:["to get away"],derived:["komme davon","kommst davon","kommt davon"],varieties:[]},
  {base:"weglaufen",past:"lief weg",participle:"weggelaufen",translations:["to run away"],derived:["laufe weg","läufst weg","läuft weg"],varieties:[]},
  {base:"fortlaufen",past:"lief fort",participle:"fortgelaufen",translations:["to run away"],derived:["laufe fort","läufst fort","läuft fort"],varieties:[]},
  {base:"wegrennen",past:"rannte weg",participle:"weggerannt",translations:["to run away"],derived:["renne weg","rennst weg","rennt weg"],varieties:[]},
  {base:"davonrennen",past:"rannte davon",participle:"davongerannt",translations:["to run off"],derived:["renne davon","rennst davon","rennt davon"],varieties:[]},
  {base:"fangen",past:"fing",participle:"gefangen",translations:["to catch"],derived:["fange","fängst","fängt"],varieties:[]},
  {base:"einfangen",past:"fing ein",participle:"eingefangen",translations:["to capture"],derived:["fange ein","fängst ein","fängt ein"],varieties:[]},
  {base:"einholen",past:"holte ein",participle:"eingeholt",translations:["to catch up"],derived:["hole ein","holst ein","holt ein"],varieties:[]},
  {base:"verfolgen",past:"verfolgte",participle:"verfolgt",translations:["to pursue","to follow"],derived:["verfolge","verfolgst","verfolgt"],varieties:[]},
  {base:"nachfolgen",past:"folgte nach",participle:"nachgefolgt",translations:["to follow","to succeed"],derived:["folge nach","folgst nach","folgt nach"],varieties:[]},
  {base:"begleiten",past:"begleitete",participle:"begleitet",translations:["to accompany"],derived:["begleite","begleitest","begleitet"],varieties:[]},
  {base:"eskortieren",past:"eskortierte",participle:"eskortiert",translations:["to escort"],derived:["eskortiere","eskortierst","eskortiert"],varieties:[]},
  {base:"geleiten",past:"geleitete",participle:"geleitet",translations:["to escort","to conduct"],derived:["geleite","geleitest","geleitet"],varieties:[]},
  {base:"führen",past:"führte",participle:"geführt",translations:["to lead","to guide"],derived:["führe","führst","führt"],varieties:[]},
  {base:"leiten",past:"leitete",participle:"geleitet",translations:["to lead","to manage"],derived:["leite","leitest","leitet"],varieties:[]},
  {base:"lenken",past:"lenkte",participle:"gelenkt",translations:["to steer","to direct"],derived:["lenke","lenkst","lenkt"],varieties:[]},
  {base:"dirigieren",past:"dirigierte",participle:"dirigiert",translations:["to conduct","to direct"],derived:["dirigiere","dirigierst","dirigiert"],varieties:[]},
  {base:"regieren",past:"regierte",participle:"regiert",translations:["to govern","to rule"],derived:["regiere","regierst","regiert"],varieties:[]},
  {base:"beherrschen",past:"beherrschte",participle:"beherrscht",translations:["to master","to dominate"],derived:["beherrsche","beherrschst","beherrscht"],varieties:[]},
  {base:"dominieren",past:"dominierte",participle:"dominiert",translations:["to dominate"],derived:["dominiere","dominierst","dominiert"],varieties:[]},
  {base:"unterdrücken",past:"unterdrückte",participle:"unterdrückt",translations:["to suppress","to oppress"],derived:["unterdrücke","unterdrückst","unterdrückt"],varieties:[]},
  {base:"unterwerfen",past:"unterwarf",participle:"unterworfen",translations:["to subjugate"],derived:["unterwerfe","unterwirfst","unterwirft"],varieties:[]},
  {base:"erobern",past:"eroberte",participle:"erobert",translations:["to conquer"],derived:["erobere","eroberst","erobert"],varieties:[]},
  {base:"besiegen",past:"besiegte",participle:"besiegt",translations:["to defeat"],derived:["besiege","besiegst","besiegt"],varieties:[]},
  {base:"überwinden",past:"überwand",participle:"überwunden",translations:["to overcome"],derived:["überwinde","überwindest","überwindet"],varieties:[]},
  {base:"bewältigen",past:"bewältigte",participle:"bewältigt",translations:["to cope with","to master"],derived:["bewältige","bewältigst","bewältigt"],varieties:[]},
  {base:"meistern",past:"meisterte",participle:"gemeistert",translations:["to master"],derived:["meistere","meisterst","meistert"],varieties:[]},
  {base:"bewältigen",past:"bewältigte",participle:"bewältigt",translations:["to cope with"],derived:["bewältige","bewältigst","bewältigt"],varieties:[]},
  {base:"managen",past:"managte",participle:"gemanagt",translations:["to manage"],derived:["manage","managst","managt"],varieties:[]},
  {base:"handhaben",past:"handhabte",participle:"gehandhabt",translations:["to handle"],derived:["handhabe","handhabst","handhabt"],varieties:[]},
  {base:"bedienen",past:"bediente",participle:"bedient",translations:["to serve","to operate"],derived:["bediene","bedienst","bedient"],varieties:[]},
  {base:"betätigen",past:"betätigte",participle:"betätigt",translations:["to operate","to activate"],derived:["betätige","betätigst","betätigt"],varieties:[]},
  {base:"betreiben",past:"betrieb",participle:"betrieben",translations:["to operate","to run"],derived:["betreibe","betreibst","betreibt"],varieties:[]},
  {base:"führen",past:"führte",participle:"geführt",translations:["to run","to manage"],derived:["führe","führst","führt"],varieties:[]},
  {base:"verwalten",past:"verwaltete",participle:"verwaltet",translations:["to manage","to administer"],derived:["verwalte","verwaltest","verwaltet"],varieties:[]},
  {base:"administrieren",past:"administrierte",participle:"administriert",translations:["to administer"],derived:["administriere","administrierst","administriert"],varieties:[]},
  {base:"koordinieren",past:"koordinierte",participle:"koordiniert",translations:["to coordinate"],derived:["koordiniere","koordinierst","koordiniert"],varieties:[]},
  {base:"organisieren",past:"organisierte",participle:"organisiert",translations:["to organize"],derived:["organisiere","organisierst","organisiert"],varieties:[]},
  {base:"arrangieren",past:"arrangierte",participle:"arrangiert",translations:["to arrange"],derived:["arrangiere","arrangierst","arrangiert"],varieties:[]},
  {base:"vereinbaren",past:"vereinbarte",participle:"vereinbart",translations:["to arrange","to agree on"],derived:["vereinbare","vereinbarst","vereinbart"],varieties:[]},
  {base:"verabreden",past:"verabredete",participle:"verabredet",translations:["to arrange","to make an appointment"],derived:["verabrede","verabredest","verabredet"],varieties:[{variant:"sich verabreden + mit",prepositions:["mit"],explanation:"To arrange to meet with someone.",examples:["Ich verabrede mich mit meinem Freund."]}]},
  {base:"treffen",past:"traf",participle:"getroffen",translations:["to meet","to hit"],derived:["treffe","triffst","trifft"],varieties:[{variant:"sich treffen + mit",prepositions:["mit"],explanation:"To meet with someone.",examples:["Ich treffe mich mit dir."]}]},
  {base:"begegnen",past:"begegnete",participle:"begegnet",translations:["to meet","to encounter"],derived:["begegne","begegnest","begegnet"],varieties:[]},
  {base:"zusammentreffen",past:"traf zusammen",participle:"zusammengetroffen",translations:["to meet"],derived:["treffe zusammen","triffst zusammen","trifft zusammen"],varieties:[]},
  {base:"zusammenkommen",past:"kam zusammen",participle:"zusammengekommen",translations:["to meet","to gather"],derived:["komme zusammen","kommst zusammen","kommt zusammen"],varieties:[]},
  {base:"versammeln",past:"versammelte",participle:"versammelt",translations:["to gather","to assemble"],derived:["versammle","versammelst","versammelt"],varieties:[{variant:"sich versammeln",explanation:"Reflexive: to gather.",examples:["Wir versammeln uns im Park."]}]}
];

export default verbsB1;
